#!/usr/bin/env php
<?php namespace Randomizer;
$start = microtime(true);
require_once('vendor/autoload.php');

use Monolog\Formatter\LineFormatter;
use Monolog\Handler\ErrorLogHandler;
use Monolog\Logger;
use Randomizer\Support\Config;

/**
 * Egs:
 *
 * do {
 *    $rand = new Randomizer($logger);
 *    $rand->setSpoilerFile(false)->makeSeed();
 * } while (!$rand->getWorld()->getLocation('Ether Tablet')->hasItem(Item::get('MoonPearl')));
 * $rand->save();
 *
 * $rand->getWorld()->getLocation("[cave-040] Link's House")->setItem(Item::get('MoonPearl'));
 */

$logger = new Logger('randomizer');
$logger->pushHandler((new ErrorLogHandler(null, Logger::INFO))->setFormatter(new LineFormatter('%message%')));

$rand = new Randomizer(Config::rules('v7'), $logger);
$rand->makeSeed();
$rand->save('out/alttp - v7p.%s.sfc');

$logger->debug("Stats:");
$logger->debug("Run Time: " . round(microtime(true) - $start, 2) . "s");
$logger->debug("Memory Usage: " . memory_get_usage(true) / 1024 / 1204 . "MB");
