#!/usr/bin/env php
<?php namespace Randomizer;
$start = microtime(true);
require_once('vendor/autoload.php');

use Monolog\Formatter\LineFormatter;
use Monolog\Handler\ErrorLogHandler;
use Monolog\Logger;
use Randomizer\Support\Config;

/**
 * Egs:
 *
 * do {
 *    $rand = new Randomizer($logger);
 *    $rand->setSpoilerFile(false)->makeSeed();
 * } while (!$rand->getWorld()->getLocation('Ether Tablet')->hasItem(Item::get('MoonPearl')));
 * $rand->save();
 *
 * $rand->getWorld()->getLocation("[cave-040] Link's House")->setItem(Item::get('MoonPearl'));
 */

$config_v7 = new Config([
    'shuffle_prizes_cross_world' => false,
    'count_TenArrows' => 11,
    'count_ThreeBombs' => 17,
    'count_BombUpgrade5' => 0,
    'count_BombUpgrade10' => 0,
    'count_BombUpgrade50' => 1,
    'count_ArrowUpgrade5' => 0,
    'count_ArrowUpgrade10' => 0,
    'count_ArrowUpgrade70' => 1,
    'count_TwentyRupees' => 24,
    'boss_location_in_base' => false,
]);

$logger = new Logger('randomizer');
$logger->pushHandler((new ErrorLogHandler(null, Logger::INFO))->setFormatter(new LineFormatter('%message%')));

$rand = new Randomizer($config_v7, $logger);
$rand->makeSeed();
$rand->save();

$logger->debug("Stats:");
$logger->debug("Run Time: " . round(microtime(true) - $start, 2) . "s");
$logger->debug("Memory Usage: " . memory_get_usage(true) / 1024 / 1204 . "MB");
