<?php

use ALttP\Randomizer;
use ALttP\Item;

/**
 * These test may have to be updated on any Logic change that adjusts the pooling of the RNG
 */
class RandomizerTest extends TestCase {
	public function setUp() {
		parent::setUp();
		$this->randomizer = new Randomizer('test_rules');
	}

	public function tearDown() {
		parent::tearDown();
		unset($this->randomizer);
	}

	public function testGetSeedIsNullBeforeRandomization() {
		$this->assertNull($this->randomizer->getSeed());
	}

	public function testGetSeedIsNotNullAfterRandomization() {
		$this->randomizer->makeSeed();

		$this->assertNotNull($this->randomizer->getSeed());
	}

	/**
	 * @group swords
	 */
	public function testSwordsNotRandomizedByConfig() {
		Config::set('alttp.test_rules.region.swordShuffle', false);

		$this->randomizer->makeSeed(1337);

		$this->assertEquals([
			Item::get('L2Sword'),
			Item::get('L3Sword'),
			Item::get('L4Sword'),
		], [
			$this->randomizer->getWorld()->getLocation("Altar")->getItem(),
			$this->randomizer->getWorld()->getLocation("Blacksmiths")->getItem(),
			$this->randomizer->getWorld()->getLocation("Pyramid - Sword")->getItem(),
		]);
	}

	/**
	 * @group crystals
	 */
	public function testCrystalsNotRandomizedByConfigCrossWorld() {
		Config::set('alttp.test_rules.prize.crossWorld', true);
		Config::set('alttp.test_rules.prize.shuffleCrystals', false);

		$this->randomizer->makeSeed(1337);
		$this->assertEquals([
			Item::get('Crystal1'),
			Item::get('Crystal2'),
			Item::get('Crystal3'),
			Item::get('Crystal4'),
			Item::get('Crystal5'),
			Item::get('Crystal6'),
			Item::get('Crystal7'),
		], [
			$this->randomizer->getWorld()->getLocation("Palace of Darkness Crystal")->getItem(),
			$this->randomizer->getWorld()->getLocation("Swamp Palace Crystal")->getItem(),
			$this->randomizer->getWorld()->getLocation("Skull Woods Crystal")->getItem(),
			$this->randomizer->getWorld()->getLocation("Thieves Town Crystal")->getItem(),
			$this->randomizer->getWorld()->getLocation("Ice Palace Crystal")->getItem(),
			$this->randomizer->getWorld()->getLocation("Misery Mire Crystal")->getItem(),
			$this->randomizer->getWorld()->getLocation("Turtle Rock Crystal")->getItem(),
		]);
	}

	/**
	 * @group crystals
	 */
	public function testCrystalsNotRandomizedByConfigNoCrossWorld() {
		Config::set('alttp.test_rules.prize.crossWorld', false);
		Config::set('alttp.test_rules.prize.shuffleCrystals', false);

		$this->randomizer->makeSeed(1337);

		$this->assertEquals([
			Item::get('Crystal1'),
			Item::get('Crystal2'),
			Item::get('Crystal3'),
			Item::get('Crystal4'),
			Item::get('Crystal5'),
			Item::get('Crystal6'),
			Item::get('Crystal7'),
		], [
			$this->randomizer->getWorld()->getLocation("Palace of Darkness Crystal")->getItem(),
			$this->randomizer->getWorld()->getLocation("Swamp Palace Crystal")->getItem(),
			$this->randomizer->getWorld()->getLocation("Skull Woods Crystal")->getItem(),
			$this->randomizer->getWorld()->getLocation("Thieves Town Crystal")->getItem(),
			$this->randomizer->getWorld()->getLocation("Ice Palace Crystal")->getItem(),
			$this->randomizer->getWorld()->getLocation("Misery Mire Crystal")->getItem(),
			$this->randomizer->getWorld()->getLocation("Turtle Rock Crystal")->getItem(),
		]);
	}


	/**
	 * @group pendants
	 */
	public function testPendantsNotRandomizedByConfigNoCrossWorld() {
		Config::set('alttp.test_rules.prize.crossWorld', false);
		Config::set('alttp.test_rules.prize.shufflePendants', false);

		$this->randomizer->makeSeed(1337);

		$this->assertEquals([
			Item::get('PendantOfCourage'),
			Item::get('PendantOfPower'),
			Item::get('PendantOfWisdom'),
		], [
			$this->randomizer->getWorld()->getLocation("Eastern Palace Pendant")->getItem(),
			$this->randomizer->getWorld()->getLocation("Desert Palace Pendant")->getItem(),
			$this->randomizer->getWorld()->getLocation("Tower of Hera Pendant")->getItem(),
		]);
	}

	/**
	 * @group pendants
	 */
	public function testPendantsNotRandomizedByConfigCrossWorld() {
		Config::set('alttp.test_rules.prize.crossWorld', true);
		Config::set('alttp.test_rules.prize.shufflePendants', false);

		$this->randomizer->makeSeed(1337);

		$this->assertEquals([
			Item::get('PendantOfCourage'),
			Item::get('PendantOfPower'),
			Item::get('PendantOfWisdom'),
		], [
			$this->randomizer->getWorld()->getLocation("Eastern Palace Pendant")->getItem(),
			$this->randomizer->getWorld()->getLocation("Desert Palace Pendant")->getItem(),
			$this->randomizer->getWorld()->getLocation("Tower of Hera Pendant")->getItem(),
		]);
	}

	/**
	 * Adjust this test and increment Logic on Randomizer if this fails.
	 *
	 * @group logic
	 */
	public function testLogicHasntChangedNoMajorGlitches() {
		$this->randomizer->makeSeed(1337);
		$loc_item_array = $this->randomizer->getWorld()->getLocations()->map(function($loc){
			return $loc->getItem()->getName();
		});

		$this->assertEquals([
			"Altar" => "PieceOfHeart",
			"Uncle" => "ProgressiveSword",
			"[cave-034] Hyrule Castle secret entrance" => "ThreeBombs",
			"[cave-018] Graveyard - top right grave" => "TwentyRupees",
			"[cave-047] Dam" => "PieceOfHeart",
			"[cave-040] Link's House" => "BombUpgrade5",
			"[cave-031] Tavern" => "FiveRupees",
			"[cave-026] chicken house" => "TenArrows",
			"[cave-044] Aginah's cave" => "HeartContainer",
			"[cave-035] Sahasrahla's Hut [left chest]" => "Ether",
			"[cave-035] Sahasrahla's Hut [center chest]" => "ThreeHundredRupees",
			"[cave-035] Sahasrahla's Hut [right chest]" => "BossHeartContainer",
			"[cave-021] Kakariko well [top chest]" => "ArrowUpgrade5",
			"[cave-021] Kakariko well [left chest row of 3]" => "TwentyRupees",
			"[cave-021] Kakariko well [center chest row of 3]" => "FiftyRupees",
			"[cave-021] Kakariko well [right chest row of 3]" => "TwentyRupees",
			"[cave-021] Kakariko well [bottom chest]" => "Hookshot",
			"[cave-022-B1] Thief's hut [top chest]" => "BossHeartContainer",
			"[cave-022-B1] Thief's hut [top left chest]" => "Bow",
			"[cave-022-B1] Thief's hut [top right chest]" => "TwentyRupees",
			"[cave-022-B1] Thief's hut [bottom left chest]" => "TenArrows",
			"[cave-022-B1] Thief's hut [bottom right chest]" => "PieceOfHeart",
			"[cave-016] cave under rocks west of Santuary" => "TwentyRupees",
			"[cave-050] cave southwest of Lake Hylia [bottom left chest]" => "BossHeartContainer",
			"[cave-050] cave southwest of Lake Hylia [top left chest]" => "TwentyRupees",
			"[cave-050] cave southwest of Lake Hylia [top right chest]" => "BossHeartContainer",
			"[cave-050] cave southwest of Lake Hylia [bottom right chest]" => "ProgressiveArmor",
			"[cave-051] Ice Cave" => "PieceOfHeart",
			"Bottle Vendor" => "BossHeartContainer",
			"Sahasrahla" => "BossHeartContainer",
			"Magic Bat" => "RedBoomerang",
			"Sick Kid" => "FiveRupees",
			"Hobo" => "BossHeartContainer",
			"Bombos Tablet" => "PieceOfHeart",
			"King Zora" => "BossHeartContainer",
			"Piece of Heart (Thieves' Forest Hideout)" => "BombUpgrade5",
			"Piece of Heart (Lumberjack Tree)" => "Mushroom",
			"Piece of Heart (south of Haunted Grove)" => "PieceOfHeart",
			"Piece of Heart (Graveyard)" => "Powder",
			"Piece of Heart (Desert - northeast corner)" => "TwentyRupees",
			"[cave-050] cave southwest of Lake Hylia - generous guy" => "MoonPearl",
			"Library" => "ProgressiveShield",
			"Mushroom" => "FiftyRupees",
			"Witch" => "ArrowUpgrade5",
			"Piece of Heart (Maze Race)" => "PieceOfHeart",
			"Piece of Heart (Desert - west side)" => "PieceOfHeart",
			"Piece of Heart (Lake Hylia)" => "TwentyRupees",
			"Piece of Heart (Dam)" => "TwentyRupees",
			"Piece of Heart (Zora's River)" => "CaneOfSomaria",
			"Haunted Grove item" => "CaneOfByrna",
			"Waterfall Fairy - Left" => "TwentyRupees",
			"Waterfall Fairy - Right" => "ProgressiveGlove",
			"[dungeon-C-1F] Sanctuary" => "BombUpgrade5",
			"[dungeon-C-B1] Escape - final basement room [left chest]" => "Cape",
			"[dungeon-C-B1] Escape - final basement room [middle chest]" => "PieceOfHeart",
			"[dungeon-C-B1] Escape - final basement room [right chest]" => "ThreeBombs",
			"[dungeon-C-B1] Escape - first B1 room" => "KeyH2",
			"[dungeon-C-B1] Hyrule Castle - boomerang room" => "FireRod",
			"[dungeon-C-B1] Hyrule Castle - map room" => "OcarinaInactive",
			"[dungeon-C-B3] Hyrule Castle - next to Zelda" => "MapH2",
			"[dungeon-L1-1F] Eastern Palace - compass room" => "TwentyRupees",
			"[dungeon-L1-1F] Eastern Palace - big chest" => "CompassP1",
			"[dungeon-L1-1F] Eastern Palace - big ball room" => "Lamp",
			"[dungeon-L1-1F] Eastern Palace - Big key" => "ThreeBombs",
			"[dungeon-L1-1F] Eastern Palace - map room" => "BigKeyP1",
			"Heart Container - Armos Knights" => "MapP1",
			"Eastern Palace Pendant" => "Crystal2",
			"[dungeon-L2-B1] Desert Palace - big chest" => "CompassP2",
			"[dungeon-L2-B1] Desert Palace - Map room" => "TwentyRupees",
			"[dungeon-L2-B1] Desert Palace - Small key room" => "KeyP2",
			"[dungeon-L2-B1] Desert Palace - Big key room" => "BigKeyP2",
			"[dungeon-L2-B1] Desert Palace - compass room" => "FiftyRupees",
			"Heart Container - Lanmolas" => "MapP2",
			"Desert Palace Pendant" => "Crystal6",
			"Old Mountain Man" => "Arrow",
			"Piece of Heart (Spectacle Rock Cave)" => "OneHundredRupees",
			"Ether Tablet" => "TwentyRupees",
			"Piece of Heart (Spectacle Rock)" => "TwentyRupees",
			"[cave-012-1F] Death Mountain - wall of caves - left cave" => "FiveRupees",
			"[cave-013] Mimic cave (from Turtle Rock)" => "ThreeBombs",
			"[cave-009-1F] Death Mountain - wall of caves - right cave [top left chest]" => "TenArrows",
			"[cave-009-1F] Death Mountain - wall of caves - right cave [top left middle chest]" => "BossHeartContainer",
			"[cave-009-1F] Death Mountain - wall of caves - right cave [top right middle chest]" => "PieceOfHeart",
			"[cave-009-1F] Death Mountain - wall of caves - right cave [top right chest]" => "HalfMagic",
			"[cave-009-1F] Death Mountain - wall of caves - right cave [bottom chest]" => "Hammer",
			"[cave-009-B1] Death Mountain - wall of caves - right cave [left chest]" => "ProgressiveSword",
			"[cave-009-B1] Death Mountain - wall of caves - right cave [right chest]" => "PieceOfHeart",
			"Piece of Heart (Death Mountain - floating island)" => "ProgressiveShield",
			"[dungeon-L3-1F] Tower of Hera - first floor" => "BigKeyP3",
			"[dungeon-L3-1F] Tower of Hera - freestanding key" => "PegasusBoots",
			"[dungeon-L3-2F] Tower of Hera - Entrance" => "KeyP3",
			"[dungeon-L3-4F] Tower of Hera - 4F [small chest]" => "MapP3",
			"[dungeon-L3-4F] Tower of Hera - big chest" => "CompassP3",
			"Heart Container - Moldorm" => "TwentyRupees",
			"Tower of Hera Pendant" => "PendantOfCourage",
			"[dungeon-A1-2F] Hyrule Castle Tower - 2 knife guys room" => "Key",
			"[dungeon-A1-3F] Hyrule Castle Tower - maze room" => "Key",
			"Agahnim" => "DefeatAgahnim",
			"[cave-057-1F] Dark World Death Mountain - cave from top to bottom [top chest]" => "TwentyRupees",
			"[cave-057-1F] Dark World Death Mountain - cave from top to bottom [bottom chest]" => "PieceOfHeart",
			"[cave-056] Dark World Death Mountain - cave under boulder [top right chest]" => "BossHeartContainer",
			"[cave-056] Dark World Death Mountain - cave under boulder [top left chest]" => "OneRupee",
			"[cave-056] Dark World Death Mountain - cave under boulder [bottom left chest]" => "Bottle",
			"[cave-056] Dark World Death Mountain - cave under boulder [bottom right chest]" => "ProgressiveShield",
			"[cave-055] Spike cave" => "BugCatchingNet",
			"Catfish" => "ProgressiveGlove",
			"Piece of Heart (Pyramid)" => "PieceOfHeart",
			"Pyramid - Sword" => "L1Sword",
			"Pyramid - Bow" => "BowAndArrows",
			"Ganon" => "DefeatGanon",
			"Pyramid Fairy - Left" => "ArrowUpgrade5",
			"Pyramid Fairy - Right" => "PieceOfHeart",
			"[cave-063] doorless hut" => "TwentyRupees",
			"[cave-062] C-shaped house" => "ThreeHundredRupees",
			"Piece of Heart (Treasure Chest Game)" => "ThreeHundredRupees",
			"Piece of Heart (Dark World blacksmith pegs)" => "ProgressiveArmor",
			"Piece of Heart (Dark World - bumper cave)" => "FiveRupees",
			"Blacksmiths" => "BottleWithGreenPotion",
			"Purple Chest" => "BookOfMudora",
			"[cave-073] cave northeast of swamp palace [top chest]" => "BottleWithGoldBee",
			"[cave-073] cave northeast of swamp palace [top middle chest]" => "ArrowUpgrade5",
			"[cave-073] cave northeast of swamp palace [bottom middle chest]" => "PieceOfHeart",
			"[cave-073] cave northeast of swamp palace [bottom chest]" => "TwentyRupees",
			"Flute Boy" => "ProgressiveSword",
			"[cave-073] cave northeast of swamp palace - generous guy" => "TwentyRupees",
			"Piece of Heart (Digging Game)" => "ThreeBombs",
			"[cave-071] Misery Mire west area [left chest]" => "BombUpgrade5",
			"[cave-071] Misery Mire west area [right chest]" => "PieceOfHeart",
			"[dungeon-D1-B1] Dark Palace - shooter room" => "ThreeBombs",
			"[dungeon-D1-1F] Dark Palace - big key room" => "CompassD1",
			"[dungeon-D1-1F] Dark Palace - jump room [right chest]" => "KeyD1",
			"[dungeon-D1-1F] Dark Palace - jump room [left chest]" => "KeyD1",
			"[dungeon-D1-B1] Dark Palace - turtle stalfos room" => "KeyD1",
			"[dungeon-D1-1F] Dark Palace - statue push room" => "KeyD1",
			"[dungeon-D1-1F] Dark Palace - big chest" => "PieceOfHeart",
			"[dungeon-D1-1F] Dark Palace - compass room" => "BottleWithGoldBee",
			"[dungeon-D1-1F] Dark Palace - spike statue room" => "FiftyRupees",
			"[dungeon-D1-B1] Dark Palace - room leading to Helmasaur [left chest]" => "KeyD1",
			"[dungeon-D1-B1] Dark Palace - room leading to Helmasaur [right chest]" => "KeyD1",
			"[dungeon-D1-1F] Dark Palace - maze room [top chest]" => "BigKeyD1",
			"[dungeon-D1-1F] Dark Palace - maze room [bottom chest]" => "MapD1",
			"Heart Container - Helmasaur King" => "TenArrows",
			"Palace of Darkness Crystal" => "Crystal1",
			"[dungeon-D2-1F] Swamp Palace - first room" => "KeyD2",
			"[dungeon-D2-B1] Swamp Palace - big chest" => "MapD2",
			"[dungeon-D2-B1] Swamp Palace - big key room" => "BigKeyD2",
			"[dungeon-D2-B1] Swamp Palace - map room" => "CompassD2",
			"[dungeon-D2-B1] Swamp Palace - push 4 blocks room" => "FiftyRupees",
			"[dungeon-D2-B1] Swamp Palace - south of hookshot room" => "ProgressiveSword",
			"[dungeon-D2-B2] Swamp Palace - flooded room [left chest]" => "ThreeBombs",
			"[dungeon-D2-B2] Swamp Palace - flooded room [right chest]" => "BombUpgrade5",
			"[dungeon-D2-B2] Swamp Palace - hidden waterfall door room" => "BombUpgrade10",
			"Heart Container - Arrghus" => "SilverArrowUpgrade",
			"Swamp Palace Crystal" => "Crystal7",
			"[dungeon-D3-B1] Skull Woods - big chest" => "CompassD3",
			"[dungeon-D3-B1] Skull Woods - Big Key room" => "KeyD3",
			"[dungeon-D3-B1] Skull Woods - Compass room" => "Bombos",
			"[dungeon-D3-B1] Skull Woods - east of Fire Rod room" => "MapD3",
			"[dungeon-D3-B1] Skull Woods - Entrance to part 2" => "KeyD3",
			"[dungeon-D3-B1] Skull Woods - Gibdo/Stalfos room" => "Flippers",
			"[dungeon-D3-B1] Skull Woods - south of Fire Rod room" => "KeyD3",
			"Heart Container - Mothula" => "BigKeyD3",
			"Skull Woods Crystal" => "PendantOfWisdom",
			"[dungeon-D4-1F] Thieves' Town - Room above boss" => "CompassD4",
			"[dungeon-D4-B1] Thieves' Town - Bottom left of huge room [bottom right chest]" => "KeyD4",
			"[dungeon-D4-B1] Thieves' Town - Bottom left of huge room [top left chest]" => "BigKeyD4",
			"[dungeon-D4-B1] Thieves' Town - Bottom right of huge room" => "OneRupee",
			"[dungeon-D4-B1] Thieves' Town - Top left of huge room" => "MapD4",
			"[dungeon-D4-B2] Thieves' Town - big chest" => "PieceOfHeart",
			"[dungeon-D4-B2] Thieves' Town - next to Blind" => "PieceOfHeart",
			"Heart Container - Blind" => "TwentyRupees",
			"Thieves Town Crystal" => "Crystal4",
			"[dungeon-D5-B1] Ice Palace - Big Key room" => "KeyD5",
			"[dungeon-D5-B1] Ice Palace - compass room" => "TwentyRupees",
			"[dungeon-D5-B2] Ice Palace - map room" => "CompassD5",
			"[dungeon-D5-B3] Ice Palace - spike room" => "BigKeyD5",
			"[dungeon-D5-B4] Ice Palace - above Blue Mail room" => "PieceOfHeart",
			"[dungeon-D5-B5] Ice Palace - b5 up staircase" => "KeyD5",
			"[dungeon-D5-B5] Ice Palace - big chest" => "MapD5",
			"Heart Container - Kholdstare" => "MagicMirror",
			"Ice Palace Crystal" => "Crystal5",
			"[dungeon-D6-B1] Misery Mire - big chest" => "KeyD6",
			"[dungeon-D6-B1] Misery Mire - big hub room" => "KeyD6",
			"[dungeon-D6-B1] Misery Mire - big key" => "TwentyRupees",
			"[dungeon-D6-B1] Misery Mire - compass" => "CompassD6",
			"[dungeon-D6-B1] Misery Mire - end of bridge" => "ThreeHundredRupees",
			"[dungeon-D6-B1] Misery Mire - map room" => "BigKeyD6",
			"[dungeon-D6-B1] Misery Mire - spike room" => "KeyD6",
			"Heart Container - Vitreous" => "MapD6",
			"Misery Mire Crystal" => "Crystal3",
			"[dungeon-D7-1F] Turtle Rock - Chain chomp room" => "PieceOfHeart",
			"[dungeon-D7-1F] Turtle Rock - compass room" => "KeyD7",
			"[dungeon-D7-1F] Turtle Rock - Map room [left chest]" => "BigKeyD7",
			"[dungeon-D7-1F] Turtle Rock - Map room [right chest]" => "KeyD7",
			"[dungeon-D7-B1] Turtle Rock - big chest" => "CompassD7",
			"[dungeon-D7-B1] Turtle Rock - big key room" => "ThreeBombs",
			"[dungeon-D7-B1] Turtle Rock - Roller switch room" => "KeyD7",
			"[dungeon-D7-B2] Turtle Rock - Eye bridge room [bottom left chest]" => "MapD7",
			"[dungeon-D7-B2] Turtle Rock - Eye bridge room [bottom right chest]" => "TwentyRupees",
			"[dungeon-D7-B2] Turtle Rock - Eye bridge room [top left chest]" => "KeyD7",
			"[dungeon-D7-B2] Turtle Rock - Eye bridge room [top right chest]" => "ThreeBombs",
			"Heart Container - Trinexx" => "Shovel",
			"Turtle Rock Crystal" => "PendantOfPower",
			"[dungeon-A2-1F] Ganon's Tower - down left staircase from entrance" => "KeyA2",
			"[dungeon-A2-1F] Ganon's Tower - north of gap room [top left chest]" => "Boomerang",
			"[dungeon-A2-1F] Ganon's Tower - north of gap room [top right chest]" => "KeyA2",
			"[dungeon-A2-1F] Ganon's Tower - north of gap room [bottom left chest]" => "TwentyRupees",
			"[dungeon-A2-1F] Ganon's Tower - north of gap room [bottom right chest]" => "Quake",
			"[dungeon-A2-1F] Ganon's Tower - west of teleport room [top left chest]" => "ThreeBombs",
			"[dungeon-A2-1F] Ganon's Tower - west of teleport room [top right chest]" => "BigKeyA2",
			"[dungeon-A2-1F] Ganon's Tower - west of teleport room [bottom left chest]" => "TwentyRupees",
			"[dungeon-A2-1F] Ganon's Tower - west of teleport room [bottom right chest]" => "IceRod",
			"[dungeon-A2-1F] Ganon's Tower - north of teleport room" => "PieceOfHeart",
			"[dungeon-A2-1F] Ganon's Tower - map room" => "TwentyRupees",
			"[dungeon-A2-1F] Ganon's Tower - big chest" => "TwentyRupees",
			"[dungeon-A2-1F] Ganon's Tower - down right staircase from entrance [left chest]" => "KeyA2",
			"[dungeon-A2-1F] Ganon's Tower - down right staircase from entrance [right chest]" => "PieceOfHeart",
			"[dungeon-A2-1F] Ganon's Tower - above Armos" => "FiftyRupees",
			"[dungeon-A2-1F] Ganon's Tower - east of down right staircase from entrance" => "BombUpgrade5",
			"[dungeon-A2-1F] Ganon's Tower - compass room [top left chest]" => "PieceOfHeart",
			"[dungeon-A2-1F] Ganon's Tower - compass room [top right chest]" => "ThreeHundredRupees",
			"[dungeon-A2-1F] Ganon's Tower - compass room [bottom left chest]" => "ArrowUpgrade5",
			"[dungeon-A2-1F] Ganon's Tower - compass room [bottom right chest]" => "ArrowUpgrade10",
			"[dungeon-A2-B1] Ganon's Tower - north of Armos room [bottom chest]" => "TenArrows",
			"[dungeon-A2-B1] Ganon's Tower - north of Armos room [left chest]" => "TwentyRupees",
			"[dungeon-A2-B1] Ganon's Tower - north of Armos room [right chest]" => "KeyA2",
			"[dungeon-A2-6F] Ganon's Tower - north of falling floor four torches [top left chest]" => "MapA2",
			"[dungeon-A2-6F] Ganon's Tower - north of falling floor four torches [top right chest]" => "FiftyRupees",
			"[dungeon-A2-6F] Ganon's Tower - before Moldorm" => "ArrowUpgrade5",
			"[dungeon-A2-6F] Ganon's Tower - Moldorm room" => "CompassA2",
			"Agahnim 2" => "DefeatAgahnim2",
			"Turtle Rock Medallion" => "Bombos",
			"Misery Mire Medallion" => "Bombos",
			"Waterfall Bottle" => "BottleWithGreenPotion",
			"Pyramid Bottle" => "BottleWithBluePotion",
		], $loc_item_array);
	}

	/**
	 * Adjust this test and increment Logic on Randomizer if this fails.
	 *
	 * @group logic
	 */
	public function testLogicHasntChangedOverworldGlitches() {
		$this->randomizer = new Randomizer('test_rules', 'OverworldGlitches');
		$this->randomizer->makeSeed(1337);
		$loc_item_array = $this->randomizer->getWorld()->getLocations()->map(function($loc){
			return $loc->getItem()->getName();
		});

		$this->assertEquals([
			"Altar" => "PieceOfHeart",
			"Uncle" => "ProgressiveSword",
			"[cave-034] Hyrule Castle secret entrance" => "ThreeBombs",
			"[cave-018] Graveyard - top right grave" => "TwentyRupees",
			"[cave-047] Dam" => "TwentyRupees",
			"[cave-040] Link's House" => "BombUpgrade5",
			"[cave-031] Tavern" => "FiveRupees",
			"[cave-026] chicken house" => "TenArrows",
			"[cave-044] Aginah's cave" => "HeartContainer",
			"[cave-035] Sahasrahla's Hut [left chest]" => "Ether",
			"[cave-035] Sahasrahla's Hut [center chest]" => "ThreeHundredRupees",
			"[cave-035] Sahasrahla's Hut [right chest]" => "BossHeartContainer",
			"[cave-021] Kakariko well [top chest]" => "ArrowUpgrade5",
			"[cave-021] Kakariko well [left chest row of 3]" => "TwentyRupees",
			"[cave-021] Kakariko well [center chest row of 3]" => "FiftyRupees",
			"[cave-021] Kakariko well [right chest row of 3]" => "TwentyRupees",
			"[cave-021] Kakariko well [bottom chest]" => "Hookshot",
			"[cave-022-B1] Thief's hut [top chest]" => "BossHeartContainer",
			"[cave-022-B1] Thief's hut [top left chest]" => "Bow",
			"[cave-022-B1] Thief's hut [top right chest]" => "TwentyRupees",
			"[cave-022-B1] Thief's hut [bottom left chest]" => "TenArrows",
			"[cave-022-B1] Thief's hut [bottom right chest]" => "PieceOfHeart",
			"[cave-016] cave under rocks west of Santuary" => "TwentyRupees",
			"[cave-050] cave southwest of Lake Hylia [bottom left chest]" => "BossHeartContainer",
			"[cave-050] cave southwest of Lake Hylia [top left chest]" => "TwentyRupees",
			"[cave-050] cave southwest of Lake Hylia [top right chest]" => "BossHeartContainer",
			"[cave-050] cave southwest of Lake Hylia [bottom right chest]" => "ProgressiveArmor",
			"[cave-051] Ice Cave" => "PieceOfHeart",
			"Bottle Vendor" => "BossHeartContainer",
			"Sahasrahla" => "BossHeartContainer",
			"Magic Bat" => "RedBoomerang",
			"Sick Kid" => "FiveRupees",
			"Hobo" => "BossHeartContainer",
			"Bombos Tablet" => "PieceOfHeart",
			"King Zora" => "BossHeartContainer",
			"Piece of Heart (Thieves' Forest Hideout)" => "BombUpgrade5",
			"Piece of Heart (Lumberjack Tree)" => "Mushroom",
			"Piece of Heart (south of Haunted Grove)" => "PieceOfHeart",
			"Piece of Heart (Graveyard)" => "ThreeBombs",
			"Piece of Heart (Desert - northeast corner)" => "TwentyRupees",
			"[cave-050] cave southwest of Lake Hylia - generous guy" => "OcarinaInactive",
			"Library" => "ProgressiveShield",
			"Mushroom" => "FiftyRupees",
			"Witch" => "ArrowUpgrade5",
			"Piece of Heart (Maze Race)" => "PieceOfHeart",
			"Piece of Heart (Desert - west side)" => "PieceOfHeart",
			"Piece of Heart (Lake Hylia)" => "TwentyRupees",
			"Piece of Heart (Dam)" => "PieceOfHeart",
			"Piece of Heart (Zora's River)" => "Cape",
			"Haunted Grove item" => "CaneOfByrna",
			"Waterfall Fairy - Left" => "PieceOfHeart",
			"Waterfall Fairy - Right" => "ProgressiveGlove",
			"[dungeon-C-1F] Sanctuary" => "BombUpgrade5",
			"[dungeon-C-B1] Escape - final basement room [left chest]" => "Quake",
			"[dungeon-C-B1] Escape - final basement room [middle chest]" => "PieceOfHeart",
			"[dungeon-C-B1] Escape - final basement room [right chest]" => "ThreeBombs",
			"[dungeon-C-B1] Escape - first B1 room" => "KeyH2",
			"[dungeon-C-B1] Hyrule Castle - boomerang room" => "FireRod",
			"[dungeon-C-B1] Hyrule Castle - map room" => "IceRod",
			"[dungeon-C-B3] Hyrule Castle - next to Zelda" => "MapH2",
			"[dungeon-L1-1F] Eastern Palace - compass room" => "TwentyRupees",
			"[dungeon-L1-1F] Eastern Palace - big chest" => "CompassP1",
			"[dungeon-L1-1F] Eastern Palace - big ball room" => "MoonPearl",
			"[dungeon-L1-1F] Eastern Palace - Big key" => "ThreeBombs",
			"[dungeon-L1-1F] Eastern Palace - map room" => "BigKeyP1",
			"Heart Container - Armos Knights" => "MapP1",
			"Eastern Palace Pendant" => "Crystal2",
			"[dungeon-L2-B1] Desert Palace - big chest" => "CompassP2",
			"[dungeon-L2-B1] Desert Palace - Map room" => "TwentyRupees",
			"[dungeon-L2-B1] Desert Palace - Small key room" => "KeyP2",
			"[dungeon-L2-B1] Desert Palace - Big key room" => "BigKeyP2",
			"[dungeon-L2-B1] Desert Palace - compass room" => "FiftyRupees",
			"Heart Container - Lanmolas" => "MapP2",
			"Desert Palace Pendant" => "Crystal6",
			"Old Mountain Man" => "Arrow",
			"Piece of Heart (Spectacle Rock Cave)" => "OneHundredRupees",
			"Ether Tablet" => "TwentyRupees",
			"Piece of Heart (Spectacle Rock)" => "TwentyRupees",
			"[cave-012-1F] Death Mountain - wall of caves - left cave" => "FiveRupees",
			"[cave-013] Mimic cave (from Turtle Rock)" => "ThreeBombs",
			"[cave-009-1F] Death Mountain - wall of caves - right cave [top left chest]" => "TenArrows",
			"[cave-009-1F] Death Mountain - wall of caves - right cave [top left middle chest]" => "BossHeartContainer",
			"[cave-009-1F] Death Mountain - wall of caves - right cave [top right middle chest]" => "PieceOfHeart",
			"[cave-009-1F] Death Mountain - wall of caves - right cave [top right chest]" => "HalfMagic",
			"[cave-009-1F] Death Mountain - wall of caves - right cave [bottom chest]" => "Hammer",
			"[cave-009-B1] Death Mountain - wall of caves - right cave [left chest]" => "ProgressiveSword",
			"[cave-009-B1] Death Mountain - wall of caves - right cave [right chest]" => "PieceOfHeart",
			"Piece of Heart (Death Mountain - floating island)" => "ProgressiveGlove",
			"[dungeon-L3-1F] Tower of Hera - first floor" => "BigKeyP3",
			"[dungeon-L3-1F] Tower of Hera - freestanding key" => "PegasusBoots",
			"[dungeon-L3-2F] Tower of Hera - Entrance" => "KeyP3",
			"[dungeon-L3-4F] Tower of Hera - 4F [small chest]" => "MapP3",
			"[dungeon-L3-4F] Tower of Hera - big chest" => "CompassP3",
			"Heart Container - Moldorm" => "TwentyRupees",
			"Tower of Hera Pendant" => "PendantOfCourage",
			"[dungeon-A1-2F] Hyrule Castle Tower - 2 knife guys room" => "Key",
			"[dungeon-A1-3F] Hyrule Castle Tower - maze room" => "Key",
			"Agahnim" => "DefeatAgahnim",
			"[cave-057-1F] Dark World Death Mountain - cave from top to bottom [top chest]" => "TwentyRupees",
			"[cave-057-1F] Dark World Death Mountain - cave from top to bottom [bottom chest]" => "BombUpgrade10",
			"[cave-056] Dark World Death Mountain - cave under boulder [top right chest]" => "BossHeartContainer",
			"[cave-056] Dark World Death Mountain - cave under boulder [top left chest]" => "OneRupee",
			"[cave-056] Dark World Death Mountain - cave under boulder [bottom left chest]" => "Bottle",
			"[cave-056] Dark World Death Mountain - cave under boulder [bottom right chest]" => "ProgressiveShield",
			"[cave-055] Spike cave" => "BugCatchingNet",
			"Catfish" => "ProgressiveShield",
			"Piece of Heart (Pyramid)" => "PieceOfHeart",
			"Pyramid - Sword" => "L1Sword",
			"Pyramid - Bow" => "BowAndArrows",
			"Ganon" => "DefeatGanon",
			"Pyramid Fairy - Left" => "ArrowUpgrade5",
			"Pyramid Fairy - Right" => "PieceOfHeart",
			"[cave-063] doorless hut" => "TwentyRupees",
			"[cave-062] C-shaped house" => "ThreeHundredRupees",
			"Piece of Heart (Treasure Chest Game)" => "ThreeHundredRupees",
			"Piece of Heart (Dark World blacksmith pegs)" => "ProgressiveArmor",
			"Piece of Heart (Dark World - bumper cave)" => "FiveRupees",
			"Blacksmiths" => "BottleWithGreenPotion",
			"Purple Chest" => "BookOfMudora",
			"[cave-073] cave northeast of swamp palace [top chest]" => "BottleWithGoldBee",
			"[cave-073] cave northeast of swamp palace [top middle chest]" => "ArrowUpgrade5",
			"[cave-073] cave northeast of swamp palace [bottom middle chest]" => "BombUpgrade5",
			"[cave-073] cave northeast of swamp palace [bottom chest]" => "TwentyRupees",
			"Flute Boy" => "ProgressiveSword",
			"[cave-073] cave northeast of swamp palace - generous guy" => "TwentyRupees",
			"Piece of Heart (Digging Game)" => "ThreeBombs",
			"[cave-071] Misery Mire west area [left chest]" => "BombUpgrade5",
			"[cave-071] Misery Mire west area [right chest]" => "PieceOfHeart",
			"[dungeon-D1-B1] Dark Palace - shooter room" => "ThreeBombs",
			"[dungeon-D1-1F] Dark Palace - big key room" => "CompassD1",
			"[dungeon-D1-1F] Dark Palace - jump room [right chest]" => "KeyD1",
			"[dungeon-D1-1F] Dark Palace - jump room [left chest]" => "KeyD1",
			"[dungeon-D1-B1] Dark Palace - turtle stalfos room" => "KeyD1",
			"[dungeon-D1-1F] Dark Palace - statue push room" => "KeyD1",
			"[dungeon-D1-1F] Dark Palace - big chest" => "PieceOfHeart",
			"[dungeon-D1-1F] Dark Palace - compass room" => "BottleWithGoldBee",
			"[dungeon-D1-1F] Dark Palace - spike statue room" => "FiftyRupees",
			"[dungeon-D1-B1] Dark Palace - room leading to Helmasaur [left chest]" => "KeyD1",
			"[dungeon-D1-B1] Dark Palace - room leading to Helmasaur [right chest]" => "KeyD1",
			"[dungeon-D1-1F] Dark Palace - maze room [top chest]" => "BigKeyD1",
			"[dungeon-D1-1F] Dark Palace - maze room [bottom chest]" => "MapD1",
			"Heart Container - Helmasaur King" => "TenArrows",
			"Palace of Darkness Crystal" => "Crystal1",
			"[dungeon-D2-1F] Swamp Palace - first room" => "KeyD2",
			"[dungeon-D2-B1] Swamp Palace - big chest" => "MapD2",
			"[dungeon-D2-B1] Swamp Palace - big key room" => "BigKeyD2",
			"[dungeon-D2-B1] Swamp Palace - map room" => "CompassD2",
			"[dungeon-D2-B1] Swamp Palace - push 4 blocks room" => "FiftyRupees",
			"[dungeon-D2-B1] Swamp Palace - south of hookshot room" => "ProgressiveSword",
			"[dungeon-D2-B2] Swamp Palace - flooded room [left chest]" => "ThreeBombs",
			"[dungeon-D2-B2] Swamp Palace - flooded room [right chest]" => "PieceOfHeart",
			"[dungeon-D2-B2] Swamp Palace - hidden waterfall door room" => "TwentyRupees",
			"Heart Container - Arrghus" => "SilverArrowUpgrade",
			"Swamp Palace Crystal" => "Crystal7",
			"[dungeon-D3-B1] Skull Woods - big chest" => "CompassD3",
			"[dungeon-D3-B1] Skull Woods - Big Key room" => "KeyD3",
			"[dungeon-D3-B1] Skull Woods - Compass room" => "Lamp",
			"[dungeon-D3-B1] Skull Woods - east of Fire Rod room" => "MapD3",
			"[dungeon-D3-B1] Skull Woods - Entrance to part 2" => "KeyD3",
			"[dungeon-D3-B1] Skull Woods - Gibdo/Stalfos room" => "ThreeBombs",
			"[dungeon-D3-B1] Skull Woods - south of Fire Rod room" => "KeyD3",
			"Heart Container - Mothula" => "BigKeyD3",
			"Skull Woods Crystal" => "PendantOfWisdom",
			"[dungeon-D4-1F] Thieves' Town - Room above boss" => "CompassD4",
			"[dungeon-D4-B1] Thieves' Town - Bottom left of huge room [bottom right chest]" => "KeyD4",
			"[dungeon-D4-B1] Thieves' Town - Bottom left of huge room [top left chest]" => "BigKeyD4",
			"[dungeon-D4-B1] Thieves' Town - Bottom right of huge room" => "OneRupee",
			"[dungeon-D4-B1] Thieves' Town - Top left of huge room" => "MapD4",
			"[dungeon-D4-B2] Thieves' Town - big chest" => "PieceOfHeart",
			"[dungeon-D4-B2] Thieves' Town - next to Blind" => "PieceOfHeart",
			"Heart Container - Blind" => "TwentyRupees",
			"Thieves Town Crystal" => "Crystal4",
			"[dungeon-D5-B1] Ice Palace - Big Key room" => "KeyD5",
			"[dungeon-D5-B1] Ice Palace - compass room" => "TwentyRupees",
			"[dungeon-D5-B2] Ice Palace - map room" => "CompassD5",
			"[dungeon-D5-B3] Ice Palace - spike room" => "BigKeyD5",
			"[dungeon-D5-B4] Ice Palace - above Blue Mail room" => "PieceOfHeart",
			"[dungeon-D5-B5] Ice Palace - b5 up staircase" => "KeyD5",
			"[dungeon-D5-B5] Ice Palace - big chest" => "MapD5",
			"Heart Container - Kholdstare" => "MagicMirror",
			"Ice Palace Crystal" => "Crystal5",
			"[dungeon-D6-B1] Misery Mire - big chest" => "KeyD6",
			"[dungeon-D6-B1] Misery Mire - big hub room" => "KeyD6",
			"[dungeon-D6-B1] Misery Mire - big key" => "TwentyRupees",
			"[dungeon-D6-B1] Misery Mire - compass" => "CompassD6",
			"[dungeon-D6-B1] Misery Mire - end of bridge" => "ThreeHundredRupees",
			"[dungeon-D6-B1] Misery Mire - map room" => "BigKeyD6",
			"[dungeon-D6-B1] Misery Mire - spike room" => "KeyD6",
			"Heart Container - Vitreous" => "MapD6",
			"Misery Mire Crystal" => "Crystal3",
			"[dungeon-D7-1F] Turtle Rock - Chain chomp room" => "PieceOfHeart",
			"[dungeon-D7-1F] Turtle Rock - compass room" => "KeyD7",
			"[dungeon-D7-1F] Turtle Rock - Map room [left chest]" => "BigKeyD7",
			"[dungeon-D7-1F] Turtle Rock - Map room [right chest]" => "Flippers",
			"[dungeon-D7-B1] Turtle Rock - big chest" => "KeyD7",
			"[dungeon-D7-B1] Turtle Rock - big key room" => "ThreeBombs",
			"[dungeon-D7-B1] Turtle Rock - Roller switch room" => "KeyD7",
			"[dungeon-D7-B2] Turtle Rock - Eye bridge room [bottom left chest]" => "MapD7",
			"[dungeon-D7-B2] Turtle Rock - Eye bridge room [bottom right chest]" => "CompassD7",
			"[dungeon-D7-B2] Turtle Rock - Eye bridge room [top left chest]" => "KeyD7",
			"[dungeon-D7-B2] Turtle Rock - Eye bridge room [top right chest]" => "Powder",
			"Heart Container - Trinexx" => "Shovel",
			"Turtle Rock Crystal" => "PendantOfPower",
			"[dungeon-A2-1F] Ganon's Tower - down left staircase from entrance" => "KeyA2",
			"[dungeon-A2-1F] Ganon's Tower - north of gap room [top left chest]" => "Boomerang",
			"[dungeon-A2-1F] Ganon's Tower - north of gap room [top right chest]" => "KeyA2",
			"[dungeon-A2-1F] Ganon's Tower - north of gap room [bottom left chest]" => "TwentyRupees",
			"[dungeon-A2-1F] Ganon's Tower - north of gap room [bottom right chest]" => "CaneOfSomaria",
			"[dungeon-A2-1F] Ganon's Tower - west of teleport room [top left chest]" => "PieceOfHeart",
			"[dungeon-A2-1F] Ganon's Tower - west of teleport room [top right chest]" => "BigKeyA2",
			"[dungeon-A2-1F] Ganon's Tower - west of teleport room [bottom left chest]" => "TwentyRupees",
			"[dungeon-A2-1F] Ganon's Tower - west of teleport room [bottom right chest]" => "Bombos",
			"[dungeon-A2-1F] Ganon's Tower - north of teleport room" => "TwentyRupees",
			"[dungeon-A2-1F] Ganon's Tower - map room" => "TwentyRupees",
			"[dungeon-A2-1F] Ganon's Tower - big chest" => "TwentyRupees",
			"[dungeon-A2-1F] Ganon's Tower - down right staircase from entrance [left chest]" => "KeyA2",
			"[dungeon-A2-1F] Ganon's Tower - down right staircase from entrance [right chest]" => "PieceOfHeart",
			"[dungeon-A2-1F] Ganon's Tower - above Armos" => "FiftyRupees",
			"[dungeon-A2-1F] Ganon's Tower - east of down right staircase from entrance" => "BombUpgrade5",
			"[dungeon-A2-1F] Ganon's Tower - compass room [top left chest]" => "PieceOfHeart",
			"[dungeon-A2-1F] Ganon's Tower - compass room [top right chest]" => "ThreeHundredRupees",
			"[dungeon-A2-1F] Ganon's Tower - compass room [bottom left chest]" => "ArrowUpgrade5",
			"[dungeon-A2-1F] Ganon's Tower - compass room [bottom right chest]" => "ArrowUpgrade10",
			"[dungeon-A2-B1] Ganon's Tower - north of Armos room [bottom chest]" => "TenArrows",
			"[dungeon-A2-B1] Ganon's Tower - north of Armos room [left chest]" => "TwentyRupees",
			"[dungeon-A2-B1] Ganon's Tower - north of Armos room [right chest]" => "KeyA2",
			"[dungeon-A2-6F] Ganon's Tower - north of falling floor four torches [top left chest]" => "MapA2",
			"[dungeon-A2-6F] Ganon's Tower - north of falling floor four torches [top right chest]" => "FiftyRupees",
			"[dungeon-A2-6F] Ganon's Tower - before Moldorm" => "ArrowUpgrade5",
			"[dungeon-A2-6F] Ganon's Tower - Moldorm room" => "CompassA2",
			"Agahnim 2" => "DefeatAgahnim2",
			"Turtle Rock Medallion" => "Bombos",
			"Misery Mire Medallion" => "Bombos",
			"Waterfall Bottle" => "BottleWithGreenPotion",
			"Pyramid Bottle" => "BottleWithBluePotion",
		], $loc_item_array);
	}

	/**
	 * Adjust this test and increment Logic on Randomizer if this fails.
	 *
	 * @group logic
	 */
	public function testLogicHasntChangedMajorGlitches() {
		$this->randomizer = new Randomizer('test_rules', 'MajorGlitches');
		$this->randomizer->makeSeed(1337);
		$loc_item_array = $this->randomizer->getWorld()->getLocations()->map(function($loc){
			return $loc->getItem()->getName();
		});

		$this->assertEquals([
			"Altar" => "ProgressiveShield",
			"Uncle" => "ProgressiveSword",
			"[cave-034] Hyrule Castle secret entrance" => "Powder",
			"[cave-018] Graveyard - top right grave" => "PieceOfHeart",
			"[cave-047] Dam" => "TwentyRupees",
			"[cave-040] Link's House" => "BugCatchingNet",
			"[cave-031] Tavern" => "BossHeartContainer",
			"[cave-026] chicken house" => "Hammer",
			"[cave-044] Aginah's cave" => "BottleWithGreenPotion",
			"[cave-035] Sahasrahla's Hut [left chest]" => "PieceOfHeart",
			"[cave-035] Sahasrahla's Hut [center chest]" => "Ether",
			"[cave-035] Sahasrahla's Hut [right chest]" => "TwentyRupees",
			"[cave-021] Kakariko well [top chest]" => "TwentyRupees",
			"[cave-021] Kakariko well [left chest row of 3]" => "ThreeBombs",
			"[cave-021] Kakariko well [center chest row of 3]" => "FiftyRupees",
			"[cave-021] Kakariko well [right chest row of 3]" => "FiftyRupees",
			"[cave-021] Kakariko well [bottom chest]" => "Bottle",
			"[cave-022-B1] Thief's hut [top chest]" => "PieceOfHeart",
			"[cave-022-B1] Thief's hut [top left chest]" => "ArrowUpgrade5",
			"[cave-022-B1] Thief's hut [top right chest]" => "PieceOfHeart",
			"[cave-022-B1] Thief's hut [bottom left chest]" => "ThreeHundredRupees",
			"[cave-022-B1] Thief's hut [bottom right chest]" => "TenArrows",
			"[cave-016] cave under rocks west of Santuary" => "CaneOfByrna",
			"[cave-050] cave southwest of Lake Hylia [bottom left chest]" => "Bombos",
			"[cave-050] cave southwest of Lake Hylia [top left chest]" => "PieceOfHeart",
			"[cave-050] cave southwest of Lake Hylia [top right chest]" => "TwentyRupees",
			"[cave-050] cave southwest of Lake Hylia [bottom right chest]" => "FiveRupees",
			"[cave-051] Ice Cave" => "TenArrows",
			"Bottle Vendor" => "BottleWithGoldBee",
			"Sahasrahla" => "FiveRupees",
			"Magic Bat" => "TwentyRupees",
			"Sick Kid" => "FiveRupees",
			"Hobo" => "BombUpgrade5",
			"Bombos Tablet" => "Flippers",
			"King Zora" => "Mushroom",
			"Piece of Heart (Thieves' Forest Hideout)" => "BossHeartContainer",
			"Piece of Heart (Lumberjack Tree)" => "TwentyRupees",
			"Piece of Heart (south of Haunted Grove)" => "ProgressiveSword",
			"Piece of Heart (Graveyard)" => "TwentyRupees",
			"Piece of Heart (Desert - northeast corner)" => "PieceOfHeart",
			"[cave-050] cave southwest of Lake Hylia - generous guy" => "Quake",
			"Library" => "ArrowUpgrade5",
			"Mushroom" => "ThreeBombs",
			"Witch" => "TwentyRupees",
			"Piece of Heart (Maze Race)" => "OcarinaInactive",
			"Piece of Heart (Desert - west side)" => "RedBoomerang",
			"Piece of Heart (Lake Hylia)" => "ArrowUpgrade5",
			"Piece of Heart (Dam)" => "PieceOfHeart",
			"Piece of Heart (Zora's River)" => "BottleWithGoldBee",
			"Haunted Grove item" => "CaneOfSomaria",
			"Waterfall Fairy - Left" => "BossHeartContainer",
			"Waterfall Fairy - Right" => "ThreeHundredRupees",
			"[dungeon-C-1F] Sanctuary" => "PegasusBoots",
			"[dungeon-C-B1] Escape - final basement room [left chest]" => "PieceOfHeart",
			"[dungeon-C-B1] Escape - final basement room [middle chest]" => "PieceOfHeart",
			"[dungeon-C-B1] Escape - final basement room [right chest]" => "TwentyRupees",
			"[dungeon-C-B1] Escape - first B1 room" => "ThreeHundredRupees",
			"[dungeon-C-B1] Hyrule Castle - boomerang room" => "KeyH2",
			"[dungeon-C-B1] Hyrule Castle - map room" => "PieceOfHeart",
			"[dungeon-C-B3] Hyrule Castle - next to Zelda" => "MapH2",
			"[dungeon-L1-1F] Eastern Palace - compass room" => "ArrowUpgrade5",
			"[dungeon-L1-1F] Eastern Palace - big chest" => "TenArrows",
			"[dungeon-L1-1F] Eastern Palace - big ball room" => "MapP1",
			"[dungeon-L1-1F] Eastern Palace - Big key" => "HalfMagic",
			"[dungeon-L1-1F] Eastern Palace - map room" => "BigKeyP1",
			"Heart Container - Armos Knights" => "CompassP1",
			"Eastern Palace Pendant" => "Crystal2",
			"[dungeon-L2-B1] Desert Palace - big chest" => "MapP2",
			"[dungeon-L2-B1] Desert Palace - Map room" => "ProgressiveArmor",
			"[dungeon-L2-B1] Desert Palace - Small key room" => "KeyP2",
			"[dungeon-L2-B1] Desert Palace - Big key room" => "BigKeyP2",
			"[dungeon-L2-B1] Desert Palace - compass room" => "BombUpgrade5",
			"Heart Container - Lanmolas" => "CompassP2",
			"Desert Palace Pendant" => "Crystal6",
			"Old Mountain Man" => "Arrow",
			"Piece of Heart (Spectacle Rock Cave)" => "ThreeBombs",
			"Ether Tablet" => "OneRupee",
			"Piece of Heart (Spectacle Rock)" => "BombUpgrade5",
			"[cave-012-1F] Death Mountain - wall of caves - left cave" => "FireRod",
			"[cave-013] Mimic cave (from Turtle Rock)" => "TwentyRupees",
			"[cave-009-1F] Death Mountain - wall of caves - right cave [top left chest]" => "PieceOfHeart",
			"[cave-009-1F] Death Mountain - wall of caves - right cave [top left middle chest]" => "ProgressiveShield",
			"[cave-009-1F] Death Mountain - wall of caves - right cave [top right middle chest]" => "TwentyRupees",
			"[cave-009-1F] Death Mountain - wall of caves - right cave [top right chest]" => "ThreeHundredRupees",
			"[cave-009-1F] Death Mountain - wall of caves - right cave [bottom chest]" => "ProgressiveGlove",
			"[cave-009-B1] Death Mountain - wall of caves - right cave [left chest]" => "BossHeartContainer",
			"[cave-009-B1] Death Mountain - wall of caves - right cave [right chest]" => "PieceOfHeart",
			"Piece of Heart (Death Mountain - floating island)" => "TwentyRupees",
			"[dungeon-L3-1F] Tower of Hera - first floor" => "BigKeyP3",
			"[dungeon-L3-1F] Tower of Hera - freestanding key" => "MapP3",
			"[dungeon-L3-2F] Tower of Hera - Entrance" => "CompassP3",
			"[dungeon-L3-4F] Tower of Hera - 4F [small chest]" => "KeyP3",
			"[dungeon-L3-4F] Tower of Hera - big chest" => "TwentyRupees",
			"Heart Container - Moldorm" => "BookOfMudora",
			"Tower of Hera Pendant" => "PendantOfCourage",
			"[dungeon-A1-2F] Hyrule Castle Tower - 2 knife guys room" => "Key",
			"[dungeon-A1-3F] Hyrule Castle Tower - maze room" => "Key",
			"Agahnim" => "DefeatAgahnim",
			"[cave-057-1F] Dark World Death Mountain - cave from top to bottom [top chest]" => "SilverArrowUpgrade",
			"[cave-057-1F] Dark World Death Mountain - cave from top to bottom [bottom chest]" => "FiftyRupees",
			"[cave-056] Dark World Death Mountain - cave under boulder [top right chest]" => "TwentyRupees",
			"[cave-056] Dark World Death Mountain - cave under boulder [top left chest]" => "ArrowUpgrade5",
			"[cave-056] Dark World Death Mountain - cave under boulder [bottom left chest]" => "TenArrows",
			"[cave-056] Dark World Death Mountain - cave under boulder [bottom right chest]" => "FiftyRupees",
			"[cave-055] Spike cave" => "BombUpgrade5",
			"Catfish" => "Shovel",
			"Piece of Heart (Pyramid)" => "TwentyRupees",
			"Pyramid - Sword" => "L1Sword",
			"Pyramid - Bow" => "BowAndArrows",
			"Ganon" => "DefeatGanon",
			"Pyramid Fairy - Left" => "FiftyRupees",
			"Pyramid Fairy - Right" => "PieceOfHeart",
			"[cave-063] doorless hut" => "ProgressiveShield",
			"[cave-062] C-shaped house" => "BombUpgrade10",
			"Piece of Heart (Treasure Chest Game)" => "TwentyRupees",
			"Piece of Heart (Dark World blacksmith pegs)" => "ThreeBombs",
			"Piece of Heart (Dark World - bumper cave)" => "IceRod",
			"Blacksmiths" => "PieceOfHeart",
			"Purple Chest" => "ThreeBombs",
			"[cave-073] cave northeast of swamp palace [top chest]" => "ArrowUpgrade10",
			"[cave-073] cave northeast of swamp palace [top middle chest]" => "ThreeHundredRupees",
			"[cave-073] cave northeast of swamp palace [bottom middle chest]" => "PieceOfHeart",
			"[cave-073] cave northeast of swamp palace [bottom chest]" => "TwentyRupees",
			"Flute Boy" => "PieceOfHeart",
			"[cave-073] cave northeast of swamp palace - generous guy" => "TwentyRupees",
			"Piece of Heart (Digging Game)" => "ArrowUpgrade5",
			"[cave-071] Misery Mire west area [left chest]" => "HeartContainer",
			"[cave-071] Misery Mire west area [right chest]" => "PieceOfHeart",
			"[dungeon-D1-B1] Dark Palace - shooter room" => "KeyD1",
			"[dungeon-D1-1F] Dark Palace - big key room" => "MagicMirror",
			"[dungeon-D1-1F] Dark Palace - jump room [right chest]" => "KeyD1",
			"[dungeon-D1-1F] Dark Palace - jump room [left chest]" => "KeyD1",
			"[dungeon-D1-B1] Dark Palace - turtle stalfos room" => "KeyD1",
			"[dungeon-D1-1F] Dark Palace - statue push room" => "KeyD1",
			"[dungeon-D1-1F] Dark Palace - big chest" => "TwentyRupees",
			"[dungeon-D1-1F] Dark Palace - compass room" => "TenArrows",
			"[dungeon-D1-1F] Dark Palace - spike statue room" => "TwentyRupees",
			"[dungeon-D1-B1] Dark Palace - room leading to Helmasaur [left chest]" => "KeyD1",
			"[dungeon-D1-B1] Dark Palace - room leading to Helmasaur [right chest]" => "CompassD1",
			"[dungeon-D1-1F] Dark Palace - maze room [top chest]" => "BigKeyD1",
			"[dungeon-D1-1F] Dark Palace - maze room [bottom chest]" => "MapD1",
			"Heart Container - Helmasaur King" => "BombUpgrade5",
			"Palace of Darkness Crystal" => "Crystal1",
			"[dungeon-D2-1F] Swamp Palace - first room" => "BossHeartContainer",
			"[dungeon-D2-B1] Swamp Palace - big chest" => "KeyD2",
			"[dungeon-D2-B1] Swamp Palace - big key room" => "BigKeyD2",
			"[dungeon-D2-B1] Swamp Palace - map room" => "MapD2",
			"[dungeon-D2-B1] Swamp Palace - push 4 blocks room" => "CompassD2",
			"[dungeon-D2-B1] Swamp Palace - south of hookshot room" => "FiveRupees",
			"[dungeon-D2-B2] Swamp Palace - flooded room [left chest]" => "TwentyRupees",
			"[dungeon-D2-B2] Swamp Palace - flooded room [right chest]" => "BossHeartContainer",
			"[dungeon-D2-B2] Swamp Palace - hidden waterfall door room" => "TwentyRupees",
			"Heart Container - Arrghus" => "ThreeBombs",
			"Swamp Palace Crystal" => "Crystal7",
			"[dungeon-D3-B1] Skull Woods - big chest" => "ThreeBombs",
			"[dungeon-D3-B1] Skull Woods - Big Key room" => "KeyD3",
			"[dungeon-D3-B1] Skull Woods - Compass room" => "CompassD3",
			"[dungeon-D3-B1] Skull Woods - east of Fire Rod room" => "MapD3",
			"[dungeon-D3-B1] Skull Woods - Entrance to part 2" => "KeyD3",
			"[dungeon-D3-B1] Skull Woods - Gibdo/Stalfos room" => "BossHeartContainer",
			"[dungeon-D3-B1] Skull Woods - south of Fire Rod room" => "KeyD3",
			"Heart Container - Mothula" => "BigKeyD3",
			"Skull Woods Crystal" => "PendantOfWisdom",
			"[dungeon-D4-1F] Thieves' Town - Room above boss" => "CompassD4",
			"[dungeon-D4-B1] Thieves' Town - Bottom left of huge room [bottom right chest]" => "KeyD4",
			"[dungeon-D4-B1] Thieves' Town - Bottom left of huge room [top left chest]" => "BigKeyD4",
			"[dungeon-D4-B1] Thieves' Town - Bottom right of huge room" => "TwentyRupees",
			"[dungeon-D4-B1] Thieves' Town - Top left of huge room" => "MapD4",
			"[dungeon-D4-B2] Thieves' Town - big chest" => "FiftyRupees",
			"[dungeon-D4-B2] Thieves' Town - next to Blind" => "PieceOfHeart",
			"Heart Container - Blind" => "Cape",
			"Thieves Town Crystal" => "Crystal4",
			"[dungeon-D5-B1] Ice Palace - Big Key room" => "KeyD5",
			"[dungeon-D5-B1] Ice Palace - compass room" => "CompassD5",
			"[dungeon-D5-B2] Ice Palace - map room" => "BombUpgrade5",
			"[dungeon-D5-B3] Ice Palace - spike room" => "BigKeyD5",
			"[dungeon-D5-B4] Ice Palace - above Blue Mail room" => "Hookshot",
			"[dungeon-D5-B5] Ice Palace - b5 up staircase" => "KeyD5",
			"[dungeon-D5-B5] Ice Palace - big chest" => "MapD5",
			"Heart Container - Kholdstare" => "Lamp",
			"Ice Palace Crystal" => "Crystal5",
			"[dungeon-D6-B1] Misery Mire - big chest" => "KeyD6",
			"[dungeon-D6-B1] Misery Mire - big hub room" => "KeyD6",
			"[dungeon-D6-B1] Misery Mire - big key" => "ThreeBombs",
			"[dungeon-D6-B1] Misery Mire - compass" => "CompassD6",
			"[dungeon-D6-B1] Misery Mire - end of bridge" => "ThreeBombs",
			"[dungeon-D6-B1] Misery Mire - map room" => "BigKeyD6",
			"[dungeon-D6-B1] Misery Mire - spike room" => "KeyD6",
			"Heart Container - Vitreous" => "MapD6",
			"Misery Mire Crystal" => "Crystal3",
			"[dungeon-D7-1F] Turtle Rock - Chain chomp room" => "Bow",
			"[dungeon-D7-1F] Turtle Rock - compass room" => "TwentyRupees",
			"[dungeon-D7-1F] Turtle Rock - Map room [left chest]" => "KeyD7",
			"[dungeon-D7-1F] Turtle Rock - Map room [right chest]" => "CompassD7",
			"[dungeon-D7-B1] Turtle Rock - big chest" => "KeyD7",
			"[dungeon-D7-B1] Turtle Rock - big key room" => "ProgressiveSword",
			"[dungeon-D7-B1] Turtle Rock - Roller switch room" => "KeyD7",
			"[dungeon-D7-B2] Turtle Rock - Eye bridge room [bottom left chest]" => "KeyD7",
			"[dungeon-D7-B2] Turtle Rock - Eye bridge room [bottom right chest]" => "MapD7",
			"[dungeon-D7-B2] Turtle Rock - Eye bridge room [top left chest]" => "BigKeyD7",
			"[dungeon-D7-B2] Turtle Rock - Eye bridge room [top right chest]" => "PieceOfHeart",
			"Heart Container - Trinexx" => "TwentyRupees",
			"Turtle Rock Crystal" => "PendantOfPower",
			"[dungeon-A2-1F] Ganon's Tower - down left staircase from entrance" => "KeyA2",
			"[dungeon-A2-1F] Ganon's Tower - north of gap room [top left chest]" => "PieceOfHeart",
			"[dungeon-A2-1F] Ganon's Tower - north of gap room [top right chest]" => "KeyA2",
			"[dungeon-A2-1F] Ganon's Tower - north of gap room [bottom left chest]" => "BossHeartContainer",
			"[dungeon-A2-1F] Ganon's Tower - north of gap room [bottom right chest]" => "TwentyRupees",
			"[dungeon-A2-1F] Ganon's Tower - west of teleport room [top left chest]" => "OneHundredRupees",
			"[dungeon-A2-1F] Ganon's Tower - west of teleport room [top right chest]" => "BigKeyA2",
			"[dungeon-A2-1F] Ganon's Tower - west of teleport room [bottom left chest]" => "ThreeBombs",
			"[dungeon-A2-1F] Ganon's Tower - west of teleport room [bottom right chest]" => "TwentyRupees",
			"[dungeon-A2-1F] Ganon's Tower - north of teleport room" => "ProgressiveArmor",
			"[dungeon-A2-1F] Ganon's Tower - map room" => "FiftyRupees",
			"[dungeon-A2-1F] Ganon's Tower - big chest" => "BossHeartContainer",
			"[dungeon-A2-1F] Ganon's Tower - down right staircase from entrance [left chest]" => "KeyA2",
			"[dungeon-A2-1F] Ganon's Tower - down right staircase from entrance [right chest]" => "PieceOfHeart",
			"[dungeon-A2-1F] Ganon's Tower - above Armos" => "BossHeartContainer",
			"[dungeon-A2-1F] Ganon's Tower - east of down right staircase from entrance" => "TwentyRupees",
			"[dungeon-A2-1F] Ganon's Tower - compass room [top left chest]" => "ProgressiveSword",
			"[dungeon-A2-1F] Ganon's Tower - compass room [top right chest]" => "PieceOfHeart",
			"[dungeon-A2-1F] Ganon's Tower - compass room [bottom left chest]" => "PieceOfHeart",
			"[dungeon-A2-1F] Ganon's Tower - compass room [bottom right chest]" => "MoonPearl",
			"[dungeon-A2-B1] Ganon's Tower - north of Armos room [bottom chest]" => "ProgressiveGlove",
			"[dungeon-A2-B1] Ganon's Tower - north of Armos room [left chest]" => "Boomerang",
			"[dungeon-A2-B1] Ganon's Tower - north of Armos room [right chest]" => "KeyA2",
			"[dungeon-A2-6F] Ganon's Tower - north of falling floor four torches [top left chest]" => "MapA2",
			"[dungeon-A2-6F] Ganon's Tower - north of falling floor four torches [top right chest]" => "OneRupee",
			"[dungeon-A2-6F] Ganon's Tower - before Moldorm" => "PieceOfHeart",
			"[dungeon-A2-6F] Ganon's Tower - Moldorm room" => "CompassA2",
			"Agahnim 2" => "DefeatAgahnim2",
			"Turtle Rock Medallion" => "Bombos",
			"Misery Mire Medallion" => "Bombos",
			"Waterfall Bottle" => "BottleWithGreenPotion",
			"Pyramid Bottle" => "BottleWithBluePotion",
		], $loc_item_array);
	}
}
