<?php

declare(strict_types=1);

namespace Tests\Unit\Logic\Inverted\MajorGlitches;

use App\Graph\Randomizer;
use Tests\TestCase;

/**
 * @group graph
 * @group Inverted
 * @group MajorGlitches
 */
final class SwampPalaceTest extends TestCase
{
    /**
     * @param string $location
     * @param bool $access
     * @param array $items
     *
     * @dataProvider accessPool
     */
    public function testLocation(string $location, bool $access, array $items): void
    {
        $randomizer = new Randomizer([[
            'mode.state' => 'inverted',
            'difficulty' => 'test_rules',
            'tech' => config('logic.major_glitches'),
            'logic' => 'MajorGlitches',
        ]]);
        $randomizer->assumeItems(array_merge(['MireEntryEther:0'], array_map(fn ($i) => "$i:0", $items)));
        $this->assertEquals($access, $randomizer->canReachLocation("$location:0"));
    }

    public function accessPool(): array
    {
        return [
            ["Swamp Palace - Entrance Chest", false, []],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'MagicMirror']],
            ["Swamp Palace - Entrance Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Entrance Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Entrance Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Entrance Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Entrance Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Entrance Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Entrance Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Entrance Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Entrance Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Entrance Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Entrance Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Entrance Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Entrance Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Entrance Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Entrance Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Entrance Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Entrance Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Entrance Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Entrance Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Entrance Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],

            ["Swamp Palace - Big Chest", false, []],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'MagicMirror', 'Hammer', 'KeyD2', 'BigKeyD2']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'MoonPearl', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'BottleWithBee', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'BottleWithFairy', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'BottleWithRedPotion', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'BottleWithGreenPotion', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'BottleWithBluePotion', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'Bottle', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'BottleWithGoldBee', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'UncleSword', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'ProgressiveSword', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'MasterSword', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'L3Sword', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'L4Sword', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],

            ["Swamp Palace - Big Key Chest", false, []],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'MagicMirror', 'Hammer', 'KeyD2', 'BigKeyD2']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'MoonPearl', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'BottleWithBee', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'BottleWithFairy', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'BottleWithRedPotion', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'BottleWithGreenPotion', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'BottleWithBluePotion', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'Bottle', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'BottleWithGoldBee', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'UncleSword', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'ProgressiveSword', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'MasterSword', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'L3Sword', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'L4Sword', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Key Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Key Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Key Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Key Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Key Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Key Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Key Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Key Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Key Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Key Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],

            ["Swamp Palace - Map Chest", false, []],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'MagicMirror', 'KeyD2']],
            ["Swamp Palace - Map Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Map Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Map Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Map Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Map Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Map Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Map Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Map Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Map Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Map Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Map Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Map Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Map Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Map Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Map Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Map Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Map Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Map Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Map Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Map Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],

            ["Swamp Palace - West Chest", false, []],
            ["Swamp Palace - West Chest", true, ['Flippers', 'MagicMirror', 'Hammer', 'KeyD2', 'BigKeyD2']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'MoonPearl', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'BottleWithBee', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'BottleWithFairy', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'BottleWithRedPotion', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'BottleWithGreenPotion', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'BottleWithBluePotion', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'Bottle', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'BottleWithGoldBee', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'UncleSword', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'ProgressiveSword', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'MasterSword', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'L3Sword', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'L4Sword', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - West Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - West Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - West Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - West Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - West Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - West Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - West Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - West Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - West Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - West Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],

            ["Swamp Palace - Compass Chest", false, []],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'MagicMirror', 'Hammer', 'KeyD2', 'BigKeyD2']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'MoonPearl', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'BottleWithBee', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'BottleWithFairy', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'BottleWithRedPotion', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'BottleWithGreenPotion', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'BottleWithBluePotion', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'Bottle', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'BottleWithGoldBee', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'UncleSword', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'ProgressiveSword', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'MasterSword', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'L3Sword', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'MagicMirror', 'KeyD2', 'L4Sword', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Compass Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Compass Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Compass Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Compass Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Compass Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Compass Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Compass Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Compass Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Compass Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Compass Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],

            ["Swamp Palace - Flooded Room - Left", false, []],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'Flippers', 'MagicMirror', 'Hammer', 'KeyD2', 'BigKeyD2']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'MoonPearl', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'BottleWithBee', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'BottleWithFairy', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'BottleWithRedPotion', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'BottleWithGreenPotion', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'BottleWithBluePotion', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'Bottle', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'BottleWithGoldBee', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'UncleSword', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'ProgressiveSword', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'MasterSword', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'L3Sword', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'L4Sword', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],

            ["Swamp Palace - Flooded Room - Right", false, []],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'Flippers', 'MagicMirror', 'Hammer', 'KeyD2', 'BigKeyD2']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'MoonPearl', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'BottleWithBee', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'BottleWithFairy', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'BottleWithRedPotion', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'BottleWithGreenPotion', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'BottleWithBluePotion', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'Bottle', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'BottleWithGoldBee', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'UncleSword', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'ProgressiveSword', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'MasterSword', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'L3Sword', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'L4Sword', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],

            ["Swamp Palace - Waterfall Room", false, []],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'Flippers', 'MagicMirror', 'Hammer', 'KeyD2', 'BigKeyD2']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'MoonPearl', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'BottleWithBee', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'BottleWithFairy', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'BottleWithRedPotion', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'BottleWithGreenPotion', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'BottleWithBluePotion', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'Bottle', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'BottleWithGoldBee', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'UncleSword', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'ProgressiveSword', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'MasterSword', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'L3Sword', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'L4Sword', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],

            ["Swamp Palace - Boss", false, []],
            // AnyBottle Seems to not work with the code for canExtendMagic() right now.
            // Testing Instead via the Test below with both allowed Magical Weapons.
            ["Swamp Palace - Boss", false, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'FireRod', 'IceRod', 'MoonPearl', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'Flippers', 'MagicMirror', 'Hammer', 'KeyD2']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'BowAndArrows', 'FireRod', 'MoonPearl', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'HalfMagic', 'FireRod', 'MoonPearl', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'QuarterMagic', 'FireRod', 'MoonPearl', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'FireRod', 'BottleWithBee', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'FireRod', 'BottleWithFairy', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'FireRod', 'BottleWithRedPotion', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'FireRod', 'BottleWithGreenPotion', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'FireRod', 'BottleWithBluePotion', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'FireRod', 'Bottle', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'FireRod', 'BottleWithGoldBee', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'BowAndArrows', 'IceRod', 'MoonPearl', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'HalfMagic', 'IceRod', 'MoonPearl', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'QuarterMagic', 'IceRod', 'MoonPearl', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'IceRod', 'BottleWithBee', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'IceRod', 'BottleWithFairy', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'IceRod', 'BottleWithRedPotion', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'IceRod', 'BottleWithGreenPotion', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'IceRod', 'BottleWithBluePotion', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'IceRod', 'Bottle', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'IceRod', 'BottleWithGoldBee', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'UncleSword', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'ProgressiveSword', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'MasterSword', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'L3Sword', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'Flippers', 'MagicMirror', 'KeyD2', 'L4Sword', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Hookshot', 'MoonPearl', 'Flippers', 'Lamp', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
        ];
    }
}
