<?php

declare(strict_types=1);

namespace Tests\Unit\Logic\Inverted\NoGlitches;

use App\Graph\Randomizer;
use Tests\TestCase;

/**
 * @group graph
 * @group Inverted
 * @group NoGlitches
 */
final class LightWorldTest extends TestCase
{
    /**
     * @param string $location
     * @param bool $access
     * @param array $items
     *
     * @dataProvider accessPool
     */
    public function testLocation(string $location, bool $access, array $items): void
    {
        $randomizer = new Randomizer([[
            'mode.state' => 'inverted',
            'difficulty' => 'test_rules',
            'logic' => 'NoGlitches',
        ]]);
        $randomizer->assumeItems(array_map(fn ($i) => "$i:0", $items));
        $this->assertEquals($access, $randomizer->canReachLocation("$location:0"));
    }

    public function accessPool(): array
    {
        return [
            ["Master Sword Pedestal", false, []],
            ["Master Sword Pedestal", false, ['PendantOfWisdom', 'PendantOfPower', 'AgahnimDefeated']],
            ["Master Sword Pedestal", false, ['PendantOfCourage', 'PendantOfPower', 'AgahnimDefeated']],
            ["Master Sword Pedestal", false, ['PendantOfCourage', 'PendantOfWisdom', 'AgahnimDefeated']],
            ["Master Sword Pedestal", true, ['PendantOfCourage', 'PendantOfWisdom', 'PendantOfPower', 'AgahnimDefeated']],
            ["Master Sword Pedestal", true, ['PendantOfCourage', 'PendantOfWisdom', 'PendantOfPower', 'MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Master Sword Pedestal", true, ['PendantOfCourage', 'PendantOfWisdom', 'PendantOfPower', 'MoonPearl', 'PowerGlove', 'Hammer']],
            ["Master Sword Pedestal", true, ['PendantOfCourage', 'PendantOfWisdom', 'PendantOfPower', 'MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Master Sword Pedestal", true, ['PendantOfCourage', 'PendantOfWisdom', 'PendantOfPower', 'MoonPearl', 'TitansMitt']],

            ["Link's Uncle", false, []],
            ["Link's Uncle", false, ['AgahnimDefeated']],
            ["Link's Uncle", true, ['MoonPearl', 'AgahnimDefeated']],
            ["Link's Uncle", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Link's Uncle", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Link's Uncle", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Link's Uncle", true, ['MoonPearl', 'TitansMitt']],

            ["Secret Passage", false, []],
            ["Secret Passage", false, ['AgahnimDefeated']],
            ["Secret Passage", true, ['MoonPearl', 'AgahnimDefeated']],
            ["Secret Passage", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Secret Passage", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Secret Passage", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Secret Passage", true, ['MoonPearl', 'TitansMitt']],

            ["King's Tomb Chest", false, []],
            ["King's Tomb Chest", false, ['ProgressiveGlove', 'ProgressiveGlove', 'MoonPearl']],
            ["King's Tomb Chest", false, ['PegasusBoots', 'ProgressiveGlove', 'MoonPearl']],
            ["King's Tomb Chest", false, ['PegasusBoots', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["King's Tomb Chest", true, ['PegasusBoots', 'ProgressiveGlove', 'ProgressiveGlove', 'MoonPearl']],
            ["King's Tomb Chest", true, ['PegasusBoots', 'TitansMitt', 'MoonPearl']],

            ["Floodgate Chest", false, []],
            ["Floodgate Chest", false, ['AgahnimDefeated']],
            ["Floodgate Chest", true, ['MoonPearl', 'AgahnimDefeated']],
            ["Floodgate Chest", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Floodgate Chest", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Floodgate Chest", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Floodgate Chest", true, ['MoonPearl', 'TitansMitt']],

            ["Kakariko Tavern", false, []],
            ["Kakariko Tavern", false, ['AgahnimDefeated']],
            ["Kakariko Tavern", true, ['MoonPearl', 'AgahnimDefeated']],
            ["Kakariko Tavern", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Kakariko Tavern", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Kakariko Tavern", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Kakariko Tavern", true, ['MoonPearl', 'TitansMitt']],

            ["Chicken House", false, []],
            ["Chicken House", false, ['AgahnimDefeated']],
            ["Chicken House", true, ['MoonPearl', 'AgahnimDefeated']],
            ["Chicken House", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Chicken House", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Chicken House", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Chicken House", true, ['MoonPearl', 'TitansMitt']],

            ["Aginah's Cave", false, []],
            ["Aginah's Cave", false, ['AgahnimDefeated']],
            ["Aginah's Cave", true, ['MoonPearl', 'AgahnimDefeated']],
            ["Aginah's Cave", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Aginah's Cave", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Aginah's Cave", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Aginah's Cave", true, ['MoonPearl', 'TitansMitt']],

            ["Sahasrahla's Hut - Left", false, []],
            ["Sahasrahla's Hut - Left", false, ['AgahnimDefeated']],
            ["Sahasrahla's Hut - Left", true, ['MoonPearl', 'AgahnimDefeated']],
            ["Sahasrahla's Hut - Left", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Sahasrahla's Hut - Left", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Sahasrahla's Hut - Left", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Sahasrahla's Hut - Left", true, ['MoonPearl', 'TitansMitt']],

            ["Sahasrahla's Hut - Middle", false, []],
            ["Sahasrahla's Hut - Middle", false, ['AgahnimDefeated']],
            ["Sahasrahla's Hut - Middle", true, ['MoonPearl', 'AgahnimDefeated']],
            ["Sahasrahla's Hut - Middle", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Sahasrahla's Hut - Middle", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Sahasrahla's Hut - Middle", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Sahasrahla's Hut - Middle", true, ['MoonPearl', 'TitansMitt']],

            ["Sahasrahla's Hut - Right", false, []],
            ["Sahasrahla's Hut - Right", false, ['AgahnimDefeated']],
            ["Sahasrahla's Hut - Right", true, ['MoonPearl', 'AgahnimDefeated']],
            ["Sahasrahla's Hut - Right", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Sahasrahla's Hut - Right", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Sahasrahla's Hut - Right", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Sahasrahla's Hut - Right", true, ['MoonPearl', 'TitansMitt']],

            ["Kakariko Well - Top", false, []],
            ["Kakariko Well - Top", false, ['AgahnimDefeated']],
            ["Kakariko Well - Top", true, ['MoonPearl', 'AgahnimDefeated']],
            ["Kakariko Well - Top", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Kakariko Well - Top", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Kakariko Well - Top", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Kakariko Well - Top", true, ['MoonPearl', 'TitansMitt']],

            ["Kakariko Well - Left", false, []],
            ["Kakariko Well - Left", false, ['AgahnimDefeated']],
            ["Kakariko Well - Left", true, ['MoonPearl', 'AgahnimDefeated']],
            ["Kakariko Well - Left", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Kakariko Well - Left", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Kakariko Well - Left", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Kakariko Well - Left", true, ['MoonPearl', 'TitansMitt']],

            ["Kakariko Well - Middle", false, []],
            ["Kakariko Well - Middle", false, ['AgahnimDefeated']],
            ["Kakariko Well - Middle", true, ['MoonPearl', 'AgahnimDefeated']],
            ["Kakariko Well - Middle", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Kakariko Well - Middle", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Kakariko Well - Middle", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Kakariko Well - Middle", true, ['MoonPearl', 'TitansMitt']],

            ["Kakariko Well - Right", false, []],
            ["Kakariko Well - Right", false, ['AgahnimDefeated']],
            ["Kakariko Well - Right", true, ['MoonPearl', 'AgahnimDefeated']],
            ["Kakariko Well - Right", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Kakariko Well - Right", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Kakariko Well - Right", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Kakariko Well - Right", true, ['MoonPearl', 'TitansMitt']],

            ["Kakariko Well - Bottom", false, []],
            ["Kakariko Well - Bottom", false, ['AgahnimDefeated']],
            ["Kakariko Well - Bottom", true, ['MoonPearl', 'AgahnimDefeated']],
            ["Kakariko Well - Bottom", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Kakariko Well - Bottom", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Kakariko Well - Bottom", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Kakariko Well - Bottom", true, ['MoonPearl', 'TitansMitt']],

            ["Blind's Hideout - Top", false, []],
            ["Blind's Hideout - Top", false, ['AgahnimDefeated']],
            ["Blind's Hideout - Top", true, ['MoonPearl', 'AgahnimDefeated']],
            ["Blind's Hideout - Top", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Blind's Hideout - Top", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Blind's Hideout - Top", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Blind's Hideout - Top", true, ['MoonPearl', 'TitansMitt']],

            ["Blind's Hideout - Left", false, []],
            ["Blind's Hideout - Left", false, ['AgahnimDefeated']],
            ["Blind's Hideout - Left", true, ['MoonPearl', 'AgahnimDefeated']],
            ["Blind's Hideout - Left", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Blind's Hideout - Left", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Blind's Hideout - Left", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Blind's Hideout - Left", true, ['MoonPearl', 'TitansMitt']],

            ["Blind's Hideout - Right", false, []],
            ["Blind's Hideout - Right", false, ['AgahnimDefeated']],
            ["Blind's Hideout - Right", true, ['MoonPearl', 'AgahnimDefeated']],
            ["Blind's Hideout - Right", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Blind's Hideout - Right", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Blind's Hideout - Right", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Blind's Hideout - Right", true, ['MoonPearl', 'TitansMitt']],

            ["Blind's Hideout - Far Left", false, []],
            ["Blind's Hideout - Far Left", false, ['AgahnimDefeated']],
            ["Blind's Hideout - Far Left", true, ['MoonPearl', 'AgahnimDefeated']],
            ["Blind's Hideout - Far Left", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Blind's Hideout - Far Left", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Blind's Hideout - Far Left", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Blind's Hideout - Far Left", true, ['MoonPearl', 'TitansMitt']],

            ["Blind's Hideout - Far Right", false, []],
            ["Blind's Hideout - Far Right", false, ['AgahnimDefeated']],
            ["Blind's Hideout - Far Right", true, ['MoonPearl', 'AgahnimDefeated']],
            ["Blind's Hideout - Far Right", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Blind's Hideout - Far Right", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Blind's Hideout - Far Right", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Blind's Hideout - Far Right", true, ['MoonPearl', 'TitansMitt']],

            ["Pegasus Rocks", false, []],
            ["Pegasus Rocks", false, ['MoonPearl', 'AgahnimDefeated']],
            ["Pegasus Rocks", false, ['PegasusBoots', 'AgahnimDefeated']],
            ["Pegasus Rocks", true, ['PegasusBoots', 'MoonPearl', 'AgahnimDefeated']],
            ["Pegasus Rocks", true, ['PegasusBoots', 'MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Pegasus Rocks", true, ['PegasusBoots', 'MoonPearl', 'PowerGlove', 'Hammer']],
            ["Pegasus Rocks", true, ['PegasusBoots', 'MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Pegasus Rocks", true, ['PegasusBoots', 'MoonPearl', 'TitansMitt']],

            ["Mini Moldorm Cave - Far Left", false, []],
            ["Mini Moldorm Cave - Far Left", false, ['AgahnimDefeated']],
            ["Mini Moldorm Cave - Far Left", true, ['MoonPearl', 'AgahnimDefeated']],
            ["Mini Moldorm Cave - Far Left", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Mini Moldorm Cave - Far Left", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Mini Moldorm Cave - Far Left", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Mini Moldorm Cave - Far Left", true, ['MoonPearl', 'TitansMitt']],

            ["Mini Moldorm Cave - Left", false, []],
            ["Mini Moldorm Cave - Left", false, ['AgahnimDefeated']],
            ["Mini Moldorm Cave - Left", true, ['MoonPearl', 'AgahnimDefeated']],
            ["Mini Moldorm Cave - Left", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Mini Moldorm Cave - Left", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Mini Moldorm Cave - Left", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Mini Moldorm Cave - Left", true, ['MoonPearl', 'TitansMitt']],

            ["Mini Moldorm Cave - Right", false, []],
            ["Mini Moldorm Cave - Right", false, ['AgahnimDefeated']],
            ["Mini Moldorm Cave - Right", true, ['MoonPearl', 'AgahnimDefeated']],
            ["Mini Moldorm Cave - Right", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Mini Moldorm Cave - Right", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Mini Moldorm Cave - Right", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Mini Moldorm Cave - Right", true, ['MoonPearl', 'TitansMitt']],

            ["Mini Moldorm Cave - Far Right", false, []],
            ["Mini Moldorm Cave - Far Right", false, ['AgahnimDefeated']],
            ["Mini Moldorm Cave - Far Right", true, ['MoonPearl', 'AgahnimDefeated']],
            ["Mini Moldorm Cave - Far Right", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Mini Moldorm Cave - Far Right", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Mini Moldorm Cave - Far Right", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Mini Moldorm Cave - Far Right", true, ['MoonPearl', 'TitansMitt']],

            ["Ice Rod Cave", false, []],
            ["Ice Rod Cave", false, ['AgahnimDefeated']],
            ["Ice Rod Cave", true, ['MoonPearl', 'AgahnimDefeated']],
            ["Ice Rod Cave", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Ice Rod Cave", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Ice Rod Cave", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Ice Rod Cave", true, ['MoonPearl', 'TitansMitt']],

            ["Bottle Merchant", false, []],
            ["Bottle Merchant", true, ['AgahnimDefeated']],
            ["Bottle Merchant", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Bottle Merchant", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Bottle Merchant", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Bottle Merchant", true, ['MoonPearl', 'TitansMitt']],

            ["Sahasrahla's Hut - Sahasrahla", false, []],
            ["Sahasrahla's Hut - Sahasrahla", false, ['AgahnimDefeated']],
            ["Sahasrahla's Hut - Sahasrahla", true, ['PendantOfCourage', 'AgahnimDefeated']],
            ["Sahasrahla's Hut - Sahasrahla", true, ['PendantOfCourage', 'MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Sahasrahla's Hut - Sahasrahla", true, ['PendantOfCourage', 'MoonPearl', 'PowerGlove', 'Hammer']],
            ["Sahasrahla's Hut - Sahasrahla", true, ['PendantOfCourage', 'MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Sahasrahla's Hut - Sahasrahla", true, ['PendantOfCourage', 'MoonPearl', 'TitansMitt']],

            ["Magic Bat", false, []],
            ["Magic Bat", false, ['Powder', 'Hammer', 'MoonPearl']],
            ["Magic Bat", true, ['Powder', 'Hammer', 'MoonPearl', 'AgahnimDefeated']],
            ["Magic Bat", true, ['Powder', 'Hammer', 'MoonPearl', 'ProgressiveGlove']],
            ["Magic Bat", true, ['Powder', 'Hammer', 'MoonPearl', 'PowerGlove']],
            ["Magic Bat", true, ['Powder', 'Hammer', 'MoonPearl', 'TitansMitt']],

            ["Sick Kid", false, []],
            ["Sick Kid", false, ['BottleWithBee']],
            ["Sick Kid", false, ['BottleWithFairy']],
            ["Sick Kid", false, ['BottleWithRedPotion']],
            ["Sick Kid", false, ['BottleWithGreenPotion']],
            ["Sick Kid", false, ['BottleWithBluePotion']],
            ["Sick Kid", false, ['Bottle']],
            ["Sick Kid", false, ['BottleWithGoldBee']],
            ["Sick Kid", true, ['BottleWithBee', 'AgahnimDefeated']],
            ["Sick Kid", true, ['BottleWithBee', 'MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Sick Kid", true, ['BottleWithBee', 'MoonPearl', 'PowerGlove', 'Hammer']],
            ["Sick Kid", true, ['BottleWithBee', 'MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Sick Kid", true, ['BottleWithBee', 'MoonPearl', 'TitansMitt']],
            ["Sick Kid", true, ['BottleWithFairy', 'AgahnimDefeated']],
            ["Sick Kid", true, ['BottleWithFairy', 'MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Sick Kid", true, ['BottleWithFairy', 'MoonPearl', 'PowerGlove', 'Hammer']],
            ["Sick Kid", true, ['BottleWithFairy', 'MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Sick Kid", true, ['BottleWithFairy', 'MoonPearl', 'TitansMitt']],
            ["Sick Kid", true, ['BottleWithRedPotion', 'AgahnimDefeated']],
            ["Sick Kid", true, ['BottleWithRedPotion', 'MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Sick Kid", true, ['BottleWithRedPotion', 'MoonPearl', 'PowerGlove', 'Hammer']],
            ["Sick Kid", true, ['BottleWithRedPotion', 'MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Sick Kid", true, ['BottleWithRedPotion', 'MoonPearl', 'TitansMitt']],
            ["Sick Kid", true, ['BottleWithGreenPotion', 'AgahnimDefeated']],
            ["Sick Kid", true, ['BottleWithGreenPotion', 'MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Sick Kid", true, ['BottleWithGreenPotion', 'MoonPearl', 'PowerGlove', 'Hammer']],
            ["Sick Kid", true, ['BottleWithGreenPotion', 'MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Sick Kid", true, ['BottleWithGreenPotion', 'MoonPearl', 'TitansMitt']],
            ["Sick Kid", true, ['BottleWithBluePotion', 'AgahnimDefeated']],
            ["Sick Kid", true, ['BottleWithBluePotion', 'MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Sick Kid", true, ['BottleWithBluePotion', 'MoonPearl', 'PowerGlove', 'Hammer']],
            ["Sick Kid", true, ['BottleWithBluePotion', 'MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Sick Kid", true, ['BottleWithBluePotion', 'MoonPearl', 'TitansMitt']],
            ["Sick Kid", true, ['Bottle', 'AgahnimDefeated']],
            ["Sick Kid", true, ['Bottle', 'MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Sick Kid", true, ['Bottle', 'MoonPearl', 'PowerGlove', 'Hammer']],
            ["Sick Kid", true, ['Bottle', 'MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Sick Kid", true, ['Bottle', 'MoonPearl', 'TitansMitt']],
            ["Sick Kid", true, ['BottleWithGoldBee', 'AgahnimDefeated']],
            ["Sick Kid", true, ['BottleWithGoldBee', 'MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Sick Kid", true, ['BottleWithGoldBee', 'MoonPearl', 'PowerGlove', 'Hammer']],
            ["Sick Kid", true, ['BottleWithGoldBee', 'MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Sick Kid", true, ['BottleWithGoldBee', 'MoonPearl', 'TitansMitt']],

            ["Hobo", false, []],
            ["Hobo", false, ['MoonPearl', 'AgahnimDefeated']],
            ["Hobo", false, ['Flippers', 'AgahnimDefeated']],
            ["Hobo", true, ['Flippers', 'MoonPearl', 'AgahnimDefeated']],
            ["Hobo", true, ['Flippers', 'MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Hobo", true, ['Flippers', 'MoonPearl', 'PowerGlove', 'Hammer']],
            ["Hobo", true, ['Flippers', 'MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Hobo", true, ['Flippers', 'MoonPearl', 'TitansMitt']],

            ["Bombos Tablet", false, []],
            ["Bombos Tablet", false, ['AgahnimDefeated', 'ProgressiveSword', 'ProgressiveSword']],
            ["Bombos Tablet", false, ['AgahnimDefeated', 'BookOfMudora', 'ProgressiveSword']],
            ["Bombos Tablet", true, ['AgahnimDefeated', 'BookOfMudora', 'ProgressiveSword', 'ProgressiveSword']],
            ["Bombos Tablet", true, ['AgahnimDefeated', 'BookOfMudora', 'L2Sword']],
            ["Bombos Tablet", true, ['AgahnimDefeated', 'BookOfMudora', 'L3Sword']],
            ["Bombos Tablet", true, ['AgahnimDefeated', 'BookOfMudora', 'L4Sword']],
            ["Bombos Tablet", true, ['MoonPearl', 'BookOfMudora', 'ProgressiveGlove', 'ProgressiveGlove', 'ProgressiveSword', 'ProgressiveSword']],
            ["Bombos Tablet", true, ['MoonPearl', 'BookOfMudora', 'ProgressiveGlove', 'ProgressiveGlove', 'L2Sword']],
            ["Bombos Tablet", true, ['MoonPearl', 'BookOfMudora', 'ProgressiveGlove', 'ProgressiveGlove', 'L3Sword']],
            ["Bombos Tablet", true, ['MoonPearl', 'BookOfMudora', 'ProgressiveGlove', 'ProgressiveGlove', 'L4Sword']],
            ["Bombos Tablet", true, ['MoonPearl', 'BookOfMudora', 'TitansMitt', 'ProgressiveSword', 'ProgressiveSword']],
            ["Bombos Tablet", true, ['MoonPearl', 'BookOfMudora', 'TitansMitt', 'L2Sword']],
            ["Bombos Tablet", true, ['MoonPearl', 'BookOfMudora', 'TitansMitt', 'L3Sword']],
            ["Bombos Tablet", true, ['MoonPearl', 'BookOfMudora', 'TitansMitt', 'L4Sword']],
            ["Bombos Tablet", true, ['MoonPearl', 'BookOfMudora', 'ProgressiveGlove', 'Hammer', 'ProgressiveSword', 'ProgressiveSword']],
            ["Bombos Tablet", true, ['MoonPearl', 'BookOfMudora', 'ProgressiveGlove', 'Hammer', 'L2Sword']],
            ["Bombos Tablet", true, ['MoonPearl', 'BookOfMudora', 'ProgressiveGlove', 'Hammer', 'L3Sword']],
            ["Bombos Tablet", true, ['MoonPearl', 'BookOfMudora', 'ProgressiveGlove', 'Hammer', 'L4Sword']],
            ["Bombos Tablet", true, ['MoonPearl', 'BookOfMudora', 'PowerGlove', 'Hammer', 'ProgressiveSword', 'ProgressiveSword']],
            ["Bombos Tablet", true, ['MoonPearl', 'BookOfMudora', 'PowerGlove', 'Hammer', 'L2Sword']],
            ["Bombos Tablet", true, ['MoonPearl', 'BookOfMudora', 'PowerGlove', 'Hammer', 'L3Sword']],
            ["Bombos Tablet", true, ['MoonPearl', 'BookOfMudora', 'PowerGlove', 'Hammer', 'L4Sword']],
            ["Bombos Tablet", true, ['MoonPearl', 'BookOfMudora', 'AgahnimDefeated', 'ProgressiveSword', 'ProgressiveSword']],
            ["Bombos Tablet", true, ['MoonPearl', 'BookOfMudora', 'AgahnimDefeated', 'L2Sword']],
            ["Bombos Tablet", true, ['MoonPearl', 'BookOfMudora', 'AgahnimDefeated', 'L3Sword']],
            ["Bombos Tablet", true, ['MoonPearl', 'BookOfMudora', 'AgahnimDefeated', 'L4Sword']],

            ["King Zora", false, []],
            ["King Zora", false, ['Flippers', 'AgahnimDefeated']],
            ["King Zora", true, ['Flippers', 'MoonPearl', 'AgahnimDefeated']],
            ["King Zora", true, ['ProgressiveGlove', 'MoonPearl', 'Hammer']],
            ["King Zora", true, ['PowerGlove', 'MoonPearl', 'Hammer']],
            ["King Zora", true, ['ProgressiveGlove', 'ProgressiveGlove', 'MoonPearl']],
            ["King Zora", true, ['TitansMitt', 'MoonPearl']],

            ["Lost Woods Hideout", false, []],
            ["Lost Woods Hideout", false, ['AgahnimDefeated']],
            ["Lost Woods Hideout", true, ['MoonPearl', 'AgahnimDefeated']],
            ["Lost Woods Hideout", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Lost Woods Hideout", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Lost Woods Hideout", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Lost Woods Hideout", true, ['MoonPearl', 'TitansMitt']],

            ["Lumberjack Tree", false, []],
            ["Lumberjack Tree", false, ['AgahnimDefeated', 'MoonPearl']],
            ["Lumberjack Tree", false, ['PegasusBoots', 'MoonPearl']],
            ["Lumberjack Tree", false, ['PegasusBoots', 'AgahnimDefeated']],
            ["Lumberjack Tree", true, ['PegasusBoots', 'AgahnimDefeated', 'MoonPearl']],

            ["Cave 45", false, []],
            ["Cave 45", false, ['ProgressiveGlove', 'ProgressiveGlove']],
            ["Cave 45", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Cave 45", true, ['MoonPearl',  'TitansMitt']],
            ["Cave 45", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Cave 45", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Cave 45", true, ['MoonPearl', 'AgahnimDefeated']],

            ["Graveyard Cave Item", false, []],
            ["Graveyard Cave Item", false, ['ProgressiveGlove', 'ProgressiveGlove']],
            ["Graveyard Cave Item", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Graveyard Cave Item", true, ['MoonPearl', 'TitansMitt']],
            ["Graveyard Cave Item", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Graveyard Cave Item", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Graveyard Cave Item", true, ['MoonPearl', 'AgahnimDefeated']],

            ["Checkerboard Cave", false, []],
            ["Checkerboard Cave", false, ['AgahnimDefeated', 'MoonPearl']],
            ["Checkerboard Cave", false, ['ProgressiveGlove', 'AgahnimDefeated']],
            ["Checkerboard Cave", true, ['ProgressiveGlove', 'AgahnimDefeated', 'MoonPearl']],
            ["Checkerboard Cave", true, ['ProgressiveGlove', 'Hammer', 'MoonPearl']],
            ["Checkerboard Cave", true, ['PowerGlove', 'Hammer', 'MoonPearl']],
            ["Checkerboard Cave", true, ['ProgressiveGlove', 'ProgressiveGlove', 'MoonPearl']],
            ["Checkerboard Cave", true, ['TitansMitt', 'MoonPearl']],

            ["Mini Moldorm Cave - NPC", false, []],
            ["Mini Moldorm Cave - NPC", false, ['AgahnimDefeated']],
            ["Mini Moldorm Cave - NPC", true, ['MoonPearl', 'AgahnimDefeated']],
            ["Mini Moldorm Cave - NPC", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Mini Moldorm Cave - NPC", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Mini Moldorm Cave - NPC", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Mini Moldorm Cave - NPC", true, ['MoonPearl', 'TitansMitt']],

            ["Library", false, []],
            ["Library", false, ['MoonPearl', 'AgahnimDefeated']],
            ["Library", false, ['PegasusBoots', 'AgahnimDefeated']],
            ["Library", true, ['PegasusBoots', 'MoonPearl', 'AgahnimDefeated']],
            ["Library", true, ['PegasusBoots', 'MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Library", true, ['PegasusBoots', 'MoonPearl', 'PowerGlove', 'Hammer']],
            ["Library", true, ['PegasusBoots', 'MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Library", true, ['PegasusBoots', 'MoonPearl', 'TitansMitt']],

            ["Mushroom", false, []],
            ["Mushroom", false, ['AgahnimDefeated']],
            ["Mushroom", true, ['MoonPearl', 'AgahnimDefeated']],
            ["Mushroom", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Mushroom", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Mushroom", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Mushroom", true, ['MoonPearl', 'TitansMitt']],

            ["Potion Shop Item", false, []],
            ["Potion Shop Item", false, ['MoonPearl', 'AgahnimDefeated']],
            ["Potion Shop Item", false, ['Mushroom', 'AgahnimDefeated']],
            ["Potion Shop Item", true, ['Mushroom', 'MoonPearl', 'AgahnimDefeated']],
            ["Potion Shop Item", true, ['Mushroom', 'MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Potion Shop Item", true, ['Mushroom', 'MoonPearl', 'PowerGlove', 'Hammer']],
            ["Potion Shop Item", true, ['Mushroom', 'MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Potion Shop Item", true, ['Mushroom', 'MoonPearl', 'TitansMitt']],

            ["Maze Race", false, []],
            ["Maze Race", false, ['AgahnimDefeated']],
            ["Maze Race", true, ['MoonPearl', 'AgahnimDefeated']],
            ["Maze Race", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Maze Race", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Maze Race", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Maze Race", true, ['MoonPearl', 'TitansMitt']],

            ["Desert Ledge - Item", false, []],
            ["Desert Ledge - Item", false, ['MoonPearl', 'AgahnimDefeated']],
            ["Desert Ledge - Item", false, ['BookOfMudora', 'AgahnimDefeated']],
            ["Desert Ledge - Item", true, ['BookOfMudora', 'MoonPearl', 'AgahnimDefeated']],
            ["Desert Ledge - Item", true, ['BookOfMudora', 'MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Desert Ledge - Item", true, ['BookOfMudora', 'MoonPearl', 'PowerGlove', 'Hammer']],
            ["Desert Ledge - Item", true, ['BookOfMudora', 'MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Desert Ledge - Item", true, ['BookOfMudora', 'MoonPearl', 'TitansMitt']],

            ["Lake Hylia Island", false, []],
            ["Lake Hylia Island", false, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Lake Hylia Island", false, ['Flippers', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Lake Hylia Island", true, ['Flippers', 'MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Lake Hylia Island", true, ['Flippers', 'MoonPearl', 'TitansMitt']],
            ["Lake Hylia Island", true, ['Flippers', 'MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Lake Hylia Island", true, ['Flippers', 'MoonPearl', 'PowerGlove', 'Hammer']],
            ["Lake Hylia Island", true, ['Flippers', 'MoonPearl', 'AgahnimDefeated']],

            ["Sunken Treasure", false, []],
            ["Sunken Treasure", false, ['AgahnimDefeated']],
            ["Sunken Treasure", true, ['MoonPearl', 'AgahnimDefeated']],
            ["Sunken Treasure", true, ['MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Sunken Treasure", true, ['MoonPearl', 'PowerGlove', 'Hammer']],
            ["Sunken Treasure", true, ['MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Sunken Treasure", true, ['MoonPearl', 'TitansMitt']],

            ["Zora's Domain Ledge Item", false, []],
            ["Zora's Domain Ledge Item", false, ['MoonPearl', 'AgahnimDefeated']],
            ["Zora's Domain Ledge Item", false, ['Flippers', 'AgahnimDefeated']],
            ["Zora's Domain Ledge Item", true, ['Flippers', 'MoonPearl', 'AgahnimDefeated']],
            ["Zora's Domain Ledge Item", true, ['Flippers', 'MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Zora's Domain Ledge Item", true, ['Flippers', 'MoonPearl', 'PowerGlove', 'Hammer']],
            ["Zora's Domain Ledge Item", true, ['Flippers', 'MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Zora's Domain Ledge Item", true, ['Flippers', 'MoonPearl', 'TitansMitt']],

            ["Flute Spot", false, []],
            ["Flute Spot", false, ['MoonPearl', 'AgahnimDefeated']],
            ["Flute Spot", false, ['Shovel', 'AgahnimDefeated']],
            ["Flute Spot", true, ['Shovel', 'MoonPearl', 'AgahnimDefeated']],
            ["Flute Spot", true, ['Shovel', 'MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Flute Spot", true, ['Shovel', 'MoonPearl', 'PowerGlove', 'Hammer']],
            ["Flute Spot", true, ['Shovel', 'MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Flute Spot", true, ['Shovel', 'MoonPearl', 'TitansMitt']],

            ["Waterfall Fairy - Left", false, []],
            ["Waterfall Fairy - Left", false, ['MoonPearl', 'AgahnimDefeated']],
            ["Waterfall Fairy - Left", false, ['Flippers', 'AgahnimDefeated']],
            ["Waterfall Fairy - Left", true, ['Flippers', 'MoonPearl', 'AgahnimDefeated']],
            ["Waterfall Fairy - Left", true, ['Flippers', 'MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Waterfall Fairy - Left", true, ['Flippers', 'MoonPearl', 'PowerGlove', 'Hammer']],
            ["Waterfall Fairy - Left", true, ['Flippers', 'MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Waterfall Fairy - Left", true, ['Flippers', 'MoonPearl', 'TitansMitt']],

            ["Waterfall Fairy - Right", false, []],
            ["Waterfall Fairy - Right", false, ['MoonPearl', 'AgahnimDefeated']],
            ["Waterfall Fairy - Right", false, ['Flippers', 'AgahnimDefeated']],
            ["Waterfall Fairy - Right", true, ['Flippers', 'MoonPearl', 'AgahnimDefeated']],
            ["Waterfall Fairy - Right", true, ['Flippers', 'MoonPearl', 'ProgressiveGlove', 'Hammer']],
            ["Waterfall Fairy - Right", true, ['Flippers', 'MoonPearl', 'PowerGlove', 'Hammer']],
            ["Waterfall Fairy - Right", true, ['Flippers', 'MoonPearl', 'ProgressiveGlove', 'ProgressiveGlove']],
            ["Waterfall Fairy - Right", true, ['Flippers', 'MoonPearl', 'TitansMitt']],

            ["Ganon", false, []],
            // @todo need to update Ganon Reqs
            // ["Ganon", true, ['MoonPearl', 'AgahnimDefeated2']],
        ];
    }
}
