<?php

declare(strict_types=1);

namespace Tests\Unit\Logic\Inverted\NoGlitches;

use App\Graph\Randomizer;
use Tests\TestCase;

/**
 * @group graph
 * @group Inverted
 * @group NoGlitches
 */
class MiseryMireTest extends TestCase
{
    /**
     * @param string $location
     * @param bool $access
     * @param array $items
     *
     * @dataProvider accessPool
     */
    public function testLocation(string $location, bool $access, array $items): void
    {
        $randomizer = new Randomizer([[
            'mode.state' => 'inverted',
            'difficulty' => 'test_rules',
            'logic' => 'NoGlitches',
        ]]);
        $randomizer->assumeItems(array_merge(['MireEntryEther:0'], array_map(fn ($i) => "$i:0", $items)));
        $this->assertEquals($access, $randomizer->canReachLocation("$location:0"));
    }

    public function accessPool(): array
    {
        return [
            ["Misery Mire - Big Chest", false, []],
            ["Misery Mire - Big Chest", false, ['MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'Hookshot']],

            ["Misery Mire - Main Lobby Chest", false, []],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'Hookshot']],

            ["Misery Mire - Big Key Chest", false, []],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'Hookshot']],

            ["Misery Mire - Compass Chest", false, []],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'Hookshot']],

            ["Misery Mire - Bridge Chest", false, []],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Bridge Chest", true, ['MagicMirror', 'AgahnimDefeated', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Bridge Chest", true, ['MagicMirror', 'AgahnimDefeated', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Bridge Chest", true, ['MagicMirror', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Bridge Chest", true, ['MagicMirror', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'Hookshot']],

            ["Misery Mire - Map Chest", false, []],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'Hookshot']],

            ["Misery Mire - Spike Chest", false, []],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Spike Chest", true, ['MagicMirror', 'AgahnimDefeated', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Spike Chest", true, ['MagicMirror', 'AgahnimDefeated', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Spike Chest", true, ['MagicMirror', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Spike Chest", true, ['MagicMirror', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'Hookshot']],

            ["Misery Mire - Boss", false, []],
            ["Misery Mire - Boss", false, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Boss", false, ['KeyD6', 'KeyD6', 'BigKeyD6', 'CaneOfSomaria', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Boss", false, ['KeyD6', 'KeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'OcarinaInactive', 'TitansMitt', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'OcarinaInactive', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'OcarinaInactive', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'MagicMirror', 'TitansMitt', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'ProgressiveGlove', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'MagicMirror', 'ProgressiveGlove', 'Hammer', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MagicMirror', 'AgahnimDefeated', 'Ether', 'ProgressiveSword', 'Hookshot']],
        ];
    }
}
