<?php
return [
    'advancement' => [
        'L1Sword' => 0,
        //'L1SwordAndShield' => 0,  // This still downgrades your sword - don't allow it as a random item unless that's fixed
        'MasterSword' => 0,
        'ProgressiveSword' => 4,
        'BossHeartContainer' => 10,
        'BottleWithRandom' => 4,
        'Bottle' => 0,
        'BottleWithRedPotion' => 0,
        'BottleWithGreenPotion' => 0,
        'BottleWithBluePotion' => 0,
        'BottleWithBee' => 0,
        'BottleWithGoldBee' => 0,
        'BottleWithFairy' => 0,
        'Bombos' => 1,
        'BookOfMudora' => 1,
        'Bow' => 0,
        'BowAndArrows' => 0,
        'CaneOfSomaria' => 1,
        'Cape' => 1,
        'Ether' => 1,
        'FireRod' => 1,
        'Flippers' => 1,
        'Hammer' => 1,
        'Hookshot' => 1,
        'IceRod' => 1,
        'Lamp' => 1,
        'MagicMirror' => 1,
        'MoonPearl' => 1,
        'Mushroom' => 1,
        'OcarinaInactive' => 1,
        'OcarinaActive' => 0,
        'PegasusBoots' => 1,
        'Powder' => 1,
        'PowerGlove' => 0,
        'Quake' => 1,
        'Shovel' => 1,
        'TitansMitt' => 0,
        'BowAndSilverArrows' => 0,
        'SilverArrowUpgrade' => 0,
        'ProgressiveGlove' => 2,
        'ProgressiveBow' => 2,
        'Triforce' => 0,
        'TriforcePiece' => 0,
        'PowerStar' => 0,
        'BugCatchingNet' => 1,
        'MirrorShield' => 0,
        'ProgressiveShield' => 3,
        'CaneOfByrna' => 1,
        'TenBombs' => 1,
        'HalfMagic' => 1,
        'QuarterMagic' => 0,
    ],
    'nice' => [
        'L3Sword' => 0,
        'L4Sword' => 0,
        'HeartContainer' => 1,
        'BlueShield' => 0,
        'ProgressiveArmor' => 2,
        'BlueMail' => 0,
        'Boomerang' => 1,
        'RedBoomerang' => 1,
        'RedShield' => 0,
        'RedMail' => 0,
        'BlueClock' => 0,
        'RedClock' => 0,
        'GreenClock' => 0,
    ],
    'junk' => [
        'PieceOfHeart' => 24,
        'BombUpgrade5' => 0,
        'BombUpgrade10' => 0,
        'ArrowUpgrade5' => 0,
        'ArrowUpgrade10' => 0,
        'Arrow' => 1,
        'TenArrows' => 12,
        'Bomb' => 0,
        'ThreeBombs' => 16,
        'OneRupee' => 2,
        'FiveRupees' => 4,
        'TwentyRupees' => 28,
        'TwentyRupees2' => 0,
        'FiftyRupees' => 7,
        'OneHundredRupees' => 1,
        'ThreeHundredRupees' => 5,
        'Heart' => 0,
        'SmallMagic' => 0,
        'Rupoor' => 0,
    ],
    'dungeon' => [
        //'ganonstower' => [
        'BigKeyA2' => 1,
        'KeyA2' => 4,
        'MapA2' => 1,
        'CompassA2' => 1,
        //],
        //'darkness' => [
        'BigKeyD1' => 1,
        'KeyD1' => 6,
        'MapD1' => 1,
        'CompassD1' => 1,
        //],
        //'swamp' => [
        'BigKeyD2' => 1,
        'KeyD2' => 1,
        'MapD2' => 1,
        'CompassD2' => 1,
        //],
        //'skullwoods' => [
        'BigKeyD3' => 1,
        'KeyD3' => 3,
        'MapD3' => 1,
        'CompassD3' => 1,
        //],
        //'theives' => [
        'BigKeyD4' => 1,
        'KeyD4' => 1,
        'MapD4' => 1,
        'CompassD4' => 1,
        //],
        //'ice' => [
        'BigKeyD5' => 1,
        'KeyD5' => 2,
        'MapD5' => 1,
        'CompassD5' => 1,
        //],
        //'mire' => [
        'BigKeyD6' => 1,
        'KeyD6' => 3,
        'MapD6' => 1,
        'CompassD6' => 1,
        //],
        //'turtlerock' => [
        'BigKeyD7' => 1,
        'KeyD7' => 4,
        'MapD7' => 1,
        'CompassD7' => 1,
        //],
        //'eastern' => [
        'BigKeyP1' => 1,
        'MapP1' => 1,
        'CompassP1' => 1,
        //],
        //'desert' => [
        'BigKeyP2' => 1,
        'KeyP2' => 1,
        'MapP2' => 1,
        'CompassP2' => 1,
        //],
        //'hera' => [
        'BigKeyP3' => 1,
        'KeyP3' => 1,
        'MapP3' => 1,
        'CompassP3' => 1,
        //],
        //'agahnim' => [
        'KeyA1' => 2,
        //],
        //'castle' => [
        'KeyH2' => 1,
        'MapH2' => 1,
        //]
    ],
    'drop' => [
        'Heart' => 13,
        'RupeeGreen' => 9,
        'RupeeBlue' => 7,
        'RupeeRed' => 6,
        'BombRefill1' => 7,
        'BombRefill4' => 1,
        'BombRefill8' => 2,
        'MagicRefillSmall' => 6,
        'MagicRefillFull' => 3,
        'ArrowRefill5' => 5,
        'ArrowRefill10' => 3,
        'Fairy' => 1,
        'BeeGood' => 0,
        'Bee' => 0,
    ],
];
