<?php

return [
    '001.link.1.zspr' => [
        'name' => 'Link',
        'author' => 'Nintendo',
        'file' => '001.link.1.zspr',
        'version' => 1,
        'vtversion' => '0',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    '4slink-armors.1.zspr' => [
        'name' => 'Four Swords Link',
        'author' => 'Mike Trethewey',
        'file' => '4slink-armors.1.zspr',
        'version' => 1,
        'vtversion' => '26',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'abigail.1.zspr' => [
        'name' => 'Abigail',
        'author' => 'Fish_waffle64',
        'file' => 'abigail.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Female',
        ],
    ],
    'adol.1.zspr' => [
        'name' => 'Adol',
        'author' => 'Yuushia',
        'file' => 'adol.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Ys',
            1 => 'Male',
        ],
    ],
    'aggretsuko.1.zspr' => [
        'name' => 'Aggretsuko',
        'author' => 'skovacs1',
        'file' => 'aggretsuko.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Cartoon',
            1 => 'Animal',
            2 => 'Female',
        ],
    ],
    'alice.1.zspr' => [
        'name' => 'Alice',
        'author' => 'Artheau',
        'file' => 'alice.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'demonetized' => true,
        'tags' => [
            0 => 'Female',
        ],
    ],
    'angry-video-game-nerd.1.zspr' => [
        'name' => 'Angry Video Game Nerd',
        'author' => 'ABOhiccups',
        'file' => 'angry-video-game-nerd.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Personality',
            1 => 'Male',
        ],
    ],
    'arcane.1.zspr' => [
        'name' => 'Arcane',
        'author' => 'MM102',
        'file' => 'arcane.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Personality',
        ],
    ],
    'ark-dorana.2.zspr' => [
        'name' => 'Ark (No Cape)',
        'author' => 'Dorana',
        'file' => 'ark-dorana.2.zspr',
        'version' => 2,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Terranigma',
            1 => 'Male',
        ],
    ],
    'ark.1.zspr' => [
        'name' => 'Ark (Cape)',
        'author' => 'wzl',
        'file' => 'ark.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Terranigma',
            1 => 'Male',
        ],
    ],
    'arrghus.3.zspr' => [
        'name' => 'Arrghus',
        'author' => 'kan',
        'file' => 'arrghus.3.zspr',
        'version' => 3,
        'vtversion' => '28',
        'tags' => [
            0 => 'Male',
            1 => 'Legend of Zelda',
            2 => 'ALTTP NPC',
            3 => 'Boss',
        ],
    ],
    'astronaut.1.zspr' => [
        'name' => 'Astronaut',
        'author' => 'Malmo',
        'file' => 'astronaut.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'IRL',
        ],
    ],
    'asuna.2.zspr' => [
        'name' => 'Asuna',
        'author' => 'Natsuru Kiyohoshi',
        'file' => 'asuna.2.zspr',
        'version' => 2,
        'vtversion' => '31.0.7',
        'tags' => [
            0 => 'Female',
            1 => 'Sword Art Online',
        ],
    ],
    'badeline.1.zspr' => [
        'name' => 'Badeline',
        'author' => 'Jam',
        'file' => 'badeline.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Celeste',
            1 => 'Female',
        ],
    ],
    'bananas-in-pyjamas.1.zspr' => [
        'name' => 'Bananas In Pyjamas',
        'author' => 'codemann8',
        'file' => 'bananas-in-pyjamas.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Cartoon',
        ],
    ],
    'bandit.1.zspr' => [
        'name' => 'Bandit',
        'author' => 'Fenrika',
        'file' => 'bandit.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Mario',
        ],
    ],
    'batman.1.zspr' => [
        'name' => 'Batman',
        'author' => 'Ninjakauz',
        'file' => 'batman.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Superhero',
            1 => 'Male',
            2 => 'DC Comics',
        ],
    ],
    'beau.1.zspr' => [
        'name' => 'Beau',
        'author' => 'Achy',
        'file' => 'beau.1.zspr',
        'version' => 1,
        'vtversion' => '28',
        'tags' => [
            0 => 'Animal Crossing',
            1 => 'Male',
            2 => 'Animal',
        ],
    ],
    'bewp.1.zspr' => [
        'name' => 'Bewp',
        'author' => 'Valechec',
        'file' => 'bewp.1.zspr',
        'version' => 1,
        'vtversion' => '27',
        'tags' => [
            0 => 'Animal',
            1 => 'Streamer',
            2 => 'Personality',
        ],
    ],
    'bigkey.2.zspr' => [
        'name' => 'Big Key',
        'author' => 'kan',
        'file' => 'bigkey.2.zspr',
        'version' => 2,
        'vtversion' => '29',
        'tags' => [
            0 => 'Legend of Zelda',
        ],
    ],
    'birb.2.zspr' => [
        'name' => 'Birb',
        'author' => 'Dr. Deadrewski',
        'file' => 'birb.2.zspr',
        'version' => 2,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Bird',
            1 => 'Animal',
            2 => 'Streamer',
        ],
    ],
    'birdo.1.zspr' => [
        'name' => 'Birdo',
        'author' => 'BlackTycoon',
        'file' => 'birdo.1.zspr',
        'version' => 1,
        'vtversion' => '31',
        'tags' => [
            0 => 'Female',
            1 => 'Mario',
        ],
    ],
    'blackmage.1.zspr' => [
        'name' => 'Black Mage',
        'author' => 'TheRedMage',
        'file' => 'blackmage.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Final Fantasy',
        ],
    ],
    'blacksmithlink.1.zspr' => [
        'name' => 'Blacksmith Link',
        'author' => 'Glan',
        'file' => 'blacksmithlink.1.zspr',
        'version' => 1,
        'vtversion' => '29',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
            3 => 'ALTTP NPC',
        ],
    ],
    'blazer.1.zspr' => [
        'name' => 'Blazer',
        'author' => 'Herowho',
        'file' => 'blazer.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.7',
        'tags' => [
            0 => 'Male',
        ],
    ],
    'blossom.1.zspr' => [
        'name' => 'Blossom',
        'author' => 'Artheau',
        'file' => 'blossom.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'demonetized' => true,
        'tags' => [
            0 => 'Female',
            1 => 'Powerpuff Girls',
            2 => 'Superhero',
            3 => 'Cartoon Network',
        ],
    ],
    'bob.2.zspr' => [
        'name' => 'Bob',
        'author' => 'kan',
        'file' => 'bob.2.zspr',
        'version' => 2,
        'vtversion' => '29',
        'tags' => [
            0 => 'Randomizer',
            1 => 'ALTTP NPC',
            2 => 'Legend of Zelda',
        ],
    ],
    'bobross.1.zspr' => [
        'name' => 'Bob Ross',
        'author' => 'CaptainApathy',
        'file' => 'bobross.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.7',
        'tags' => [
            0 => 'Male',
            1 => 'Personality',
        ],
    ],
    'boco.2.zspr' => [
        'name' => 'Boco the Chocobo',
        'author' => 'TarThoron',
        'file' => 'boco.2.zspr',
        'version' => 2,
        'vtversion' => '31.0.7',
        'tags' => [
            0 => 'Final Fantasy',
            1 => 'Animal',
        ],
    ],
    'boo-two.1.zspr' => [
        'name' => 'Boo 2',
        'author' => 'Achy',
        'file' => 'boo-two.1.zspr',
        'version' => 1,
        'vtversion' => '29',
        'tags' => [
            0 => 'Mario',
            1 => 'Ghost',
        ],
    ],
    'boo.2.zspr' => [
        'name' => 'Boo',
        'author' => 'Zarby89',
        'file' => 'boo.2.zspr',
        'version' => 2,
        'vtversion' => '25',
        'tags' => [
            0 => 'Mario',
            1 => 'Ghost',
        ],
    ],
    'bottle_o_goo.1.zspr' => [
        'name' => 'Bottle o\' Goo',
        'author' => 'Fish_waffle64',
        'file' => 'bottle_o_goo.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Legend of Zelda',
        ],
    ],
    'botw-link.1.zspr' => [
        'name' => 'BotW Link',
        'author' => 'Pasta La Vista',
        'file' => 'botw-link.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.7',
        'tags' => [
            0 => 'Legend of Zelda',
            1 => 'Male',
        ],
    ],
    'botw-zelda.1.zspr' => [
        'name' => 'BotW Zelda',
        'author' => 'Roo',
        'file' => 'botw-zelda.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Legend of Zelda',
            1 => 'Female',
        ],
    ],
    'bowser.1.zspr' => [
        'name' => 'Bowser',
        'author' => 'Artheau',
        'file' => 'bowser.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'demonetized' => true,
        'tags' => [
            0 => 'Male',
            1 => 'Mario',
            2 => 'Villain',
        ],
    ],
    'bowsette-red.1.zspr' => [
        'name' => 'Bowsette (Red)',
        'author' => 'Sarah Shinespark',
        'file' => 'bowsette-red.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.7',
        'tags' => [
            0 => 'Mario',
            1 => 'Female',
            2 => 'Villain',
        ],
    ],
    'bowsette.1.zspr' => [
        'name' => 'Bowsette',
        'author' => 'Sarah Shinespark',
        'file' => 'bowsette.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.7',
        'tags' => [
            0 => 'Mario',
            1 => 'Female',
            2 => 'Villain',
        ],
    ],
    'branch.1.zspr' => [
        'name' => 'Branch',
        'author' => 'cbass601',
        'file' => 'branch.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Trolls',
            1 => 'Male',
        ],
    ],
    'brian.1.zspr' => [
        'name' => 'Brian',
        'author' => 'Herowho',
        'file' => 'brian.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Quest',
            1 => 'Male',
        ],
    ],
    'broccoli.2.zspr' => [
        'name' => 'Broccoli',
        'author' => 'kan',
        'file' => 'broccoli.2.zspr',
        'version' => 2,
        'vtversion' => '29',
        'tags' => [
            0 => 'Legend of Zelda',
            1 => 'ALTTP NPC',
        ],
    ],
    'bronzor.2.zspr' => [
        'name' => 'Bronzor',
        'author' => 'kan',
        'file' => 'bronzor.2.zspr',
        'version' => 2,
        'vtversion' => '30',
        'tags' => [
            0 => 'Pokemon',
        ],
    ],
    'bsboy.1.zspr' => [
        'name' => 'B.S. Boy',
        'author' => 'InTheBeef',
        'file' => 'bsboy.1.zspr',
        'version' => 1,
        'vtversion' => '25',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'bsgirl.1.zspr' => [
        'name' => 'B.S. Girl',
        'author' => 'InTheBeef',
        'file' => 'bsgirl.1.zspr',
        'version' => 1,
        'vtversion' => '25',
        'tags' => [
            0 => 'Link',
            1 => 'Female',
            2 => 'Legend of Zelda',
        ],
    ],
    'bubbles.1.zspr' => [
        'name' => 'Bubbles',
        'author' => 'Artheau',
        'file' => 'bubbles.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'demonetized' => true,
        'tags' => [
            0 => 'Female',
            1 => 'Superhero',
            2 => 'Powerpuff Girls',
            3 => 'Cartoon Network',
        ],
    ],
    'bullet_bill.1.zspr' => [
        'name' => 'Bullet Bill',
        'author' => 'Artheau',
        'file' => 'bullet_bill.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'demonetized' => true,
        'tags' => [
            0 => 'Mario',
        ],
    ],
    'buttercup.1.zspr' => [
        'name' => 'Buttercup',
        'author' => 'Artheau',
        'file' => 'buttercup.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'demonetized' => true,
        'tags' => [
            0 => 'Female',
            1 => 'Superhero',
            2 => 'Powerpuff Girls',
            3 => 'Cartoon Network',
        ],
    ],
    'cactuar.1.zspr' => [
        'name' => 'Cactuar',
        'author' => 'RyuTech',
        'file' => 'cactuar.1.zspr',
        'version' => 1,
        'vtversion' => '27',
        'tags' => [
            0 => 'Final Fantasy',
        ],
    ],
    'cadence.1.zspr' => [
        'name' => 'Cadence',
        'author' => 'Fish_waffle64',
        'file' => 'cadence.1.zspr',
        'version' => 1,
        'vtversion' => '31',
        'tags' => [
            0 => 'Crypt of the Necrodancer',
            1 => 'Cadence of Hyrule',
            2 => 'Female',
        ],
    ],
    'carlsagan42.1.zspr' => [
        'name' => 'CarlSagan42',
        'author' => 'FedoraFriday',
        'file' => 'carlsagan42.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'note' => 'No permission secured for usage on other sites',
        'permitted' => [
            0 => 'ALttPR'
        ],
        'tags' => [
            0 => 'Personality',
            1 => 'Mario',
            2 => 'Streamer',
        ],
    ],
    'casual-zelda.1.zspr' => [
        'name' => 'Casual Zelda',
        'author' => 'Fish_waffle64',
        'file' => 'casual-zelda.1.zspr',
        'version' => 1,
        'vtversion' => '30',
        'tags' => [
            0 => 'Female',
            1 => 'Legend of Zelda',
        ],
    ],
    'cat.3.zspr' => [
        'name' => 'Marvin the Cat',
        'author' => 'Fish_waffle64',
        'file' => 'cat.3.zspr',
        'version' => 3,
        'vtversion' => '30',
        'tags' => [
            0 => 'Personality',
            1 => 'Animal',
            2 => 'Male',
            3 => 'Cat',
        ],
    ],
    'catboo.1.zspr' => [
        'name' => 'Cat Boo',
        'author' => 'JaySee87',
        'file' => 'catboo.1.zspr',
        'version' => 1,
        'vtversion' => '25',
        'tags' => [
            0 => 'Mario',
            1 => 'Ghost',
            2 => 'Cat',
        ],
    ],
    'cdilink.1.zspr' => [
        'name' => 'CD-i Link',
        'author' => 'SnipSlum',
        'file' => 'cdilink.1.zspr',
        'version' => 1,
        'vtversion' => '30',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'celes.1.zspr' => [
        'name' => 'Celes',
        'author' => 'Deagans',
        'file' => 'celes.1.zspr',
        'version' => 1,
        'vtversion' => '30',
        'tags' => [
            0 => 'Final Fantasy',
            1 => 'Female',
        ],
    ],
    'charizard.1.zspr' => [
        'name' => 'Charizard',
        'author' => 'Charmander106',
        'file' => 'charizard.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Pokemon',
        ],
    ],
    'cheepcheep.1.zspr' => [
        'name' => 'Cheep Cheep',
        'author' => 'Faw',
        'file' => 'cheepcheep.1.zspr',
        'version' => 1,
        'vtversion' => '29',
        'tags' => [
            0 => 'Mario',
            1 => 'Fish',
        ],
    ],
    'chibity.1.zspr' => [
        'name' => 'Chibity',
        'author' => 'Ecyro',
        'file' => 'chibity.1.zspr',
        'version' => 1,
        'vtversion' => '31',
        'tags' => [
            0 => 'Personality',
        ],
    ],
    'chrizzz.1.zspr' => [
        'name' => 'Chrizzz',
        'author' => 'Chrizzz',
        'file' => 'chrizzz.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.7',
        'tags' => [
            0 => 'Link',
            1 => 'Personality',
        ],
    ],
    'cirno.1.zspr' => [
        'name' => 'Cirno',
        'author' => 'Achy',
        'file' => 'cirno.1.zspr',
        'version' => 1,
        'vtversion' => '26.2',
        'tags' => [
            0 => 'Touhou Project',
            1 => 'Female',
        ],
    ],
    'clifford.1.zspr' => [
        'name' => 'Clifford',
        'author' => 'PlaguedOne',
        'file' => 'clifford.1.zspr',
        'version' => 1,
        'vtversion' => '30',
        'demonetized' => true,
        'tags' => [
            0 => 'Animal',
            1 => 'Dog',
        ],
    ],
    'clyde.1.zspr' => [
        'name' => 'Clyde',
        'author' => 'Artheau',
        'file' => 'clyde.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'demonetized' => true,
        'tags' => [
            0 => 'Pac-man',
            1 => 'Namco',
            2 => 'Ghost',
        ],
    ],
    'conker.1.zspr' => [
        'name' => 'Conker',
        'author' => 'Charmander106/SePH',
        'file' => 'conker.1.zspr',
        'version' => 1,
        'vtversion' => '29',
        'tags' => [
            0 => 'Rare',
            1 => 'Animal',
        ],
    ],
    'cornelius.1.zspr' => [
        'name' => 'Cornelius',
        'author' => 'Lori',
        'file' => 'cornelius.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Odin Sphere',
            1 => 'Male',
        ],
    ],
    'corona.2.zspr' => [
        'name' => 'Corona',
        'author' => 'Herowho',
        'file' => 'corona.2.zspr',
        'version' => 2,
        'vtversion' => '31',
        'tags' => [
            0 => 'King\'s Quest',
            1 => 'Male',
        ],
    ],
    'crewmate.2.zspr' => [
        'name' => 'Crewmate',
        'author' => 'Fish_waffle64',
        'file' => 'crewmate.2.zspr',
        'version' => 2,
        'vtversion' => '31.0.7',
        'tags' => [
            0 => 'Among Us',
        ],
    ],
    'cucco.2.zspr' => [
        'name' => 'Cucco',
        'author' => 'Mike Trethewey',
        'file' => 'cucco.2.zspr',
        'version' => 2,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Legend of Zelda',
            1 => 'ALTTP NPC',
            2 => 'Bird',
        ],
    ],
    'cursor.1.zspr' => [
        'name' => 'Cursor',
        'author' => 'PlaguedOne',
        'file' => 'cursor.1.zspr',
        'version' => 1,
        'vtversion' => '29',
        'demonetized' => true,
        'tags' => [
            0 => 'Personality',
        ],
    ],
    'd_owls.2.zspr' => [
        'name' => 'D.Owls',
        'author' => 'D.Owls',
        'file' => 'd_owls.2.zspr',
        'version' => 2,
        'vtversion' => '31',
        'tags' => [
            0 => 'Personality',
            1 => 'Male',
        ],
    ],
    'dark-panda.1.zspr' => [
        'name' => 'Dark Panda',
        'author' => 'MM102',
        'file' => 'dark-panda.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Personality',
        ],
    ],
    'darkboy.1.zspr' => [
        'name' => 'Dark Boy',
        'author' => 'iBazly',
        'file' => 'darkboy.1.zspr',
        'version' => 1,
        'vtversion' => '26',
        'permitted' => [
            0 => 'ALttPR'
        ],
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'darkgirl.1.zspr' => [
        'name' => 'Dark Girl',
        'author' => 'iBazly',
        'file' => 'darkgirl.1.zspr',
        'version' => 1,
        'vtversion' => '26',
        'permitted' => [
            0 => 'ALttPR'
        ],
        'tags' => [
            0 => 'Link',
            1 => 'Female',
            2 => 'Legend of Zelda',
        ],
    ],
    'darklink-tunic.1.zspr' => [
        'name' => 'Dark Link (Tunic)',
        'author' => 'Damon',
        'file' => 'darklink-tunic.1.zspr',
        'version' => 1,
        'vtversion' => '28',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'darklink.1.zspr' => [
        'name' => 'Dark Link',
        'author' => 'iBazly',
        'file' => 'darklink.1.zspr',
        'version' => 1,
        'vtversion' => '26',
        'permitted' => [
            0 => 'ALttPR'
        ],
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'darkswatchy.1.zspr' => [
        'name' => 'Dark Swatchy',
        'author' => 'Mike Trethewey',
        'file' => 'darkswatchy.1.zspr',
        'version' => 1,
        'vtversion' => '26',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'darkzelda.1.zspr' => [
        'name' => 'Dark Zelda',
        'author' => 'iBazly',
        'file' => 'darkzelda.1.zspr',
        'version' => 1,
        'vtversion' => '26',
        'permitted' => [
            0 => 'ALttPR'
        ],
        'tags' => [
            0 => 'Female',
            1 => 'Legend of Zelda',
        ],
    ],
    'darkzora.2.zspr' => [
        'name' => 'Dark Zora',
        'author' => 'iBazly',
        'file' => 'darkzora.2.zspr',
        'version' => 2,
        'vtversion' => '26',
        'tags' => [
            0 => 'Legend of Zelda',
            1 => 'ALTTP NPC',
        ],
    ],
    'deadpool-mythic.1.zspr' => [
        'name' => 'Deadpool (Mythic)',
        'author' => 'Mythic',
        'file' => 'deadpool-mythic.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Superhero',
            1 => 'Marvel',
            2 => 'Male',
        ],
    ],
    'deadpool.1.zspr' => [
        'name' => 'Deadpool (SirCzah)',
        'author' => 'SirCzah',
        'file' => 'deadpool.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Superhero',
            1 => 'Marvel',
            2 => 'Male',
        ],
    ],
    'deadrock.1.zspr' => [
        'name' => 'Deadrock',
        'author' => 'Glan',
        'file' => 'deadrock.1.zspr',
        'version' => 1,
        'vtversion' => '30',
        'tags' => [
            0 => 'Legend of Zelda',
            1 => 'ALTTP NPC',
        ],
    ],
    'decidueye.1.zspr' => [
        'name' => 'Decidueye',
        'author' => 'Achy',
        'file' => 'decidueye.1.zspr',
        'version' => 1,
        'vtversion' => '25',
        'tags' => [
            0 => 'Pokemon',
            1 => 'Bird',
        ],
    ],
    'dekar.1.zspr' => [
        'name' => 'Dekar',
        'author' => 'The3X',
        'file' => 'dekar.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.7',
        'tags' => [
            0 => 'Male',
            1 => 'Lufia',
        ],
    ],
    'demonlink.1.zspr' => [
        'name' => 'Demon Link',
        'author' => 'Krelbel',
        'file' => 'demonlink.1.zspr',
        'version' => 1,
        'vtversion' => '25',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'dragonite.2.zspr' => [
        'name' => 'Dragonite',
        'author' => 'Fish_waffle64',
        'file' => 'dragonite.2.zspr',
        'version' => 2,
        'vtversion' => '31',
        'tags' => [
            0 => 'Pokemon',
        ],
    ],
    'drake.2.zspr' => [
        'name' => 'Drake The Dragon',
        'author' => 'NO Body The Dragon',
        'file' => 'drake.2.zspr',
        'version' => 2,
        'vtversion' => '30.5',
        'demonetized' => true,
        'tags' => [
            0 => 'Personality',
            1 => 'Male',
        ],
    ],
    'eggplant.1.zspr' => [
        'name' => 'Eggplant',
        'author' => 'PlaguedOne',
        'file' => 'eggplant.1.zspr',
        'version' => 1,
        'vtversion' => '30',
        'demonetized' => true,
        'tags' => [
            0 => 'Emoji',
        ],
    ],
    'emosaru.1.zspr' => [
        'name' => 'EmoSaru',
        'author' => 'Achy',
        'file' => 'emosaru.1.zspr',
        'version' => 1,
        'vtversion' => '28',
        'permitted' => [
            0 => 'ALttPR'
        ],
        'demonetized' => true,
        'tags' => [
            0 => 'Personality',
            1 => 'Streamer',
        ],
    ],
    'ezlo.1.zspr' => [
        'name' => 'Ezlo',
        'author' => 'cbass601',
        'file' => 'ezlo.1.zspr',
        'version' => 1,
        'vtversion' => '30',
        'tags' => [
            0 => 'Legend of Zelda',
            1 => 'Male',
        ],
    ],
    'fierce-deity-link.3.zspr' => [
        'name' => 'Fierce Deity Link',
        'author' => 'Jeffreygriggs2',
        'file' => 'fierce-deity-link.3.zspr',
        'version' => 3,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Link',
            1 => 'Legend of Zelda',
            2 => 'Male',
        ],
    ],
    'finn.3.zspr' => [
        'name' => 'Finn Merten',
        'author' => 'Devan2002',
        'file' => 'finn.3.zspr',
        'version' => 3,
        'vtversion' => '31',
        'tags' => [
            0 => 'Cartoon Network',
            1 => 'Male',
        ],
    ],
    'finny_bear.1.zspr' => [
        'name' => 'Finny Bear',
        'author' => 'skovacs1',
        'file' => 'finny_bear.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Animal',
            1 => 'Personality',
        ],
    ],
    'fish_floodgate.1.zspr' => [
        'name' => 'Floodgate Fish',
        'author' => 'Delphi1024',
        'file' => 'fish_floodgate.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Legend of Zelda',
            1 => 'ALTTP NPC',
            2 => 'Animal',
        ],
    ],
    'flavor_guy.1.zspr' => [
        'name' => 'Flavor Guy',
        'author' => 'PlaguedOne',
        'file' => 'flavor_guy.1.zspr',
        'version' => 1,
        'vtversion' => '31',
        'demonetized' => true,
        'tags' => [
            0 => 'Personality',
            1 => 'Male',
        ],
    ],
    'foxlink.1.zspr' => [
        'name' => 'Fox Link',
        'author' => 'InTheBeef',
        'file' => 'foxlink.1.zspr',
        'version' => 1,
        'vtversion' => '28',
        'tags' => [
            0 => 'Link',
            1 => 'Animal',
        ],
    ],
    'freya.1.zspr' => [
        'name' => 'Freya Crescent',
        'author' => 'Demoncraze',
        'file' => 'freya.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.6',
        'tags' => [
            0 => 'Final Fantasy',
            1 => 'Female',
        ],
    ],
    'frisk.2.zspr' => [
        'name' => 'Frisk',
        'author' => 'TobyFox/MisterKerr',
        'file' => 'frisk.2.zspr',
        'version' => 2,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Undertale',
        ],
    ],
    'froglink.3.zspr' => [
        'name' => 'Frog Link',
        'author' => 'Mike Trethewey',
        'file' => 'froglink.3.zspr',
        'version' => 3,
        'vtversion' => '25',
        'tags' => [
            0 => 'Link',
            1 => 'Animal',
        ],
    ],
    'fujin.2.zspr' => [
        'name' => 'Fujin',
        'author' => 'FujinAkari',
        'file' => 'fujin.2.zspr',
        'version' => 2,
        'vtversion' => '31',
        'tags' => [
            0 => 'Final Fantasy',
        ],
    ],
    'future_trunks.1.zspr' => [
        'name' => 'Future Trunks',
        'author' => 'Merciter',
        'file' => 'future_trunks.1.zspr',
        'version' => 1,
        'vtversion' => '31',
        'tags' => [
            0 => 'Dragonball',
            1 => 'Male',
        ],
    ],
    'gamer.2.zspr' => [
        'name' => 'Gamer',
        'author' => 'InTheBeef',
        'file' => 'gamer.2.zspr',
        'version' => 2,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
        ],
    ],
    'ganon.2.zspr' => [
        'name' => 'Mini Ganon',
        'author' => 'atth3h3art0fwinter',
        'file' => 'ganon.2.zspr',
        'version' => 2,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Villain',
            1 => 'ALTTP NPC',
            2 => 'Male',
            3 => 'Legend of Zelda',
            4 => 'Boss',
        ],
    ],
    'ganondorf.2.zspr' => [
        'name' => 'Ganondorf',
        'author' => 'Fish_waffle64',
        'file' => 'ganondorf.2.zspr',
        'version' => 2,
        'vtversion' => '27',
        'tags' => [
            0 => 'Villain',
            1 => 'ALTTP NPC',
            2 => 'Male',
            3 => 'Legend of Zelda',
            4 => 'Boss',
        ],
    ],
    'garfield.2.zspr' => [
        'name' => 'Garfield',
        'author' => 'Fwiller',
        'file' => 'garfield.2.zspr',
        'version' => 2,
        'vtversion' => '26',
        'tags' => [
            0 => 'Male',
            1 => 'Animal',
        ],
    ],
    'garnet.1.zspr' => [
        'name' => 'Garnet',
        'author' => 'Artheau',
        'file' => 'garnet.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'demonetized' => true,
        'tags' => [
            0 => 'Female',
            1 => 'Cartoon Network',
        ],
    ],
    'garomaster.1.zspr' => [
        'name' => 'Garo Master',
        'author' => 'Herowho',
        'file' => 'garomaster.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Legend of Zelda',
        ],
    ],
    'gbc-link.1.zspr' => [
        'name' => 'GBC Link',
        'author' => 'skovacs1',
        'file' => 'gbc-link.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'geno.2.zspr' => [
        'name' => 'Geno',
        'author' => 'FedoraFriday',
        'file' => 'geno.2.zspr',
        'version' => 2,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Mario',
            1 => 'Male',
        ],
    ],
    'gliitchwiitch.1.zspr' => [
        'name' => 'GliitchWiitch',
        'author' => 'Ivy-IV',
        'file' => 'gliitchwiitch.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.7',
        'tags' => [
            0 => 'Female',
            1 => 'Personality',
            2 => 'Streamer',
        ],
    ],
    'gobli.1.zspr' => [
        'name' => 'Gobli',
        'author' => 'Lantis',
        'file' => 'gobli.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Male',
        ],
    ],
    'goomba.1.zspr' => [
        'name' => 'Goomba',
        'author' => 'SirCzah',
        'file' => 'goomba.1.zspr',
        'version' => 1,
        'vtversion' => '30',
        'tags' => [
            0 => 'Mario',
        ],
    ],
    'goose.1.zspr' => [
        'name' => 'Goose',
        'author' => 'Jam',
        'file' => 'goose.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Bird',
            1 => 'Animal',
        ],
    ],
    'grandpoobear.2.zspr' => [
        'name' => 'GrandPOOBear',
        'author' => 'proximitysound',
        'file' => 'grandpoobear.2.zspr',
        'version' => 2,
        'vtversion' => '30',
        'permitted' => [
            0 => 'ALttPR'
        ],
        'tags' => [
            0 => 'Personality',
            1 => 'Streamer',
            2 => 'Animal',
            3 => 'Male',
        ],
    ],
    'gretis.1.zspr' => [
        'name' => 'Gretis',
        'author' => 'SnakeGrunger',
        'file' => 'gretis.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.7',
        'tags' => [
            0 => 'Male',
            1 => 'Personality',
            2 => 'Streamer',
        ],
    ],
    'grunclestan.1.zspr' => [
        'name' => 'Gruncle Stan',
        'author' => 'SirCzah',
        'file' => 'grunclestan.1.zspr',
        'version' => 1,
        'vtversion' => '30',
        'tags' => [
            0 => 'Disney',
            1 => 'Male',
        ],
    ],
    'guiz.2.zspr' => [
        'name' => 'Guiz',
        'author' => 'GuizDP',
        'file' => 'guiz.2.zspr',
        'version' => 2,
        'vtversion' => '31.0.6',
        'tags' => [
            0 => 'Personality',
            1 => 'Streamer',
            2 => 'Male',
        ],
    ],
    'hanna.1.zspr' => [
        'name' => 'Hanna',
        'author' => 'Maya-Neko',
        'file' => 'hanna.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.7',
        'tags' => [
            0 => 'Female',
            1 => 'Personality',
        ],
    ],
    'hardhat_beetle.1.zspr' => [
        'name' => 'Hardhat Beetle',
        'author' => 'Artheau',
        'file' => 'hardhat_beetle.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'demonetized' => true,
        'tags' => [
            0 => 'ALTTP NPC',
            1 => 'Legend of Zelda',
        ],
    ],
    'hat-kid.1.zspr' => [
        'name' => 'Hat Kid',
        'author' => 'skovacs1',
        'file' => 'hat-kid.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Female',
            1 => 'A Hat in Time',
        ],
    ],
    'headlesslink.2.zspr' => [
        'name' => 'Headless Link',
        'author' => 'kan',
        'file' => 'headlesslink.2.zspr',
        'version' => 2,
        'vtversion' => '27',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'hello_kitty.1.zspr' => [
        'name' => 'Hello Kitty',
        'author' => 'qeeen',
        'file' => 'hello_kitty.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Female',
            1 => 'Cat',
            2 => 'Animal',
        ],
    ],
    'hidari.1.zspr' => [
        'name' => 'Hidari',
        'author' => 'Hidari',
        'file' => 'hidari.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Legend of Zelda',
            1 => 'ALTTP NPC',
        ],
    ],
    'hint_tile.1.zspr' => [
        'name' => 'Hint Tile',
        'author' => 'PlaguedOne',
        'file' => 'hint_tile.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'demonetized' => true,
        'tags' => [
            0 => 'ALTTP NPC',
        ],
    ],
    'hoarder-bush.1.zspr' => [
        'name' => 'Hoarder (Bush)',
        'author' => 'Restomak',
        'file' => 'hoarder-bush.1.zspr',
        'version' => 1,
        'vtversion' => '30',
        'tags' => [
            0 => 'ALTTP NPC',
            1 => 'Legend of Zelda',
        ],
    ],
    'hoarder-pot.1.zspr' => [
        'name' => 'Hoarder (Pot)',
        'author' => 'Restomak',
        'file' => 'hoarder-pot.1.zspr',
        'version' => 1,
        'vtversion' => '30',
        'tags' => [
            0 => 'ALTTP NPC',
            1 => 'Legend of Zelda',
        ],
    ],
    'hoarder-rock.1.zspr' => [
        'name' => 'Hoarder (Rock)',
        'author' => 'Restomak',
        'file' => 'hoarder-rock.1.zspr',
        'version' => 1,
        'vtversion' => '30',
        'tags' => [
            0 => 'ALTTP NPC',
            1 => 'Legend of Zelda',
        ],
    ],
    'hollow-knight.2.zspr' => [
        'name' => 'Hollow Knight',
        'author' => 'Chew_Terr',
        'file' => 'hollow-knight.2.zspr',
        'version' => 2,
        'vtversion' => '31.0.7',
        'tags' => [
            0 => 'Hollow Knight',
        ],
    ],
    'homer.1.zspr' => [
        'name' => 'Homer Simpson',
        'author' => 'Fwiller',
        'file' => 'homer.1.zspr',
        'version' => 1,
        'vtversion' => '31',
        'tags' => [
            0 => 'Simpsons',
            1 => 'Male',
        ],
    ],
    'hotdog.1.zspr' => [
        'name' => 'Hotdog',
        'author' => 'Xag & Tylo',
        'file' => 'hotdog.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.7',
        'tags' => [
            0 => 'Link',
            1 => 'Food',
        ],
    ],
    'hyruleknight.1.zspr' => [
        'name' => 'Hyrule Knight',
        'author' => 'InTheBeef',
        'file' => 'hyruleknight.1.zspr',
        'version' => 1,
        'vtversion' => '29',
        'tags' => [
            0 => 'ALTTP NPC',
            1 => 'Legend of Zelda',
        ],
    ],
    'ibazly.1.zspr' => [
        'name' => 'iBazly',
        'author' => 'Achy',
        'file' => 'ibazly.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'permitted' => [
            0 => 'ALttPR'
        ],
        'tags' => [
            0 => 'Personality',
            1 => 'Streamer',
            2 => 'Male',
        ],
    ],
    'ignignokt.3.zspr' => [
        'name' => 'Ignignokt',
        'author' => 'kan',
        'file' => 'ignignokt.3.zspr',
        'version' => 3,
        'vtversion' => '30',
        'tags' => [
            0 => 'Male',
            1 => 'Alien',
            2 => 'Cartoon Network',
            3 => 'Aqua Teen Hunger Force',
        ],
    ],
    'informant_woman.1.zspr' => [
        'name' => 'Informant Woman',
        'author' => 'Herowho',
        'file' => 'informant_woman.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'ALTTP NPC',
            1 => 'Female',
            2 => 'Legend of Zelda',
        ],
    ],
    'inkling.1.zspr' => [
        'name' => 'Inkling',
        'author' => 'RyuTech',
        'file' => 'inkling.1.zspr',
        'version' => 1,
        'vtversion' => '27',
        'tags' => [
            0 => 'Splatoon',
        ],
    ],
    'invisibleman.1.zspr' => [
        'name' => 'Invisible Link',
        'author' => 'Mike Trethewey',
        'file' => 'invisibleman.1.zspr',
        'version' => 1,
        'vtversion' => '25',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'jack-frost.1.zspr' => [
        'name' => 'Jack Frost',
        'author' => 'xypotion',
        'file' => 'jack-frost.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Shin Megami Tensei',
        ],
    ],
    'jason_frudnick.1.zspr' => [
        'name' => 'Jason Frudnick',
        'author' => 'Artheau',
        'file' => 'jason_frudnick.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'demonetized' => true,
        'tags' => [
            0 => 'Blast Master',
            1 => 'Male',
        ],
    ],
    'jasp.1.zspr' => [
        'name' => 'Jasp',
        'author' => 'Chonixtu',
        'file' => 'jasp.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Personality',
        ],
    ],
    'jogurt.1.zspr' => [
        'name' => 'Jogurt',
        'author' => 'Nakuri',
        'file' => 'jogurt.1.zspr',
        'version' => 1,
        'vtversion' => '29',
        'tags' => [
            0 => 'Personality',
        ],
    ],
    'katsura.2.zspr' => [
        'name' => 'Katsura',
        'author' => 'atth3h3art0fwinter',
        'file' => 'katsura.2.zspr',
        'version' => 2,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Gintama',
            1 => 'Cartoon',
            2 => 'Male',
        ],
    ],
    'kecleon.1.zspr' => [
        'name' => 'Kecleon',
        'author' => 'Gylergin',
        'file' => 'kecleon.1.zspr',
        'version' => 1,
        'vtversion' => '30',
        'tags' => [
            0 => 'Pokemon',
        ],
    ],
    'kenny_mccormick.1.zspr' => [
        'name' => 'Kenny McCormick',
        'author' => 'Artheau',
        'file' => 'kenny_mccormick.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'demonetized' => true,
        'tags' => [
            0 => 'South Park',
            1 => 'Male',
        ],
    ],
    'ketchup.1.zspr' => [
        'name' => 'Ketchup',
        'author' => 't0uchan',
        'file' => 'ketchup.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.6',
        'tags' => [
            0 => 'Tasty',
            1 => 'IRL',
        ],
    ],
    'kholdstare.2.zspr' => [
        'name' => 'Kholdstare',
        'author' => 'kan',
        'file' => 'kholdstare.2.zspr',
        'version' => 2,
        'vtversion' => '30',
        'tags' => [
            0 => 'ALTTP NPC',
            1 => 'Legend of Zelda',
            2 => 'Boss',
        ],
    ],
    'king_gothalion.1.zspr' => [
        'name' => 'King Gothalion',
        'author' => 'kickpixel',
        'file' => 'king_gothalion.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Streamer',
            1 => 'Personality',
            2 => 'Male',
        ],
    ],
    'king_graham.2.zspr' => [
        'name' => 'King Graham',
        'author' => 'MisterKerr',
        'file' => 'king_graham.2.zspr',
        'version' => 2,
        'vtversion' => '31',
        'tags' => [
            0 => 'King\'s Quest',
            1 => 'Male',
        ],
    ],
    'kirby-meta.1.zspr' => [
        'name' => 'Kirby',
        'author' => 'KHRoxas',
        'file' => 'kirby-meta.1.zspr',
        'version' => 1,
        'vtversion' => '26',
        'tags' => [
            0 => 'Male',
            1 => 'Kirby',
        ],
    ],
    'kore8.1.zspr' => [
        'name' => 'Kore8',
        'author' => 'Skewer',
        'file' => 'kore8.1.zspr',
        'version' => 1,
        'vtversion' => '27',
        'tags' => [
            0 => 'Personality',
        ],
    ],
    'korok.1.zspr' => [
        'name' => 'Korok',
        'author' => 'atth3h3art0fwinter',
        'file' => 'korok.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.7',
        'tags' => [
            0 => 'The Legend of Zelda',
            1 => 'Wind Waker',
            2 => 'NPC',
        ],
    ],
    'lakitu.1.zspr' => [
        'name' => 'Lakitu',
        'author' => 'SirCzah',
        'file' => 'lakitu.1.zspr',
        'version' => 1,
        'vtversion' => '30',
        'tags' => [
            0 => 'Mario',
        ],
    ],
    'lapras.1.zspr' => [
        'name' => 'Lapras',
        'author' => 'Fish_waffle64',
        'file' => 'lapras.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Pokemon',
        ],
    ],
    'lest.1.zspr' => [
        'name' => 'Lest',
        'author' => 'PrideToRuleEarth',
        'file' => 'lest.1.zspr',
        'version' => 1,
        'vtversion' => '31',
        'tags' => [
            0 => 'Final Fantasy',
        ],
    ],
    'lily.1.zspr' => [
        'name' => 'Lily',
        'author' => 'ScatlinkSean',
        'file' => 'lily.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Blossom Tales',
            1 => 'Female',
        ],
    ],
    'linja.1.zspr' => [
        'name' => 'Linja',
        'author' => 'Razhagal',
        'file' => 'linja.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'link-redrawn.1.zspr' => [
        'name' => 'Link Redrawn',
        'author' => 'Spiffy',
        'file' => 'link-redrawn.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.7',
        'tags' => [
            0 => 'Link',
            1 => 'ALTTP',
            2 => 'Male',
        ],
    ],
    'linkhatcolor.1.zspr' => [
        'name' => 'Hat Color Link',
        'author' => 'Damon',
        'file' => 'linkhatcolor.1.zspr',
        'version' => 1,
        'vtversion' => '29',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'linktuniccolor.1.zspr' => [
        'name' => 'Tunic Color Link',
        'author' => 'Damon',
        'file' => 'linktuniccolor.1.zspr',
        'version' => 1,
        'vtversion' => '29',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'little-hylian.1.zspr' => [
        'name' => 'Little Hylian',
        'author' => 'MM102',
        'file' => 'little-hylian.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.7',
        'tags' => [
            0 => 'Male',
            1 => 'Personality',
            2 => 'Pokemon',
        ],
    ],
    'littlepony.1.zspr' => [
        'name' => 'Pony',
        'author' => 'Botchos',
        'file' => 'littlepony.1.zspr',
        'version' => 1,
        'vtversion' => '25',
        'tags' => [
            0 => 'My Little Pony',
            1 => 'Female',
            2 => 'Animal',
        ],
    ],
    'locke.1.zspr' => [
        'name' => 'Locke',
        'author' => 'Rose',
        'file' => 'locke.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.7',
        'tags' => [
            0 => 'Male',
            1 => 'Final Fantasy',
        ],
    ],
    'locke_merchant.1.zspr' => [
        'name' => 'Figaro Merchant',
        'author' => 'Artheau',
        'file' => 'locke_merchant.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'demonetized' => true,
        'tags' => [
            0 => 'Final Fantasy',
            1 => 'Male',
        ],
    ],
    'lucario.1.zspr' => [
        'name' => 'Lucario',
        'author' => 'Achy',
        'file' => 'lucario.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Pokemon',
        ],
    ],
    'luffy.2.zspr' => [
        'name' => 'Luffy',
        'author' => 'BOtheMighty',
        'file' => 'luffy.2.zspr',
        'version' => 2,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Personality',
            1 => 'Streamer',
            2 => 'Male',
        ],
    ],
    'luigi.1.zspr' => [
        'name' => 'Luigi',
        'author' => 'Achy',
        'file' => 'luigi.1.zspr',
        'version' => 1,
        'vtversion' => '26.2',
        'tags' => [
            0 => 'Male',
            1 => 'Mario',
            2 => 'Superhero',
        ],
    ],
    'luna-maindo.1.zspr' => [
        'name' => 'Luna Maindo',
        'author' => 'IkkyLights',
        'file' => 'luna-maindo.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.7',
        'tags' => [
            0 => 'Female',
            1 => 'Elsword',
        ],
    ],
    'madeline.1.zspr' => [
        'name' => 'Madeline',
        'author' => 'Jam',
        'file' => 'madeline.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Female',
            1 => 'Celeste',
        ],
    ],
    'magus.1.zspr' => [
        'name' => 'Magus',
        'author' => 'PlaguedOne',
        'file' => 'magus.1.zspr',
        'version' => 1,
        'vtversion' => '30',
        'demonetized' => true,
        'tags' => [
            0 => 'Chrono Trigger',
            1 => 'Villain',
            2 => 'Male',
        ],
    ],
    'maiden.1.zspr' => [
        'name' => 'Maiden',
        'author' => 'Plan',
        'file' => 'maiden.1.zspr',
        'version' => 1,
        'vtversion' => '26',
        'tags' => [
            0 => 'ALTTP NPC',
            1 => 'Female',
            2 => 'Legend of Zelda',
        ],
    ],
    'mallow-cat.1.zspr' => [
        'name' => 'Mallow (Cat)',
        'author' => 'FedoraFriday',
        'file' => 'mallow-cat.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Cat',
            1 => 'Animal',
            2 => 'Streamer',
        ],
    ],
    'mangalink.2.zspr' => [
        'name' => 'Manga Link',
        'author' => 'kan',
        'file' => 'mangalink.2.zspr',
        'version' => 2,
        'vtversion' => '29',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'maplequeen.2.zspr' => [
        'name' => 'Maple Queen',
        'author' => 'Zarby89',
        'file' => 'maplequeen.2.zspr',
        'version' => 2,
        'vtversion' => '25',
        'tags' => [
            0 => 'Female',
        ],
    ],
    'marin.2.zspr' => [
        'name' => 'Marin',
        'author' => 'Nocturnesthesia',
        'file' => 'marin.2.zspr',
        'version' => 2,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Legend of Zelda',
            1 => 'Female',
        ],
    ],
    'mario-classic.2.zspr' => [
        'name' => 'Mario (Classic)',
        'author' => 'Damon',
        'file' => 'mario-classic.2.zspr',
        'version' => 2,
        'vtversion' => '29',
        'tags' => [
            0 => 'Mario',
            1 => 'Male',
        ],
    ],
    'mario_tanooki.2.zspr' => [
        'name' => 'Tanooki Mario',
        'author' => 'Nocturnesthesia',
        'file' => 'mario_tanooki.2.zspr',
        'version' => 2,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Mario',
            1 => 'Male',
        ],
    ],
    'mariocappy.1.zspr' => [
        'name' => 'Mario and Cappy',
        'author' => 'Damon',
        'file' => 'mariocappy.1.zspr',
        'version' => 1,
        'vtversion' => '29',
        'tags' => [
            0 => 'Mario',
            1 => 'Male',
        ],
    ],
    'marisa.1.zspr' => [
        'name' => 'Marisa Kirisame',
        'author' => 'Achy',
        'file' => 'marisa.1.zspr',
        'version' => 1,
        'vtversion' => '26',
        'tags' => [
            0 => 'Touhou Project',
            1 => 'Female',
        ],
    ],
    'matthias.1.zspr' => [
        'name' => 'Matthias',
        'author' => 'Marcus Bolduc',
        'file' => 'matthias.1.zspr',
        'version' => 1,
        'vtversion' => '31',
        'tags' => [
            0 => 'Redwall',
            1 => 'Male',
            2 => 'Cartoon',
            3 => 'Book',
        ],
    ],
    'meatwad.2.zspr' => [
        'name' => 'Meatwad',
        'author' => 'kan',
        'file' => 'meatwad.2.zspr',
        'version' => 2,
        'vtversion' => '30',
        'tags' => [
            0 => 'Male',
            1 => 'Aqua Teen Hunger Force',
            2 => 'Cartoon Network',
        ],
    ],
    'medallions.1.zspr' => [
        'name' => 'Medallions',
        'author' => 'Mike Trethewey',
        'file' => 'medallions.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'ALTTP NPC',
            1 => 'Legend of Zelda',
        ],
    ],
    'medli.1.zspr' => [
        'name' => 'Medli',
        'author' => 'Kzinssie',
        'file' => 'medli.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Legend of Zelda',
            1 => 'Female',
            2 => 'Bird',
        ],
    ],
    'megaman-x.2.zspr' => [
        'name' => 'Megaman X',
        'author' => 'PlaguedOne',
        'file' => 'megaman-x.2.zspr',
        'version' => 2,
        'vtversion' => '28',
        'demonetized' => true,
        'tags' => [
            0 => 'Male',
            1 => 'Megaman',
        ],
    ],
    'metroid.1.zspr' => [
        'name' => 'Baby Metroid',
        'author' => 'Jam',
        'file' => 'metroid.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Metroid',
            1 => 'Alien',
        ],
    ],
    'mew.1.zspr' => [
        'name' => 'MewLp',
        'author' => 'MewLp',
        'file' => 'mew.1.zspr',
        'version' => 1,
        'vtversion' => '31',
        'tags' => [
            0 => 'Pokemon',
        ],
    ],
    'mike-jones.2.zspr' => [
        'name' => 'Mike Jones',
        'author' => 'Fish_waffle64',
        'file' => 'mike-jones.2.zspr',
        'version' => 2,
        'vtversion' => '25',
        'tags' => [
            0 => 'StarTropics',
            1 => 'Male',
        ],
    ],
    'minish_link.1.zspr' => [
        'name' => 'Minish Link',
        'author' => 'Artheau',
        'file' => 'minish_link.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'demonetized' => true,
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'minishcaplink.3.zspr' => [
        'name' => 'Minish Cap Link',
        'author' => 'InTheBeef',
        'file' => 'minishcaplink.3.zspr',
        'version' => 3,
        'vtversion' => '30',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'missingno.2.zspr' => [
        'name' => 'missingno',
        'author' => 'AAhbxsujd',
        'file' => 'missingno.2.zspr',
        'version' => 2,
        'vtversion' => '29',
        'tags' => [
            0 => 'Pokemon',
        ],
    ],
    'moblin.2.zspr' => [
        'name' => 'Moblin',
        'author' => 'Noctai_',
        'file' => 'moblin.2.zspr',
        'version' => 2,
        'vtversion' => '31.0.7',
        'tags' => [
            0 => 'Legend of Zelda',
            1 => 'ALTTP',
        ],
    ],
    'modernlink.1.zspr' => [
        'name' => 'Modern Link',
        'author' => 'RyuTech',
        'file' => 'modernlink.1.zspr',
        'version' => 1,
        'vtversion' => '27',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'mog.2.zspr' => [
        'name' => 'Mog',
        'author' => 'Krelbel',
        'file' => 'mog.2.zspr',
        'version' => 2,
        'vtversion' => '25',
        'tags' => [
            0 => 'Final Fantasy',
        ],
    ],
    'momiji.1.zspr' => [
        'name' => 'Momiji Inubashiri',
        'author' => 'Ardaceus',
        'file' => 'momiji.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Touhou Project',
            1 => 'Female',
        ],
    ],
    'moosh.1.zspr' => [
        'name' => 'Moosh',
        'author' => 'PlaguedOne',
        'file' => 'moosh.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'demonetized' => true,
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
            3 => 'Animal',
        ],
    ],
    'mouse.1.zspr' => [
        'name' => 'Mouse',
        'author' => 'Malthaez',
        'file' => 'mouse.1.zspr',
        'version' => 1,
        'vtversion' => '28',
        'tags' => [
            0 => 'Link',
            1 => 'Animal',
        ],
    ],
    'ms-paintdog.1.zspr' => [
        'name' => 'Ms. Paint Dog',
        'author' => 'TehRealSalt',
        'file' => 'ms-paintdog.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Animal',
        ],
    ],
    'mushy.1.zspr' => [
        'name' => 'Power Up with Pride Mushroom',
        'author' => 'Achy',
        'file' => 'mushy.1.zspr',
        'version' => 1,
        'vtversion' => '30',
        'tags' => [
            0 => 'Pride',
        ],
    ],
    'naturelink.1.zspr' => [
        'name' => 'Nature Link',
        'author' => 'iBazly',
        'file' => 'naturelink.1.zspr',
        'version' => 1,
        'vtversion' => '27',
        'permitted' => [
            0 => 'ALttPR'
        ],
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'navi.1.zspr' => [
        'name' => 'Navi',
        'author' => 'qwertymodo',
        'file' => 'navi.1.zspr',
        'version' => 1,
        'vtversion' => '29',
        'tags' => [
            0 => 'Female',
            1 => 'Legend of Zelda',
        ],
    ],
    'navirou.3.zspr' => [
        'name' => 'Navirou',
        'author' => 'Lori',
        'file' => 'navirou.3.zspr',
        'version' => 3,
        'vtversion' => '31.0.6',
        'tags' => [
            0 => 'Monster Hunter',
        ],
    ],
    'ned-flanders.1.zspr' => [
        'name' => 'Ned Flanders',
        'author' => 'JJ0033LL',
        'file' => 'ned-flanders.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.6',
        'tags' => [
            0 => 'Male',
            1 => 'Cartoon',
            2 => 'Simpsons',
        ],
    ],
    'negativelink.1.zspr' => [
        'name' => 'Negative Link',
        'author' => 'iBazly',
        'file' => 'negativelink.1.zspr',
        'version' => 1,
        'vtversion' => '27',
        'permitted' => [
            0 => 'ALttPR'
        ],
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'neosad.2.zspr' => [
        'name' => 'Neosad',
        'author' => 'Dr. Deadrewski',
        'file' => 'neosad.2.zspr',
        'version' => 2,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Personality',
            1 => 'Streamer',
        ],
    ],
    'neslink.2.zspr' => [
        'name' => 'NES Link',
        'author' => 'Mike Trethewey/kan',
        'file' => 'neslink.2.zspr',
        'version' => 2,
        'vtversion' => '29',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'ness.2.zspr' => [
        'name' => 'Ness',
        'author' => 'Lantis',
        'file' => 'ness.2.zspr',
        'version' => 2,
        'vtversion' => '30',
        'tags' => [
            0 => 'Male',
            1 => 'Earthbound',
        ],
    ],
    'nia.1.zspr' => [
        'name' => 'Nia',
        'author' => 'Mojonbo',
        'file' => 'nia.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Xenoblade',
            1 => 'Female',
        ],
    ],
    'niddraig.1.zspr' => [
        'name' => 'Niddraig',
        'author' => 'Jakebob',
        'file' => 'niddraig.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.7',
        'tags' => [
            0 => 'Final Fantasy',
            1 => 'Personality',
        ],
    ],
    'niko.1.zspr' => [
        'name' => 'Niko',
        'author' => 'ScatlinkSean',
        'file' => 'niko.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'OneShot',
            1 => 'Cat',
        ],
    ],
    'oldman.2.zspr' => [
        'name' => 'Old Man',
        'author' => 'Zarby89',
        'file' => 'oldman.2.zspr',
        'version' => 2,
        'vtversion' => '25',
        'tags' => [
            0 => 'ALTTP NPC',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'ori.2.zspr' => [
        'name' => 'Ori',
        'author' => 'Phant',
        'file' => 'ori.2.zspr',
        'version' => 2,
        'vtversion' => '30',
        'tags' => [
            0 => 'Ori',
            1 => 'Male',
        ],
    ],
    'outlinelink.1.zspr' => [
        'name' => 'Outline Link',
        'author' => 'VT',
        'file' => 'outlinelink.1.zspr',
        'version' => 1,
        'vtversion' => '26.2',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'parallelworldslink.1.zspr' => [
        'name' => 'Parallel Worlds Link',
        'author' => 'SePH/InTheBeef',
        'file' => 'parallelworldslink.1.zspr',
        'version' => 1,
        'vtversion' => '30',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'paula.1.zspr' => [
        'name' => 'Paula',
        'author' => 'Fish_waffle64',
        'file' => 'paula.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Earthbound',
            1 => 'Female',
        ],
    ],
    'peach.1.zspr' => [
        'name' => 'Princess Peach',
        'author' => 'RoPan',
        'file' => 'peach.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Mario',
            1 => 'Princess',
            2 => 'Female',
        ],
    ],
    'penguinlink.2.zspr' => [
        'name' => 'Penguin Link',
        'author' => 'Fish_waffle64',
        'file' => 'penguinlink.2.zspr',
        'version' => 2,
        'vtversion' => '28',
        'tags' => [
            0 => 'Link',
            1 => 'Animal',
        ],
    ],
    'pete.2.zspr' => [
        'name' => 'Pete',
        'author' => 'Lantis',
        'file' => 'pete.2.zspr',
        'version' => 2,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Male',
            1 => 'Harvest Moon',
        ],
    ],
    'phoenix-wright.1.zspr' => [
        'name' => 'Phoenix Wright',
        'author' => 'SnipSlum',
        'file' => 'phoenix-wright.1.zspr',
        'version' => 1,
        'vtversion' => '30',
        'tags' => [
            0 => 'Male',
            1 => 'Ace Attorney',
        ],
    ],
    'pikachu.2.zspr' => [
        'name' => 'Pikachu',
        'author' => 't0uchan',
        'file' => 'pikachu.2.zspr',
        'version' => 2,
        'vtversion' => '29',
        'tags' => [
            0 => 'Pokemon',
        ],
    ],
    'pinkribbonlink.3.zspr' => [
        'name' => 'Pink Ribbon Link',
        'author' => 'kan',
        'file' => 'pinkribbonlink.3.zspr',
        'version' => 3,
        'vtversion' => '27',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'piranha_plant.1.zspr' => [
        'name' => 'Piranha Plant',
        'author' => 'lecremateur',
        'file' => 'piranha_plant.1.zspr',
        'version' => 1,
        'vtversion' => '31',
        'tags' => [
            0 => 'Mario',
            1 => 'Villain',
        ],
    ],
    'plagueknight.1.zspr' => [
        'name' => 'Plague Knight',
        'author' => 'Jenichi',
        'file' => 'plagueknight.1.zspr',
        'version' => 1,
        'vtversion' => '30',
        'tags' => [
            0 => 'Shovel Knight',
            1 => 'Male',
        ],
    ],
    'pokey.2.zspr' => [
        'name' => 'Pokey',
        'author' => 'kan',
        'file' => 'pokey.2.zspr',
        'version' => 2,
        'vtversion' => '30',
        'tags' => [
            0 => 'ALTTP NPC',
            1 => 'Legend of Zelda',
        ],
    ],
    'popoi.1.zspr' => [
        'name' => 'Popoi',
        'author' => 'ItsSupercar',
        'file' => 'popoi.1.zspr',
        'version' => 1,
        'vtversion' => '27',
        'tags' => [
            0 => 'Secret of Mana',
            1 => 'Male',
        ],
    ],
    'poppy.1.zspr' => [
        'name' => 'Poppy',
        'author' => 'cbass601',
        'file' => 'poppy.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Trolls',
            1 => 'Female',
        ],
    ],
    'porg_knight.1.zspr' => [
        'name' => 'Porg Knight',
        'author' => 'PorgCollector',
        'file' => 'porg_knight.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Star Wars',
        ],
    ],
    'powerpuff_girl.1.zspr' => [
        'name' => 'Powerpuff Girl',
        'author' => 'Jenichi',
        'file' => 'powerpuff_girl.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Female',
            1 => 'Superhero',
            2 => 'Powerpuff Girls',
            3 => 'Cartoon Network',
        ],
    ],
    'pridelink.2.zspr' => [
        'name' => 'Pride Link',
        'author' => 'proximitysound',
        'file' => 'pridelink.2.zspr',
        'version' => 2,
        'vtversion' => '30',
        'permitted' => [
            0 => 'ALttPR'
        ],
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
            3 => 'Pride',
        ],
    ],
    'primm.1.zspr' => [
        'name' => 'Primm',
        'author' => 'Artheau',
        'file' => 'primm.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'demonetized' => true,
        'tags' => [
            0 => 'Secret of Mana',
            1 => 'Female',
        ],
    ],
    'princess_bubblegum.1.zspr' => [
        'name' => 'Princess Bubblegum',
        'author' => 'Devan2002',
        'file' => 'princess_bubblegum.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Female',
            1 => 'Cartoon Network',
        ],
    ],
    'psyduck.2.zspr' => [
        'name' => 'Psyduck',
        'author' => 'skovacs1',
        'file' => 'psyduck.2.zspr',
        'version' => 2,
        'vtversion' => '30',
        'tags' => [
            0 => 'Pokemon',
        ],
    ],
    'pug.1.zspr' => [
        'name' => 'The Pug',
        'author' => 'Achy',
        'file' => 'pug.1.zspr',
        'version' => 1,
        'vtversion' => '26.2',
        'tags' => [
            0 => 'Personality',
            1 => 'Animal',
            2 => 'Streamer',
            3 => 'Male',
        ],
    ],
    'purplechest-bottle.1.zspr' => [
        'name' => 'Purple Chest',
        'author' => 'Mike Trethewey',
        'file' => 'purplechest-bottle.1.zspr',
        'version' => 1,
        'vtversion' => '26',
        'tags' => [
            0 => 'ALTTP NPC',
            1 => 'Legend of Zelda',
        ],
    ],
    'pyro.1.zspr' => [
        'name' => 'Pyro',
        'author' => 'malmo',
        'file' => 'pyro.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Team Fortress',
            1 => 'Male',
        ],
    ],
    'rainbowlink.2.zspr' => [
        'name' => 'Rainbow Link',
        'author' => 'kan',
        'file' => 'rainbowlink.2.zspr',
        'version' => 2,
        'vtversion' => '30',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'rat.1.zspr' => [
        'name' => 'Rat',
        'author' => 'atth3h3art0fwinter',
        'file' => 'rat.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.7',
        'tags' => [
            0 => 'ALTTP NPC',
            1 => 'Legend of Zelda',
        ],
    ],
    'red-mage.1.zspr' => [
        'name' => 'Red Mage',
        'author' => 'TheRedMage',
        'file' => 'red-mage.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.7',
        'tags' => [
            0 => 'Final Fantasy',
        ],
    ],
    'remeer.1.zspr' => [
        'name' => 'Remeer',
        'author' => 'Herowho',
        'file' => 'remeer.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Brain Lord',
            1 => 'Male',
        ],
    ],
    'rick.2.zspr' => [
        'name' => 'Rick',
        'author' => 'Eric the Terrible/Devan 2002',
        'file' => 'rick.2.zspr',
        'version' => 2,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Male',
            1 => 'Cartoon Network',
        ],
    ],
    'robotlink.2.zspr' => [
        'name' => 'Robo-Link 9000',
        'author' => 'kan',
        'file' => 'robotlink.2.zspr',
        'version' => 2,
        'vtversion' => '28',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'rocko.2.zspr' => [
        'name' => 'Rocko',
        'author' => 't0uchan',
        'file' => 'rocko.2.zspr',
        'version' => 2,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Male',
            1 => 'Nickelodeon',
        ],
    ],
    'rottytops.1.zspr' => [
        'name' => 'Rottytops',
        'author' => 'PlaguedOne',
        'file' => 'rottytops.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'demonetized' => true,
        'tags' => [
            0 => 'Cartoon',
        ],
    ],
    'rover.1.zspr' => [
        'name' => 'Rover',
        'author' => 'NO Body the Dragon',
        'file' => 'rover.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.7',
        'demonetized' => true,
        'tags' => [
            0 => 'Male',
            1 => 'Animal Crossing',
            2 => 'Cat',
        ],
    ],
    'roykoopa.1.zspr' => [
        'name' => 'Roy Koopa',
        'author' => 'Achy',
        'file' => 'roykoopa.1.zspr',
        'version' => 1,
        'vtversion' => '26',
        'tags' => [
            0 => 'Male',
            1 => 'Mario',
        ],
    ],
    'rumia.1.zspr' => [
        'name' => 'Rumia',
        'author' => 'Achy',
        'file' => 'rumia.1.zspr',
        'version' => 1,
        'vtversion' => '25',
        'tags' => [
            0 => 'Touhou Project',
            1 => 'Female',
        ],
    ],
    'rydia.1.zspr' => [
        'name' => 'Rydia',
        'author' => 'Sho',
        'file' => 'rydia.1.zspr',
        'version' => 1,
        'vtversion' => '31',
        'tags' => [
            0 => 'Final Fantasy',
            1 => 'Female',
        ],
    ],
    'ryu.1.zspr' => [
        'name' => 'Ryu',
        'author' => 'PlaguedOne',
        'file' => 'ryu.1.zspr',
        'version' => 1,
        'vtversion' => '30',
        'demonetized' => true,
        'tags' => [
            0 => 'Male',
            1 => 'Street Fighter',
        ],
    ],
    'sailormoon.1.zspr' => [
        'name' => 'Sailor Moon',
        'author' => 'Jenichi',
        'file' => 'sailormoon.1.zspr',
        'version' => 1,
        'vtversion' => '30',
        'tags' => [
            0 => 'Sailor Moon',
            1 => 'Female',
            2 => 'Cartoon',
        ],
    ],
    'saitama.2.zspr' => [
        'name' => 'Saitama',
        'author' => 'Dabeanjelly/Ath3h3art0fwinter',
        'file' => 'saitama.2.zspr',
        'version' => 2,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Male',
            1 => 'Superhero',
        ],
    ],
    'samus-sm.1.zspr' => [
        'name' => 'Samus (Super Metroid)',
        'author' => 'Ben G',
        'file' => 'samus-sm.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Metroid',
            1 => 'Female',
        ],
    ],
    'samus.2.zspr' => [
        'name' => 'Samus',
        'author' => 'Fish_waffle64',
        'file' => 'samus.2.zspr',
        'version' => 2,
        'vtversion' => '30',
        'tags' => [
            0 => 'Metroid',
            1 => 'Female',
        ],
    ],
    'samus_classic.1.zspr' => [
        'name' => 'Samus (Classic)',
        'author' => 'Fish_waffle64',
        'file' => 'samus_classic.1.zspr',
        'version' => 1,
        'vtversion' => '25',
        'tags' => [
            0 => 'Metroid',
            1 => 'Female',
        ],
    ],
    'santalink.2.zspr' => [
        'name' => 'Santa Link',
        'author' => 'HOHOHO',
        'file' => 'santalink.2.zspr',
        'version' => 2,
        'vtversion' => '26',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
            3 => 'Festive',
        ],
    ],
    'scholar.1.zspr' => [
        'name' => 'Scholar',
        'author' => 'Damon',
        'file' => 'scholar.1.zspr',
        'version' => 1,
        'vtversion' => '30',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
        ],
    ],
    'selan.2.zspr' => [
        'name' => 'Selan',
        'author' => 'atth3h3art0fwinter',
        'file' => 'selan.2.zspr',
        'version' => 2,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Lufia',
            1 => 'Female',
        ],
    ],
    'sevens1ns.1.zspr' => [
        'name' => 'SevenS1ns',
        'author' => 'Hroun',
        'file' => 'sevens1ns.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Personality',
            1 => 'Streamer',
            2 => 'Male',
        ],
    ],
    'shadow.1.zspr' => [
        'name' => 'Shadow',
        'author' => 'CGG Zayik',
        'file' => 'shadow.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Final Fantasy',
            1 => 'Male',
        ],
    ],
    'shadowsaku.2.zspr' => [
        'name' => 'Shadow Sakura',
        'author' => 'iBazly',
        'file' => 'shadowsaku.2.zspr',
        'version' => 2,
        'vtversion' => '27',
        'permitted' => [
            0 => 'ALttPR'
        ],
        'tags' => [
            0 => 'Personality',
            1 => 'Streamer',
            2 => 'Female',
        ],
    ],
    'shantae.1.zspr' => [
        'name' => 'Shantae',
        'author' => 'skovacs1',
        'file' => 'shantae.1.zspr',
        'version' => 1,
        'vtversion' => '30',
        'tags' => [
            0 => 'Shantae',
            1 => 'Female',
        ],
    ],
    'shuppet.2.zspr' => [
        'name' => 'Shuppet',
        'author' => 'kan',
        'file' => 'shuppet.2.zspr',
        'version' => 2,
        'vtversion' => '30',
        'tags' => [
            0 => 'Pokemon',
            1 => 'Ghost',
        ],
    ],
    'shy-gal.1.zspr' => [
        'name' => 'Shy Gal',
        'author' => 'FedoraFriday',
        'file' => 'shy-gal.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.6',
        'tags' => [
            0 => 'Mario',
            1 => 'Female',
        ],
    ],
    'shy-guy.1.zspr' => [
        'name' => 'Shy Guy',
        'author' => 'skovacs1',
        'file' => 'shy-guy.1.zspr',
        'version' => 1,
        'vtversion' => '30',
        'tags' => [
            0 => 'Mario',
        ],
    ],
    'sighn_waive.1.zspr' => [
        'name' => 'SighnWaive',
        'author' => 'GenoCL',
        'file' => 'sighn_waive.1.zspr',
        'version' => 1,
        'vtversion' => '31',
        'tags' => [
            0 => 'Personality',
        ],
    ],
    'slime.1.zspr' => [
        'name' => 'Slime',
        'author' => 'KamenRideDecade',
        'file' => 'slime.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.7',
        'tags' => [
            0 => 'Dragon Quest',
        ],
    ],
    'slowpoke.2.zspr' => [
        'name' => 'Slowpoke',
        'author' => 'Joey_Rat',
        'file' => 'slowpoke.2.zspr',
        'version' => 2,
        'vtversion' => '31.0.7',
        'tags' => [
            0 => 'Pokemon',
        ],
    ],
    'snes-controller.2.zspr' => [
        'name' => 'SNES Controller',
        'author' => 'cbass601',
        'file' => 'snes-controller.2.zspr',
        'version' => 2,
        'vtversion' => '30',
        'tags' => [
            0 => 'SNES',
        ],
    ],
    'sodacan.1.zspr' => [
        'name' => 'Soda Can',
        'author' => 'Zarby89',
        'file' => 'sodacan.1.zspr',
        'version' => 1,
        'vtversion' => '27',
        'tags' => [
            0 => 'Sprite',
            1 => 'Tasty',
            2 => 'IRL',
        ],
    ],
    'solaire.1.zspr' => [
        'name' => 'Solaire of Astora',
        'author' => 'Knilip',
        'file' => 'solaire.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Dark Souls',
            1 => 'Male',
        ],
    ],
    'soldiersprite.1.zspr' => [
        'name' => 'Hyrule Soldier',
        'author' => 'InTheBeef',
        'file' => 'soldiersprite.1.zspr',
        'version' => 1,
        'vtversion' => '29',
        'tags' => [
            0 => 'Legend of Zelda',
            1 => 'ALTTP NPC',
        ],
    ],
    'sonic.1.zspr' => [
        'name' => 'Sonic the Hedgehog',
        'author' => 'Osaka',
        'file' => 'sonic.1.zspr',
        'version' => 1,
        'vtversion' => '28',
        'tags' => [
            0 => 'Male',
            1 => 'Sonic the Hedgehog',
        ],
    ],
    'sora.1.zspr' => [
        'name' => 'Sora',
        'author' => 'roxas232',
        'file' => 'sora.1.zspr',
        'version' => 1,
        'vtversion' => '28',
        'tags' => [
            0 => 'Male',
            1 => 'Kingdom Hearts',
        ],
    ],
    'sora_kh1.1.zspr' => [
        'name' => 'Sora (KH1)',
        'author' => 'ScatlinkSean',
        'file' => 'sora_kh1.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Male',
            1 => 'Kingdom Hearts',
        ],
    ],
    'spongebob.1.zspr' => [
        'name' => 'Spongebob Squarepants',
        'author' => 'JJ0033LL',
        'file' => 'spongebob.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.7',
        'tags' => [
            0 => 'Male',
            1 => 'Spongebob Squarepants',
        ],
    ],
    'squall.1.zspr' => [
        'name' => 'Squall',
        'author' => 'Maessan',
        'file' => 'squall.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Male',
            1 => 'Final Fantasy',
        ],
    ],
    'squirrel.1.zspr' => [
        'name' => 'Squirrel',
        'author' => 'Fish_waffle64',
        'file' => 'squirrel.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Animal',
            1 => 'Personality',
            2 => 'Streamer',
        ],
    ],
    'squirtle.1.zspr' => [
        'name' => 'Squirtle',
        'author' => 'Numberplay',
        'file' => 'squirtle.1.zspr',
        'version' => 1,
        'vtversion' => '29',
        'tags' => [
            0 => 'Pokemon',
        ],
    ],
    'stalfos.1.zspr' => [
        'name' => 'Stalfos',
        'author' => 'Artheau',
        'file' => 'stalfos.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'demonetized' => true,
        'tags' => [
            0 => 'ALTTP NPC',
            1 => 'Legend of Zelda',
        ],
    ],
    'stan.2.zspr' => [
        'name' => 'Stan',
        'author' => 'kan',
        'file' => 'stan.2.zspr',
        'version' => 2,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Male',
            1 => 'Okage: Shadow King',
        ],
    ],
    'staticlink.2.zspr' => [
        'name' => 'Static Link',
        'author' => 'kan',
        'file' => 'staticlink.2.zspr',
        'version' => 2,
        'vtversion' => '27',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
            3 => 'Randomizer',
        ],
    ],
    'steamedhams.1.zspr' => [
        'name' => 'Steamed Hams',
        'author' => 'AFewGoodTaters',
        'file' => 'steamedhams.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.7',
        'tags' => [
            0 => 'Link',
            1 => 'Cartoon',
        ],
    ],
    'stick_man.1.zspr' => [
        'name' => 'Stick Man',
        'author' => 'skovacs1',
        'file' => 'stick_man.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Personality',
        ],
    ],
    'superbomb.1.zspr' => [
        'name' => 'Super Bomb',
        'author' => 'Ninjakauz',
        'file' => 'superbomb.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'ALTTP NPC',
            1 => 'Legend of Zelda',
        ],
    ],
    'superbunny.2.zspr' => [
        'name' => 'Super Bunny',
        'author' => 'TheOkayGuy',
        'file' => 'superbunny.2.zspr',
        'version' => 2,
        'vtversion' => '25',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'supermeatboy.1.zspr' => [
        'name' => 'Super Meat Boy',
        'author' => 'Achy',
        'file' => 'supermeatboy.1.zspr',
        'version' => 1,
        'vtversion' => '29',
        'tags' => [
            0 => 'Male',
            1 => 'Meat Boy',
        ],
    ],
    'susie.1.zspr' => [
        'name' => 'Susie',
        'author' => 'Zandra',
        'file' => 'susie.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.7',
        'tags' => [
            0 => 'Female',
            1 => 'Undertale',
            2 => 'Deltarune',
        ],
    ],
    'swatchy.1.zspr' => [
        'name' => 'Swatchy',
        'author' => 'Mike Trethewey',
        'file' => 'swatchy.1.zspr',
        'version' => 1,
        'vtversion' => '25',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'tasbot.1.zspr' => [
        'name' => 'TASBot',
        'author' => 'GenoCL',
        'file' => 'tasbot.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Personality',
        ],
    ],
    'teatime.1.zspr' => [
        'name' => 'Tea Time',
        'author' => 'SirCzah',
        'file' => 'teatime.1.zspr',
        'version' => 1,
        'vtversion' => '30',
        'tags' => [
            0 => 'Personality',
            1 => 'Streamer',
        ],
    ],
    'terra.1.zspr' => [
        'name' => 'Terra (Esper)',
        'author' => 'All-in-one Mighty',
        'file' => 'terra.1.zspr',
        'version' => 1,
        'vtversion' => '29',
        'tags' => [
            0 => 'Final Fantasy',
            1 => 'Female',
        ],
    ],
    'tetra.1.zspr' => [
        'name' => 'Tetra',
        'author' => 'Ferelheart',
        'file' => 'tetra.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Legend of Zelda',
            1 => 'Female',
        ],
    ],
    'tgh.1.zspr' => [
        'name' => 'TGH',
        'author' => 'Drew Wise, pizza_for_free',
        'file' => 'tgh.1.zspr',
        'version' => 1,
        'vtversion' => '31',
        'tags' => [
            0 => 'Personality',
            1 => 'Streamer',
            2 => 'Male',
        ],
    ],
    'thief.1.zspr' => [
        'name' => 'Thief',
        'author' => 'Devan2002',
        'file' => 'thief.1.zspr',
        'version' => 1,
        'vtversion' => '30',
        'tags' => [
            0 => 'ALTTP NPC',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'thomcrow.1.zspr' => [
        'name' => 'Thomcrow',
        'author' => 'Thom',
        'file' => 'thomcrow.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Personality',
            1 => 'Streamer',
            2 => 'Male',
            3 => 'Bird',
        ],
    ],
    'tile.3.zspr' => [
        'name' => 'Tile',
        'author' => 'kan',
        'file' => 'tile.3.zspr',
        'version' => 3,
        'vtversion' => '28',
        'tags' => [
            0 => 'ALTTP NPC',
            1 => 'Legend of Zelda',
        ],
    ],
    'tingle.1.zspr' => [
        'name' => 'Tingle',
        'author' => 'Xenobond',
        'file' => 'tingle.1.zspr',
        'version' => 1,
        'vtversion' => '27',
        'tags' => [
            0 => 'Legend of Zelda',
            1 => 'Male',
        ],
    ],
    'tmnt.1.zspr' => [
        'name' => 'TMNT',
        'author' => 'SirCzah',
        'file' => 'tmnt.1.zspr',
        'version' => 1,
        'vtversion' => '30',
        'tags' => [
            0 => 'Animal',
            1 => 'Male',
            2 => 'Cartoon',
        ],
    ],
    'toad.2.zspr' => [
        'name' => 'Toad',
        'author' => 'Zarby89',
        'file' => 'toad.2.zspr',
        'version' => 2,
        'vtversion' => '25',
        'tags' => [
            0 => 'Male',
            1 => 'Mario',
        ],
    ],
    'toadette.2.zspr' => [
        'name' => 'Toadette',
        'author' => 'Devan2002',
        'file' => 'toadette.2.zspr',
        'version' => 2,
        'vtversion' => '30',
        'tags' => [
            0 => 'Female',
            1 => 'Mario',
        ],
    ],
    'toadette_captain.1.zspr' => [
        'name' => 'Captain Toadette',
        'author' => 'Devan2002',
        'file' => 'toadette_captain.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Female',
            1 => 'Mario',
        ],
    ],
    'totem-links.1.zspr' => [
        'name' => 'TotemLinks',
        'author' => 'Yotohan',
        'file' => 'totem-links.1.zspr',
        'version' => 1,
        'vtversion' => '30',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'trogdor.2.zspr' => [
        'name' => 'Trogdor the Burninator',
        'author' => 'Mike Trethewey/kan',
        'file' => 'trogdor.2.zspr',
        'version' => 2,
        'vtversion' => '29',
        'tags' => [
            0 => 'Male',
        ],
    ],
    'twilightprincesszelda.2.zspr' => [
        'name' => 'TP Zelda',
        'author' => 'Fish_waffle64',
        'file' => 'twilightprincesszelda.2.zspr',
        'version' => 2,
        'vtversion' => '28',
        'tags' => [
            0 => 'Legend of Zelda',
            1 => 'Female',
        ],
    ],
    'two_faced.2.zspr' => [
        'name' => 'TwoFaced',
        'author' => 'Devan2002',
        'file' => 'two_faced.2.zspr',
        'version' => 2,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Personality',
        ],
    ],
    'ty.1.zspr' => [
        'name' => 'Ty the Tasmanian Tiger',
        'author' => 'Fish_waffle64',
        'file' => 'ty.1.zspr',
        'version' => 1,
        'vtversion' => '31',
        'tags' => [
            0 => 'Animal',
            1 => 'Ty the Tasmanian Tiger',
        ],
    ],
    'ultros.1.zspr' => [
        'name' => 'Ultros',
        'author' => 'PlaguedOne',
        'file' => 'ultros.1.zspr',
        'version' => 1,
        'vtversion' => '30',
        'demonetized' => true,
        'tags' => [
            0 => 'Final Fantasy',
        ],
    ],
    'valeera.1.zspr' => [
        'name' => 'Valeera',
        'author' => 'Glan',
        'file' => 'valeera.1.zspr',
        'version' => 1,
        'vtversion' => '27',
        'tags' => [
            0 => 'Warcraft',
            1 => 'Female',
        ],
    ],
    'vanillalink.1.zspr' => [
        'name' => 'VanillaLink',
        'author' => 'Jenichi',
        'file' => 'vanillalink.1.zspr',
        'version' => 1,
        'vtversion' => '30',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
        ],
    ],
    'vaporeon.1.zspr' => [
        'name' => 'Vaporeon',
        'author' => 'Aquana',
        'file' => 'vaporeon.1.zspr',
        'version' => 1,
        'vtversion' => '31',
        'tags' => [
            0 => 'Pokemon',
        ],
    ],
    'vegeta.1.zspr' => [
        'name' => 'Vegeta',
        'author' => 'Merciter',
        'file' => 'vegeta.1.zspr',
        'version' => 1,
        'vtversion' => '31',
        'tags' => [
            0 => 'Male',
            1 => 'Dragonball',
        ],
    ],
    'vera.1.zspr' => [
        'name' => 'Vera',
        'author' => 'aitchFactor',
        'file' => 'vera.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Personality',
        ],
    ],
    'vitreous.1.zspr' => [
        'name' => 'Vitreous',
        'author' => 'Glan',
        'file' => 'vitreous.1.zspr',
        'version' => 1,
        'vtversion' => '27',
        'tags' => [
            0 => 'ALTTP NPC',
            1 => 'Legend of Zelda',
            2 => 'Boss',
        ],
    ],
    'vivi.1.zspr' => [
        'name' => 'Vivi',
        'author' => 'RyuTech',
        'file' => 'vivi.1.zspr',
        'version' => 1,
        'vtversion' => '27',
        'tags' => [
            0 => 'Final Fantasy',
            1 => 'Male',
        ],
    ],
    'vivian.1.zspr' => [
        'name' => 'Vivian',
        'author' => 'SirCzah',
        'file' => 'vivian.1.zspr',
        'version' => 1,
        'vtversion' => '30',
        'tags' => [
            0 => 'Mario',
            1 => 'Female',
        ],
    ],
    'wario.1.zspr' => [
        'name' => 'Wario',
        'author' => 'Deagans',
        'file' => 'wario.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Male',
            1 => 'Mario',
            2 => 'Villain',
        ],
    ],
    'will.1.zspr' => [
        'name' => 'Will',
        'author' => 'Xenobond',
        'file' => 'will.1.zspr',
        'version' => 1,
        'vtversion' => '27',
        'tags' => [
            0 => 'Illusion of Gaia',
            1 => 'Male',
        ],
    ],
    'wizzrobe.2.zspr' => [
        'name' => 'Wizzrobe',
        'author' => 'iBazly',
        'file' => 'wizzrobe.2.zspr',
        'version' => 2,
        'vtversion' => '25',
        'permitted' => [
            0 => 'ALttPR'
        ],
        'tags' => [
            0 => 'ALTTP NPC',
            1 => 'Legend of Zelda',
        ],
    ],
    'wolf_link.1.zspr' => [
        'name' => 'Wolf Link (Festive)',
        'author' => 'Fish/Beef-Chan',
        'file' => 'wolf_link.1.zspr',
        'version' => 1,
        'vtversion' => '31',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
            3 => 'Animal',
            4 => 'Festive',
        ],
    ],
    'wolf_link_tp.1.zspr' => [
        'name' => 'Wolf Link (TP)',
        'author' => 'Gfish59',
        'file' => 'wolf_link_tp.1.zspr',
        'version' => 1,
        'vtversion' => '31',
        'tags' => [
            0 => 'Link',
            1 => 'Male',
            2 => 'Legend of Zelda',
            3 => 'Animal',
        ],
    ],
    'yoshi.1.zspr' => [
        'name' => 'Yoshi',
        'author' => 'Yotohan',
        'file' => 'yoshi.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Mario',
        ],
    ],
    'yunica.2.zspr' => [
        'name' => 'Yunica Tovah',
        'author' => 'Fish_waffle64',
        'file' => 'yunica.2.zspr',
        'version' => 2,
        'vtversion' => '27',
        'tags' => [
            0 => 'Female',
            1 => 'Ys',
        ],
    ],
    'zandra.2.zspr' => [
        'name' => 'Zandra',
        'author' => 'ZandraVandra',
        'file' => 'zandra.2.zspr',
        'version' => 2,
        'vtversion' => '30',
        'tags' => [
            0 => 'Personality',
            1 => 'Streamer',
            2 => 'Female',
        ],
    ],
    'zebraunicorn.1.zspr' => [
        'name' => 'Zebra Unicorn',
        'author' => 'Brass Man',
        'file' => 'zebraunicorn.1.zspr',
        'version' => 1,
        'vtversion' => '30.5',
        'tags' => [
            0 => 'Animal',
            1 => 'Personlity',
            2 => 'Streamer',
        ],
    ],
    'zeck.1.zspr' => [
        'name' => 'Zeckemyro',
        'author' => 'aitchFactor',
        'file' => 'zeck.1.zspr',
        'version' => 1,
        'vtversion' => '31.0.5',
        'tags' => [
            0 => 'Personality',
        ],
    ],
    'zelda.1.zspr' => [
        'name' => 'Zelda',
        'author' => 'Myriachan',
        'file' => 'zelda.1.zspr',
        'version' => 1,
        'vtversion' => '25',
        'tags' => [
            0 => 'ALTTP NPC',
            1 => 'Female',
            2 => 'Legend of Zelda',
        ],
    ],
    'zerosuitsamus.2.zspr' => [
        'name' => 'Zero Suit Samus',
        'author' => 'Fish_waffle64',
        'file' => 'zerosuitsamus.2.zspr',
        'version' => 2,
        'vtversion' => '30',
        'tags' => [
            0 => 'Metroid',
            1 => 'Female',
        ],
    ],
    'zora.2.zspr' => [
        'name' => 'Zora',
        'author' => 'Zarby, InTheBeef',
        'file' => 'zora.2.zspr',
        'version' => 2,
        'vtversion' => '25',
        'tags' => [
            0 => 'ALTTP NPC',
            1 => 'Legend of Zelda',
        ],
    ],
];
