<?php

declare(strict_types=1);

namespace Tests\Unit\Logic\Standard\MajorGlitches;

use App\Graph\Randomizer;
use Tests\TestCase;

/**
 * @group graph
 * @group Standard
 * @group MajorGlitches
 */
final class MiseryMireTest extends TestCase
{
    /**
     * @param string $location
     * @param bool $access
     * @param array $items
     *
     * @dataProvider accessPool
     */
    public function testLocation(string $location, bool $access, array $items): void
    {
        $randomizer = new Randomizer([[
            'mode.state' => 'standard',
            'difficulty' => 'test_rules',
            'tech' => config('logic.major_glitches'),
            'logic' => 'MajorGlitches',
        ]]);
        $randomizer->assumeItems(array_merge(['MireEntryEther:0'], array_map(fn ($i) => "$i:0", $items)));
        $this->assertEquals($access, $randomizer->canReachLocation("$location:0"));
    }

    public function accessPool(): array
    {
        return [
            ["Misery Mire - Big Chest", false, []],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'Ether', 'MasterSword', 'PegasusBoots']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'Ether', 'MasterSword', 'Hookshot']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'Ether', 'L3Sword', 'PegasusBoots']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'Ether', 'L3Sword', 'Hookshot']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'Ether', 'L4Sword', 'PegasusBoots']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'MoonPearl', 'Ether', 'L4Sword', 'Hookshot']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'Bottle', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'Bottle', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'Bottle', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'Bottle', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'Bottle', 'Ether', 'MasterSword', 'PegasusBoots']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'Bottle', 'Ether', 'MasterSword', 'Hookshot']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'Bottle', 'Ether', 'L3Sword', 'PegasusBoots']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'Bottle', 'Ether', 'L3Sword', 'Hookshot']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'Bottle', 'Ether', 'L4Sword', 'PegasusBoots']],
            ["Misery Mire - Big Chest", true, ['BigKeyD6', 'Bottle', 'Ether', 'L4Sword', 'Hookshot']],

            ["Misery Mire - Main Lobby Chest", false, []],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'Ether', 'MasterSword', 'PegasusBoots']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'Ether', 'MasterSword', 'Hookshot']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'Ether', 'L3Sword', 'PegasusBoots']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'Ether', 'L3Sword', 'Hookshot']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'Ether', 'L4Sword', 'PegasusBoots']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'MoonPearl', 'Ether', 'L4Sword', 'Hookshot']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'Bottle', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'Bottle', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'Bottle', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'Bottle', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'Bottle', 'Ether', 'MasterSword', 'PegasusBoots']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'Bottle', 'Ether', 'MasterSword', 'Hookshot']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'Bottle', 'Ether', 'L3Sword', 'PegasusBoots']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'Bottle', 'Ether', 'L3Sword', 'Hookshot']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'Bottle', 'Ether', 'L4Sword', 'PegasusBoots']],
            ["Misery Mire - Main Lobby Chest", true, ['KeyD6', 'Bottle', 'Ether', 'L4Sword', 'Hookshot']],

            ["Misery Mire - Big Key Chest", false, []],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'Ether', 'MasterSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'Ether', 'MasterSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'Ether', 'L3Sword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'Ether', 'L3Sword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'Ether', 'L4Sword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'Ether', 'L4Sword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'Ether', 'MasterSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'Ether', 'MasterSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'Ether', 'L3Sword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'Ether', 'L3Sword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'Ether', 'L4Sword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'Ether', 'L4Sword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'Bottle', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'Bottle', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'Bottle', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'Bottle', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'Bottle', 'Ether', 'MasterSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'Bottle', 'Ether', 'MasterSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'Bottle', 'Ether', 'L3Sword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'Bottle', 'Ether', 'L3Sword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'Bottle', 'Ether', 'L4Sword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'Bottle', 'Ether', 'L4Sword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'Bottle', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'Bottle', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'Bottle', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'Bottle', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'Bottle', 'Ether', 'MasterSword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'Bottle', 'Ether', 'MasterSword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'Bottle', 'Ether', 'L3Sword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'Bottle', 'Ether', 'L3Sword', 'Hookshot']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'Bottle', 'Ether', 'L4Sword', 'PegasusBoots']],
            ["Misery Mire - Big Key Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'Bottle', 'Ether', 'L4Sword', 'Hookshot']],

            ["Misery Mire - Compass Chest", false, []],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'Ether', 'MasterSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'Ether', 'MasterSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'Ether', 'L3Sword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'Ether', 'L3Sword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'Ether', 'L4Sword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'MoonPearl', 'Ether', 'L4Sword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'Ether', 'MasterSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'Ether', 'MasterSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'Ether', 'L3Sword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'Ether', 'L3Sword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'Ether', 'L4Sword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'MoonPearl', 'Ether', 'L4Sword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'Bottle', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'Bottle', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'Bottle', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'Bottle', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'Bottle', 'Ether', 'MasterSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'Bottle', 'Ether', 'MasterSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'Bottle', 'Ether', 'L3Sword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'Bottle', 'Ether', 'L3Sword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'Bottle', 'Ether', 'L4Sword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'Lamp', 'Bottle', 'Ether', 'L4Sword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'Bottle', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'Bottle', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'Bottle', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'Bottle', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'Bottle', 'Ether', 'MasterSword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'Bottle', 'Ether', 'MasterSword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'Bottle', 'Ether', 'L3Sword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'Bottle', 'Ether', 'L3Sword', 'Hookshot']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'Bottle', 'Ether', 'L4Sword', 'PegasusBoots']],
            ["Misery Mire - Compass Chest", true, ['KeyD6', 'KeyD6', 'KeyD6', 'FireRod', 'Bottle', 'Ether', 'L4Sword', 'Hookshot']],

            ["Misery Mire - Bridge Chest", false, []],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'Ether', 'MasterSword', 'PegasusBoots']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'Ether', 'MasterSword', 'Hookshot']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'Ether', 'L3Sword', 'PegasusBoots']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'Ether', 'L3Sword', 'Hookshot']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'Ether', 'L4Sword', 'PegasusBoots']],
            ["Misery Mire - Bridge Chest", true, ['MoonPearl', 'Ether', 'L4Sword', 'Hookshot']],
            ["Misery Mire - Bridge Chest", true, ['Bottle', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Bridge Chest", true, ['Bottle', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Bridge Chest", true, ['Bottle', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Bridge Chest", true, ['Bottle', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Bridge Chest", true, ['Bottle', 'Ether', 'MasterSword', 'PegasusBoots']],
            ["Misery Mire - Bridge Chest", true, ['Bottle', 'Ether', 'MasterSword', 'Hookshot']],
            ["Misery Mire - Bridge Chest", true, ['Bottle', 'Ether', 'L3Sword', 'PegasusBoots']],
            ["Misery Mire - Bridge Chest", true, ['Bottle', 'Ether', 'L3Sword', 'Hookshot']],
            ["Misery Mire - Bridge Chest", true, ['Bottle', 'Ether', 'L4Sword', 'PegasusBoots']],
            ["Misery Mire - Bridge Chest", true, ['Bottle', 'Ether', 'L4Sword', 'Hookshot']],

            ["Misery Mire - Map Chest", false, []],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'Ether', 'MasterSword', 'PegasusBoots']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'Ether', 'MasterSword', 'Hookshot']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'Ether', 'L3Sword', 'PegasusBoots']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'Ether', 'L3Sword', 'Hookshot']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'Ether', 'L4Sword', 'PegasusBoots']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'MoonPearl', 'Ether', 'L4Sword', 'Hookshot']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'Bottle', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'Bottle', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'Bottle', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'Bottle', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'Bottle', 'Ether', 'MasterSword', 'PegasusBoots']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'Bottle', 'Ether', 'MasterSword', 'Hookshot']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'Bottle', 'Ether', 'L3Sword', 'PegasusBoots']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'Bottle', 'Ether', 'L3Sword', 'Hookshot']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'Bottle', 'Ether', 'L4Sword', 'PegasusBoots']],
            ["Misery Mire - Map Chest", true, ['KeyD6', 'Bottle', 'Ether', 'L4Sword', 'Hookshot']],

            ["Misery Mire - Spike Chest", false, []],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'Ether', 'MasterSword', 'PegasusBoots']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'Ether', 'MasterSword', 'Hookshot']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'Ether', 'L3Sword', 'PegasusBoots']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'Ether', 'L3Sword', 'Hookshot']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'Ether', 'L4Sword', 'PegasusBoots']],
            ["Misery Mire - Spike Chest", true, ['MoonPearl', 'Ether', 'L4Sword', 'Hookshot']],
            ["Misery Mire - Spike Chest", true, ['Bottle', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Spike Chest", true, ['Bottle', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Spike Chest", true, ['Bottle', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Spike Chest", true, ['Bottle', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Spike Chest", true, ['Bottle', 'Ether', 'MasterSword', 'PegasusBoots']],
            ["Misery Mire - Spike Chest", true, ['Bottle', 'Ether', 'MasterSword', 'Hookshot']],
            ["Misery Mire - Spike Chest", true, ['Bottle', 'Ether', 'L3Sword', 'PegasusBoots']],
            ["Misery Mire - Spike Chest", true, ['Bottle', 'Ether', 'L3Sword', 'Hookshot']],
            ["Misery Mire - Spike Chest", true, ['Bottle', 'Ether', 'L4Sword', 'PegasusBoots']],
            ["Misery Mire - Spike Chest", true, ['Bottle', 'Ether', 'L4Sword', 'Hookshot']],

            ["Misery Mire - Boss", false, []],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'Flute', 'TitansMitt', 'Ether', 'UncleSword', 'PegasusBoots']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'Flute', 'TitansMitt', 'Ether', 'UncleSword', 'Hookshot']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'Flute', 'TitansMitt', 'Ether', 'ProgressiveSword', 'PegasusBoots']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'Flute', 'TitansMitt', 'Ether', 'ProgressiveSword', 'Hookshot']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'Flute', 'TitansMitt', 'Ether', 'MasterSword', 'PegasusBoots']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'Flute', 'TitansMitt', 'Ether', 'MasterSword', 'Hookshot']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'Flute', 'TitansMitt', 'Ether', 'L3Sword', 'PegasusBoots']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'Flute', 'TitansMitt', 'Ether', 'L3Sword', 'Hookshot']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'Flute', 'TitansMitt', 'Ether', 'L4Sword', 'PegasusBoots']],
            ["Misery Mire - Boss", true, ['KeyD6', 'KeyD6', 'BigKeyD6', 'Lamp', 'CaneOfSomaria', 'MoonPearl', 'Flute', 'TitansMitt', 'Ether', 'L4Sword', 'Hookshot']],

        ];
    }
}
