<?php

declare(strict_types=1);

namespace Tests\Unit\Logic\Standard\MajorGlitches;

use App\Graph\Randomizer;
use Tests\TestCase;

/**
 * @group graph
 * @group Standard
 * @group MajorGlitches
 */
final class SwampPalaceTest extends TestCase
{
    /**
     * @param string $location
     * @param bool $access
     * @param array $items
     *
     * @dataProvider accessPool
     */
    public function testLocation(string $location, bool $access, array $items): void
    {
        $this->markTestSkipped();
        $randomizer = new Randomizer([[
            'mode.state' => 'standard',
            'tech' => config('logic.major_glitches'),
            'logic' => 'MajorGlitches',
        ]]);
        $randomizer->assumeItems(array_map(fn ($i) => "$i:0", $items));
        $this->assertEquals($access, $randomizer->canReachLocation("$location:0"));
    }

    public function accessPool(): array
    {
        return [
            ["Swamp Palace - Entrance Chest", false, []],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'MagicMirror', 'MoonPearl']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Entrance Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],

            ["Swamp Palace - Big Chest", false, []],
            ["Swamp Palace - Big Chest", true, ['KeyD2', 'Flippers', 'MagicMirror', 'MoonPearl', 'Hammer', 'BigKeyD2']],
            ["Swamp Palace - Big Chest", true, ['KeyD2', 'Flippers', 'MagicMirror', 'MoonPearl', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],

            ["Swamp Palace - Big Key Chest", false, []],
            ["Swamp Palace - Big Key Chest", true, ['KeyD2', 'Flippers', 'MagicMirror', 'MoonPearl', 'Hammer']],
            ["Swamp Palace - Big Key Chest", true, ['KeyD2', 'Flippers', 'MagicMirror', 'MoonPearl', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Big Key Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],

            ["Swamp Palace - Map Chest", false, []],
            ["Swamp Palace - Map Chest", true, ['KeyD2', 'Flippers', 'MagicMirror', 'MoonPearl']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Map Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],

            ["Swamp Palace - West Chest", false, []],
            ["Swamp Palace - West Chest", true, ['KeyD2', 'Flippers', 'MagicMirror', 'MoonPearl', 'Hammer']],
            ["Swamp Palace - West Chest", true, ['KeyD2', 'Flippers', 'MagicMirror', 'MoonPearl', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - West Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],

            ["Swamp Palace - Compass Chest", false, []],
            ["Swamp Palace - Compass Chest", true, ['KeyD2', 'Flippers', 'MagicMirror', 'MoonPearl', 'Hammer']],
            ["Swamp Palace - Compass Chest", true, ['KeyD2', 'Flippers', 'MagicMirror', 'MoonPearl', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'PegasusBoots', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Compass Chest", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],

            ["Swamp Palace - Flooded Room - Left", false, []],
            ["Swamp Palace - Flooded Room - Left", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'Hammer']],
            ["Swamp Palace - Flooded Room - Left", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Left", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Left", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Left", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Left", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Left", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Left", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Left", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Left", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Left", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Left", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Left", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],

            ["Swamp Palace - Flooded Room - Right", false, []],
            ["Swamp Palace - Flooded Room - Right", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'Hammer']],
            ["Swamp Palace - Flooded Room - Right", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Right", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Right", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Right", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Right", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Right", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Right", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Right", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Right", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Right", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Flooded Room - Right", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Flooded Room - Right", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],

            ["Swamp Palace - Waterfall Room", false, []],
            ["Swamp Palace - Waterfall Room", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'Hammer']],
            ["Swamp Palace - Waterfall Room", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Waterfall Room", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Waterfall Room", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Waterfall Room", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Waterfall Room", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Waterfall Room", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Waterfall Room", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Waterfall Room", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Waterfall Room", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Waterfall Room", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Waterfall Room", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Waterfall Room", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],

            ["Swamp Palace - Boss", false, []],
            ["Swamp Palace - Boss", false, ['Hookshot', 'Flippers', 'MagicMirror', 'MoonPearl', 'KeyD2', 'FireRod', 'IceRod', 'MoonPearl', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'Hammer']],
            ["Swamp Palace - Boss", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'BowAndArrows', 'FireRod', 'MoonPearl', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'HalfMagic', 'FireRod', 'MoonPearl', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'QuarterMagic', 'FireRod', 'MoonPearl', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'FireRod', 'BottleWithBee', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'FireRod', 'BottleWithFairy', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'FireRod', 'BottleWithRedPotion', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'FireRod', 'BottleWithGreenPotion', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'FireRod', 'BottleWithBluePotion', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'FireRod', 'Bottle', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'FireRod', 'BottleWithGoldBee', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'BowAndArrows', 'IceRod', 'MoonPearl', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'HalfMagic', 'IceRod', 'MoonPearl', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'QuarterMagic', 'IceRod', 'MoonPearl', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'IceRod', 'BottleWithBee', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'IceRod', 'BottleWithFairy', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'IceRod', 'BottleWithRedPotion', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'IceRod', 'BottleWithGreenPotion', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'IceRod', 'BottleWithBluePotion', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'IceRod', 'Bottle', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'IceRod', 'BottleWithGoldBee', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'UncleSword', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'ProgressiveSword', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'MasterSword', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'L3Sword', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['KeyD2', 'Flippers', 'Hookshot', 'MagicMirror', 'MoonPearl', 'L4Sword', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Boss", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Boss", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Boss", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Boss", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Boss", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Boss", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Boss", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Boss", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Boss", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyD6']],
            ["Swamp Palace - Boss", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Flippers', 'Lamp', 'MoonPearl', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'UncleSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'ProgressiveSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'MasterSword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L3Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
            ["Swamp Palace - Boss", true, ['Flippers', 'Lamp', 'Bottle', 'Ether', 'Hookshot', 'L4Sword', 'KeyD6', 'KeyD6', 'KeyD6', 'BigKeyP3']],
        ];
    }
}
